# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from llm.observability.v1 import instrumentation_pb2 as llm_dot_observability_dot_v1_dot_instrumentation__pb2


class InstrumentationControlServiceStub(object):
    """Service definition for remote instrumentation control
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitInstrumentation = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/InitInstrumentation',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitInstrumentationRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitInstrumentationResponse.FromString,
                )
        self.DisableInstrumentation = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/DisableInstrumentation',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DisableInstrumentationRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DisableInstrumentationResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/GetStatus',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetStatusResponse.FromString,
                )
        self.DetectProvider = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/DetectProvider',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DetectProviderRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DetectProviderResponse.FromString,
                )
        self.TriggerTestCall = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/TriggerTestCall',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestCallRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestCallResponse.FromString,
                )
        self.TriggerTestStreamCall = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/TriggerTestStreamCall',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestStreamCallRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestStreamCallResponse.FromString,
                )
        self.CountTokens = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/CountTokens',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.CountTokensRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.CountTokensResponse.FromString,
                )
        self.ScanPiiInjection = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/ScanPiiInjection',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ScanPiiInjectionRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ScanPiiInjectionResponse.FromString,
                )
        self.ShouldSample = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/ShouldSample',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ShouldSampleRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ShouldSampleResponse.FromString,
                )
        self.InitMetrics = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/InitMetrics',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitMetricsRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitMetricsResponse.FromString,
                )
        self.GetMetricsHealth = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/GetMetricsHealth',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetMetricsHealthRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetMetricsHealthResponse.FromString,
                )
        self.RecordMetrics = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/RecordMetrics',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsResponse.FromString,
                )
        self.RecordMetricsBatch = channel.unary_unary(
                '/llm.observability.v1.InstrumentationControlService/RecordMetricsBatch',
                request_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsBatchRequest.SerializeToString,
                response_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsBatchResponse.FromString,
                )


class InstrumentationControlServiceServicer(object):
    """Service definition for remote instrumentation control
    """

    def InitInstrumentation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableInstrumentation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerTestCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerTestStreamCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPiiInjection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShouldSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetricsHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMetricsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstrumentationControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitInstrumentation': grpc.unary_unary_rpc_method_handler(
                    servicer.InitInstrumentation,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitInstrumentationRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitInstrumentationResponse.SerializeToString,
            ),
            'DisableInstrumentation': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableInstrumentation,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DisableInstrumentationRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DisableInstrumentationResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetStatusRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetStatusResponse.SerializeToString,
            ),
            'DetectProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectProvider,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DetectProviderRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.DetectProviderResponse.SerializeToString,
            ),
            'TriggerTestCall': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerTestCall,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestCallRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestCallResponse.SerializeToString,
            ),
            'TriggerTestStreamCall': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerTestStreamCall,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestStreamCallRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestStreamCallResponse.SerializeToString,
            ),
            'CountTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.CountTokens,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.CountTokensRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.CountTokensResponse.SerializeToString,
            ),
            'ScanPiiInjection': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPiiInjection,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ScanPiiInjectionRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ScanPiiInjectionResponse.SerializeToString,
            ),
            'ShouldSample': grpc.unary_unary_rpc_method_handler(
                    servicer.ShouldSample,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ShouldSampleRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.ShouldSampleResponse.SerializeToString,
            ),
            'InitMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.InitMetrics,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitMetricsRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitMetricsResponse.SerializeToString,
            ),
            'GetMetricsHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetricsHealth,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetMetricsHealthRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetMetricsHealthResponse.SerializeToString,
            ),
            'RecordMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordMetrics,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsResponse.SerializeToString,
            ),
            'RecordMetricsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordMetricsBatch,
                    request_deserializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsBatchRequest.FromString,
                    response_serializer=llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.observability.v1.InstrumentationControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InstrumentationControlService(object):
    """Service definition for remote instrumentation control
    """

    @staticmethod
    def InitInstrumentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/InitInstrumentation',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitInstrumentationRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitInstrumentationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableInstrumentation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/DisableInstrumentation',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.DisableInstrumentationRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.DisableInstrumentationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/GetStatus',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetStatusRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetectProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/DetectProvider',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.DetectProviderRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.DetectProviderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerTestCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/TriggerTestCall',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestCallRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerTestStreamCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/TriggerTestStreamCall',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestStreamCallRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.TriggerTestStreamCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CountTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/CountTokens',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.CountTokensRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.CountTokensResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScanPiiInjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/ScanPiiInjection',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.ScanPiiInjectionRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.ScanPiiInjectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShouldSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/ShouldSample',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.ShouldSampleRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.ShouldSampleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/InitMetrics',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitMetricsRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.InitMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetricsHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/GetMetricsHealth',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetMetricsHealthRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.GetMetricsHealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecordMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/RecordMetrics',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecordMetricsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llm.observability.v1.InstrumentationControlService/RecordMetricsBatch',
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsBatchRequest.SerializeToString,
            llm_dot_observability_dot_v1_dot_instrumentation__pb2.RecordMetricsBatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
