apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: ''
        spanStartTimeShift: '0s'
        spanEndTimeShift: '0s'
        filterByTraceID: false
        filterBySpanID: false
