max_connections = 400
shared_buffers = 512MB
effective_cache_size = 2GB
work_mem = 16MB
checkpoint_completion_target = 0.95
wal_buffers = 32MB
synchronous_commit = off
listen_addresses = '*'
max_wal_size = 2GB
wal_compression = on
full_page_writes = off
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
random_page_cost = 1.1
