from setuptools import setup, find_packages

setup(
    name="llm-messaging-sdk",
    version="1.0.0",
    description="A comprehensive messaging SDK following Hexagonal Architecture for Kafka, Schema Registry, and database integration",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="LLM Observability Platform",
    author_email="dev@example.com",
    url="https://github.com/example/llm-messaging-sdk",
    packages=find_packages(where=".", include=["infrastructure*"]),
    package_data={"infrastructure.messaging": ["py.typed"]},
    python_requires=">=3.8",
    install_requires=[
        "pydantic>=2.0.0",
        "psycopg2-binary>=2.9.0",
        "pymongo>=4.0.0",
        "confluent-kafka>=2.0.0",
        "requests>=2.28.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
            "isort>=5.12.0",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Distributed Computing",
    ],
    keywords=["kafka", "messaging", "schema-registry", "hexagonal-architecture", "postgresql", "mongodb"],
)
