#!/usr/bin/env bash
# infrastructure/orchestrator/scripts/fix_localhost_dns.sh
# Idempotent script: patch /etc/hosts, create .env (with escaped $ for docker-compose),
# and start traefik compose. Use sudo to run (needs to edit /etc/hosts and start containers).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ORCHESTRATOR_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
COMPOSE_DIR="${ORCHESTRATOR_DIR}/config/docker"
COMPOSE_FILE="${COMPOSE_DIR}/traefik-dynamic-docker.yaml"
ENV_FILE="${ORCHESTRATOR_DIR}/.env"
HOSTS_FILE="/etc/hosts"
BACKUP_DIR="/var/backups/traefik-hosts-backups"
NAMES=( "traefik-0.localhost" "scaibu.traefik" "temporal-ui.localhost" "scaibu.mongoexpress" "scaibu.kafka-ui" )

# Default non-conflicting host ports (can be changed in .env after first run)
DEFAULT_HTTP_PORT="${TRAEFIK_HTTP_PORT:-80}"
DEFAULT_HTTPS_PORT="${TRAEFIK_HTTPS_PORT:-443}"
DEFAULT_DASHBOARD_PORT="${TRAEFIK_DASHBOARD_PORT:-13101}"

echo "== Traefik local setup =="
echo "Compose file: ${COMPOSE_FILE}"
echo "Env file: ${ENV_FILE}"
echo "Will ensure hostnames: ${NAMES[*]}"
echo

# 1) Backup /etc/hosts
sudo mkdir -p "${BACKUP_DIR}"
TS=$(date +%Y%m%d_%H%M%S)
BACKUP="${BACKUP_DIR}/hosts.backup.${TS}"
sudo cp "${HOSTS_FILE}" "${BACKUP}"
echo "Backed up ${HOSTS_FILE} -> ${BACKUP}"

# 2) Patch /etc/hosts idempotently:
TMP_HOSTS="$(mktemp)"
# Copy existing hosts but comment ::1 lines for our names and remove existing occurrences to avoid duplicates
sudo awk -v names="$(IFS=,; echo "${NAMES[*]}")" '
BEGIN { split(names, list, ","); for (i in list) want[list[i]] = 1 }
{
  line = $0
  # If IPv6 loopback line contains any of our names, comment it out
  if ($1 ~ /^::1/ || $1 ~ /^fe80:/) {
    for (n in want) if (index(line, n) > 0) { if (substr(line,1,1) != "#") { print "# commented by fix_localhost_dns.sh: " line } else { print line }; next }
  }
  print line
}
' "${HOSTS_FILE}" | sudo tee "${TMP_HOSTS}" >/dev/null

# Remove any of our names from existing 127.0.0.1 lines to prevent duplicates
for n in "${NAMES[@]}"; do
  sudo sed -i -E "s/\\b${n}\\b//g" "${TMP_HOSTS}" || true
done

# Append canonical 127.0.0.1 line with our names (idempotent because earlier deletions removed duplicates)
CANONICAL="127.0.0.1"
for n in "${NAMES[@]}"; do CANONICAL="${CANONICAL} ${n}"; done
echo "${CANONICAL}" | sudo tee -a "${TMP_HOSTS}" >/dev/null

# Finalize
sudo cp "${TMP_HOSTS}" "${HOSTS_FILE}"
sudo chmod 644 "${HOSTS_FILE}"
rm -f "${TMP_HOSTS}"

echo "/etc/hosts patched. Current matching lines:"
sudo grep -E "traefik-0.localhost|scaibu.traefik|temporal-ui.localhost" "${HOSTS_FILE}" || true
echo

# 3) Write .env file (no authentication for local dev - automatic access)
# Write .env file atomically
cat > "${ENV_FILE}.tmp" <<EOF
# Auto-generated by fix_localhost_dns.sh - safe defaults for local dev
# No authentication required - automatic access for local development
# To enable authentication, set TRAEFIK_BASIC_AUTH=username:\$\$apr1\$\$hash
TRAEFIK_BASIC_AUTH=
TRAEFIK_HTTP_PORT=${DEFAULT_HTTP_PORT}
TRAEFIK_HTTPS_PORT=${DEFAULT_HTTPS_PORT}
TRAEFIK_DASHBOARD_PORT=${DEFAULT_DASHBOARD_PORT}
ACME_EMAIL=admin@localhost
TRAEFIK_INSTANCE_ID=0
TEMPORAL_NETWORK=temporal-network
OBSERVABILITY_NETWORK=observability-network
DATA_NETWORK=data-network
MESSAGING_NETWORK=messaging-network
CICD_NETWORK=cicd-network
EOF

mv "${ENV_FILE}.tmp" "${ENV_FILE}"
chmod 600 "${ENV_FILE}"
echo "Wrote ${ENV_FILE} with configuration (no auth required):"
grep -E 'TRAEFIK_HTTP_PORT|TRAEFIK_HTTPS_PORT|TRAEFIK_DASHBOARD_PORT' "${ENV_FILE}"
echo

# 4) Ensure networks exist (create if needed)
echo "Ensuring required Docker networks exist..."
for network in temporal-network observability-network data-network messaging-network cicd-network; do
  if ! docker network inspect "${network}" >/dev/null 2>&1; then
    echo "Creating network: ${network}"
    docker network create "${network}"
  else
    echo "Network already exists: ${network}"
  fi
done
echo

# 5) Start docker compose (use docker compose if available, fallback to docker-compose)
COMPOSE_CMD=""
if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_CMD="docker-compose"
else
  echo "ERROR: docker compose not found (neither 'docker compose' nor 'docker-compose'). Aborting."
  exit 2
fi

echo "Starting Traefik using: ${COMPOSE_CMD}docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d (with env from ${ENV_FILE})"
( cd "${COMPOSE_DIR}" && ${COMPOSE_CMD} -f "$(basename "${COMPOSE_FILE}")" --env-file "${ENV_FILE}" up -d )

echo
echo "===================================================================="
echo "Traefik startup complete! No authentication required."
echo "===================================================================="
echo
echo "📊 Traefik Dashboard:"
echo "   http://traefik-0.localhost:${DEFAULT_DASHBOARD_PORT}/"
echo "   http://scaibu.traefik:${DEFAULT_DASHBOARD_PORT}/"
echo
echo "🕐 Temporal UI (via Traefik):"
echo "   http://temporal-ui.localhost:${DEFAULT_DASHBOARD_PORT}/"
echo
echo "🕐 Temporal UI (direct):"
echo "   http://localhost:8080/"
echo
echo "📝 Logs: docker logs -f traefik-instance-0"
echo "===================================================================="
