version: "3.9"

services:
  webrtc-client:
    build:
      context: ../..
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_SIGNALING_URL=ws://localhost:8010
      - VITE_TURN_USER=webrtc
      - VITE_TURN_CREDENTIAL=webrtc123
    restart: unless-stopped
