[obs_nodes]
# Define your target VM nodes here (IP or domain name)
# Example:
# node1 ansible_host=192.168.1.50 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[obs_nodes:vars]
ansible_python_interpreter=/usr/bin/python3
