from typing import Protocol

class MetricsPort(Protocol):
    def record_workflow_run_latency(self, workflow_name: str, latency_ms: float) -> None: ...
    def record_baseline_updates(self, count: int) -> None: ...
    def record_rollup_rows(self, count: int) -> None: ...
    def record_invariant_violation(self, invariant_id: str) -> None: ...
