version: '3.8'

services:
  embedding-worker:
    build:
      context: ../../../
      dockerfile: packages/python/queue-embedding-worker/build/Dockerfile.dev
    container_name: queue-embedding-worker-dev
    volumes:
      - ../../../packages/python/queue-embedding-worker:/app
    ports:
      - "8002:8000"
    environment:
      - DEPLOYMENT_ENV=dev
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - observability-network

networks:
  observability-network:
    external: true
