// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "llm/observability/v1/instrumentation.proto" (package "llm.observability.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message llm.observability.v1.InitInstrumentationRequest
 */
export interface InitInstrumentationRequest {
    /**
     * @generated from protobuf field: string service_name = 1;
     */
    serviceName: string;
    /**
     * @generated from protobuf field: string environment = 2;
     */
    environment: string;
}
/**
 * @generated from protobuf message llm.observability.v1.DisableInstrumentationRequest
 */
export interface DisableInstrumentationRequest {
}
/**
 * @generated from protobuf message llm.observability.v1.GetStatusRequest
 */
export interface GetStatusRequest {
}
/**
 * @generated from protobuf message llm.observability.v1.DetectProviderRequest
 */
export interface DetectProviderRequest {
    /**
     * @generated from protobuf field: string url = 1;
     */
    url: string;
    /**
     * @generated from protobuf field: string body = 2;
     */
    body: string;
}
/**
 * @generated from protobuf message llm.observability.v1.DetectProviderResponse
 */
export interface DetectProviderResponse {
    /**
     * @generated from protobuf field: string provider = 1;
     */
    provider: string;
    /**
     * @generated from protobuf field: string model = 2;
     */
    model: string;
}
/**
 * @generated from protobuf message llm.observability.v1.TriggerTestCallRequest
 */
export interface TriggerTestCallRequest {
    /**
     * @generated from protobuf field: string method = 1;
     */
    method: string;
    /**
     * @generated from protobuf field: string provider = 2;
     */
    provider: string;
}
/**
 * @generated from protobuf message llm.observability.v1.TriggerTestStreamCallRequest
 */
export interface TriggerTestStreamCallRequest {
    /**
     * @generated from protobuf field: string provider = 1;
     */
    provider: string;
    /**
     * @generated from protobuf field: repeated string chunks = 2;
     */
    chunks: string[];
}
/**
 * @generated from protobuf message llm.observability.v1.InstrumentationResponse
 */
export interface InstrumentationResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: llm.observability.v1.InstrumentationStatus status = 3;
     */
    status: InstrumentationStatus;
}
/**
 * @generated from protobuf message llm.observability.v1.InitInstrumentationResponse
 */
export interface InitInstrumentationResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: llm.observability.v1.InstrumentationStatus status = 3;
     */
    status: InstrumentationStatus;
}
/**
 * @generated from protobuf message llm.observability.v1.DisableInstrumentationResponse
 */
export interface DisableInstrumentationResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: llm.observability.v1.InstrumentationStatus status = 3;
     */
    status: InstrumentationStatus;
}
/**
 * @generated from protobuf message llm.observability.v1.GetStatusResponse
 */
export interface GetStatusResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: llm.observability.v1.InstrumentationStatus status = 3;
     */
    status: InstrumentationStatus;
}
/**
 * @generated from protobuf message llm.observability.v1.TriggerTestCallResponse
 */
export interface TriggerTestCallResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: llm.observability.v1.InstrumentationStatus status = 3;
     */
    status: InstrumentationStatus;
}
/**
 * @generated from protobuf message llm.observability.v1.TriggerTestStreamCallResponse
 */
export interface TriggerTestStreamCallResponse {
    /**
     * @generated from protobuf field: bool success = 1;
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: llm.observability.v1.InstrumentationStatus status = 3;
     */
    status: InstrumentationStatus;
}
/**
 * Event for publishing instrumentation state changes to Kafka
 *
 * @generated from protobuf message llm.observability.v1.InstrumentationEvent
 */
export interface InstrumentationEvent {
    /**
     * @generated from protobuf field: string event_id = 1;
     */
    eventId: string;
    /**
     * @generated from protobuf field: string timestamp_utc = 2;
     */
    timestampUtc: string;
    /**
     * @generated from protobuf field: string service_name = 3;
     */
    serviceName: string;
    /**
     * @generated from protobuf field: llm.observability.v1.InstrumentationStatus action = 4;
     */
    action: InstrumentationStatus;
    /**
     * @generated from protobuf field: string metadata = 5;
     */
    metadata: string; // JSON blob for extra details
}
/**
 * @generated from protobuf message llm.observability.v1.CountTokensRequest
 */
export interface CountTokensRequest {
    /**
     * @generated from protobuf field: string prompt = 1;
     */
    prompt: string;
    /**
     * @generated from protobuf field: string model = 2;
     */
    model: string;
    /**
     * @generated from protobuf field: string provider = 3;
     */
    provider: string;
}
/**
 * @generated from protobuf message llm.observability.v1.CountTokensResponse
 */
export interface CountTokensResponse {
    /**
     * @generated from protobuf field: int32 tokens = 1;
     */
    tokens: number;
    /**
     * @generated from protobuf field: string method = 2;
     */
    method: string;
}
/**
 * @generated from protobuf message llm.observability.v1.ScanPiiInjectionRequest
 */
export interface ScanPiiInjectionRequest {
    /**
     * @generated from protobuf field: string prompt = 1;
     */
    prompt: string;
}
/**
 * @generated from protobuf message llm.observability.v1.ScanPiiInjectionResponse
 */
export interface ScanPiiInjectionResponse {
    /**
     * @generated from protobuf field: bool pii_detected = 1;
     */
    piiDetected: boolean;
    /**
     * @generated from protobuf field: bool injection_attempt = 2;
     */
    injectionAttempt: boolean;
}
/**
 * @generated from protobuf message llm.observability.v1.InitMetricsRequest
 */
export interface InitMetricsRequest {
    /**
     * @generated from protobuf field: optional int32 port = 1;
     */
    port?: number;
}
/**
 * @generated from protobuf message llm.observability.v1.GetMetricsHealthRequest
 */
export interface GetMetricsHealthRequest {
}
/**
 * @generated from protobuf message llm.observability.v1.InitMetricsResponse
 */
export interface InitMetricsResponse {
    /**
     * @generated from protobuf field: bool initialized = 1;
     */
    initialized: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
}
/**
 * @generated from protobuf message llm.observability.v1.GetMetricsHealthResponse
 */
export interface GetMetricsHealthResponse {
    /**
     * @generated from protobuf field: bool initialized = 1;
     */
    initialized: boolean;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
}
/**
 * @generated from protobuf message llm.observability.v1.RecordMetricsRequest
 */
export interface RecordMetricsRequest {
    /**
     * @generated from protobuf field: string model = 1;
     */
    model: string;
    /**
     * @generated from protobuf field: string provider = 2;
     */
    provider: string;
    /**
     * @generated from protobuf field: string service_name = 3;
     */
    serviceName: string;
    /**
     * @generated from protobuf field: optional int32 prompt_tokens = 4;
     */
    promptTokens?: number;
    /**
     * @generated from protobuf field: optional int32 completion_tokens = 5;
     */
    completionTokens?: number;
    /**
     * @generated from protobuf field: optional int64 cost_usd_micro = 6;
     */
    costUsdMicro?: bigint;
    /**
     * @generated from protobuf field: optional int32 latency_ms_total = 7;
     */
    latencyMsTotal?: number;
    /**
     * @generated from protobuf field: optional int32 latency_ms_ttft = 8;
     */
    latencyMsTtft?: number;
    /**
     * @generated from protobuf field: optional string finish_reason = 9;
     */
    finishReason?: string;
    /**
     * @generated from protobuf field: string status = 10;
     */
    status: string;
    /**
     * @generated from protobuf field: bool pii_detected = 11;
     */
    piiDetected: boolean;
    /**
     * @generated from protobuf field: bool injection_attempt = 12;
     */
    injectionAttempt: boolean;
    /**
     * @generated from protobuf field: int32 retry_count = 13;
     */
    retryCount: number;
}
/**
 * @generated from protobuf message llm.observability.v1.RecordMetricsResponse
 */
export interface RecordMetricsResponse {
    /**
     * @generated from protobuf field: bool recorded = 1;
     */
    recorded: boolean;
    /**
     * @generated from protobuf field: optional int64 cost_usd_micro = 2;
     */
    costUsdMicro?: bigint;
    /**
     * @generated from protobuf field: optional string price_version = 3;
     */
    priceVersion?: string;
}
/**
 * @generated from protobuf message llm.observability.v1.RecordMetricsBatchRequest
 */
export interface RecordMetricsBatchRequest {
    /**
     * @generated from protobuf field: repeated llm.observability.v1.RecordMetricsRequest spans = 1;
     */
    spans: RecordMetricsRequest[];
}
/**
 * @generated from protobuf message llm.observability.v1.RecordMetricsBatchResponse
 */
export interface RecordMetricsBatchResponse {
    /**
     * @generated from protobuf field: int32 recorded_count = 1;
     */
    recordedCount: number;
}
/**
 * InstrumentationStatus represents the current state of auto-instrumentation.
 *
 * @generated from protobuf enum llm.observability.v1.InstrumentationStatus
 */
export enum InstrumentationStatus {
    /**
     * @generated from protobuf enum value: INSTRUMENTATION_STATUS_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: INSTRUMENTATION_STATUS_INITIALIZED = 1;
     */
    INITIALIZED = 1,
    /**
     * @generated from protobuf enum value: INSTRUMENTATION_STATUS_DISABLED = 2;
     */
    DISABLED = 2,
    /**
     * @generated from protobuf enum value: INSTRUMENTATION_STATUS_PARTIAL = 3;
     */
    PARTIAL = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class InitInstrumentationRequest$Type extends MessageType<InitInstrumentationRequest> {
    constructor() {
        super("llm.observability.v1.InitInstrumentationRequest", [
            { no: 1, name: "service_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "environment", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InitInstrumentationRequest>): InitInstrumentationRequest {
        const message = { serviceName: "", environment: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<InitInstrumentationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitInstrumentationRequest): InitInstrumentationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string service_name */ 1:
                    message.serviceName = reader.string();
                    break;
                case /* string environment */ 2:
                    message.environment = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitInstrumentationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string service_name = 1; */
        if (message.serviceName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.serviceName);
        /* string environment = 2; */
        if (message.environment !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.environment);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.InitInstrumentationRequest
 */
export const InitInstrumentationRequest = new InitInstrumentationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DisableInstrumentationRequest$Type extends MessageType<DisableInstrumentationRequest> {
    constructor() {
        super("llm.observability.v1.DisableInstrumentationRequest", []);
    }
    create(value?: PartialMessage<DisableInstrumentationRequest>): DisableInstrumentationRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DisableInstrumentationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DisableInstrumentationRequest): DisableInstrumentationRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: DisableInstrumentationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.DisableInstrumentationRequest
 */
export const DisableInstrumentationRequest = new DisableInstrumentationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetStatusRequest$Type extends MessageType<GetStatusRequest> {
    constructor() {
        super("llm.observability.v1.GetStatusRequest", []);
    }
    create(value?: PartialMessage<GetStatusRequest>): GetStatusRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetStatusRequest): GetStatusRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: GetStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.GetStatusRequest
 */
export const GetStatusRequest = new GetStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetectProviderRequest$Type extends MessageType<DetectProviderRequest> {
    constructor() {
        super("llm.observability.v1.DetectProviderRequest", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "body", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DetectProviderRequest>): DetectProviderRequest {
        const message = { url: "", body: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DetectProviderRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetectProviderRequest): DetectProviderRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* string body */ 2:
                    message.body = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetectProviderRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* string body = 2; */
        if (message.body !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.body);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.DetectProviderRequest
 */
export const DetectProviderRequest = new DetectProviderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetectProviderResponse$Type extends MessageType<DetectProviderResponse> {
    constructor() {
        super("llm.observability.v1.DetectProviderResponse", [
            { no: 1, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DetectProviderResponse>): DetectProviderResponse {
        const message = { provider: "", model: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DetectProviderResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetectProviderResponse): DetectProviderResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string provider */ 1:
                    message.provider = reader.string();
                    break;
                case /* string model */ 2:
                    message.model = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetectProviderResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string provider = 1; */
        if (message.provider !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.provider);
        /* string model = 2; */
        if (message.model !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.model);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.DetectProviderResponse
 */
export const DetectProviderResponse = new DetectProviderResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerTestCallRequest$Type extends MessageType<TriggerTestCallRequest> {
    constructor() {
        super("llm.observability.v1.TriggerTestCallRequest", [
            { no: 1, name: "method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TriggerTestCallRequest>): TriggerTestCallRequest {
        const message = { method: "", provider: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TriggerTestCallRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TriggerTestCallRequest): TriggerTestCallRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string method */ 1:
                    message.method = reader.string();
                    break;
                case /* string provider */ 2:
                    message.provider = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TriggerTestCallRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string method = 1; */
        if (message.method !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.method);
        /* string provider = 2; */
        if (message.provider !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.provider);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.TriggerTestCallRequest
 */
export const TriggerTestCallRequest = new TriggerTestCallRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerTestStreamCallRequest$Type extends MessageType<TriggerTestStreamCallRequest> {
    constructor() {
        super("llm.observability.v1.TriggerTestStreamCallRequest", [
            { no: 1, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "chunks", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TriggerTestStreamCallRequest>): TriggerTestStreamCallRequest {
        const message = { provider: "", chunks: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TriggerTestStreamCallRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TriggerTestStreamCallRequest): TriggerTestStreamCallRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string provider */ 1:
                    message.provider = reader.string();
                    break;
                case /* repeated string chunks */ 2:
                    message.chunks.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TriggerTestStreamCallRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string provider = 1; */
        if (message.provider !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.provider);
        /* repeated string chunks = 2; */
        for (let i = 0; i < message.chunks.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.chunks[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.TriggerTestStreamCallRequest
 */
export const TriggerTestStreamCallRequest = new TriggerTestStreamCallRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InstrumentationResponse$Type extends MessageType<InstrumentationResponse> {
    constructor() {
        super("llm.observability.v1.InstrumentationResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["llm.observability.v1.InstrumentationStatus", InstrumentationStatus, "INSTRUMENTATION_STATUS_"] }
        ]);
    }
    create(value?: PartialMessage<InstrumentationResponse>): InstrumentationResponse {
        const message = { success: false, message: "", status: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<InstrumentationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InstrumentationResponse): InstrumentationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* llm.observability.v1.InstrumentationStatus status */ 3:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InstrumentationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* llm.observability.v1.InstrumentationStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.InstrumentationResponse
 */
export const InstrumentationResponse = new InstrumentationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InitInstrumentationResponse$Type extends MessageType<InitInstrumentationResponse> {
    constructor() {
        super("llm.observability.v1.InitInstrumentationResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["llm.observability.v1.InstrumentationStatus", InstrumentationStatus, "INSTRUMENTATION_STATUS_"] }
        ]);
    }
    create(value?: PartialMessage<InitInstrumentationResponse>): InitInstrumentationResponse {
        const message = { success: false, message: "", status: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<InitInstrumentationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitInstrumentationResponse): InitInstrumentationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* llm.observability.v1.InstrumentationStatus status */ 3:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitInstrumentationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* llm.observability.v1.InstrumentationStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.InitInstrumentationResponse
 */
export const InitInstrumentationResponse = new InitInstrumentationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DisableInstrumentationResponse$Type extends MessageType<DisableInstrumentationResponse> {
    constructor() {
        super("llm.observability.v1.DisableInstrumentationResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["llm.observability.v1.InstrumentationStatus", InstrumentationStatus, "INSTRUMENTATION_STATUS_"] }
        ]);
    }
    create(value?: PartialMessage<DisableInstrumentationResponse>): DisableInstrumentationResponse {
        const message = { success: false, message: "", status: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DisableInstrumentationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DisableInstrumentationResponse): DisableInstrumentationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* llm.observability.v1.InstrumentationStatus status */ 3:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DisableInstrumentationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* llm.observability.v1.InstrumentationStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.DisableInstrumentationResponse
 */
export const DisableInstrumentationResponse = new DisableInstrumentationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetStatusResponse$Type extends MessageType<GetStatusResponse> {
    constructor() {
        super("llm.observability.v1.GetStatusResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["llm.observability.v1.InstrumentationStatus", InstrumentationStatus, "INSTRUMENTATION_STATUS_"] }
        ]);
    }
    create(value?: PartialMessage<GetStatusResponse>): GetStatusResponse {
        const message = { success: false, message: "", status: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetStatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetStatusResponse): GetStatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* llm.observability.v1.InstrumentationStatus status */ 3:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetStatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* llm.observability.v1.InstrumentationStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.GetStatusResponse
 */
export const GetStatusResponse = new GetStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerTestCallResponse$Type extends MessageType<TriggerTestCallResponse> {
    constructor() {
        super("llm.observability.v1.TriggerTestCallResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["llm.observability.v1.InstrumentationStatus", InstrumentationStatus, "INSTRUMENTATION_STATUS_"] }
        ]);
    }
    create(value?: PartialMessage<TriggerTestCallResponse>): TriggerTestCallResponse {
        const message = { success: false, message: "", status: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TriggerTestCallResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TriggerTestCallResponse): TriggerTestCallResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* llm.observability.v1.InstrumentationStatus status */ 3:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TriggerTestCallResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* llm.observability.v1.InstrumentationStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.TriggerTestCallResponse
 */
export const TriggerTestCallResponse = new TriggerTestCallResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerTestStreamCallResponse$Type extends MessageType<TriggerTestStreamCallResponse> {
    constructor() {
        super("llm.observability.v1.TriggerTestStreamCallResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["llm.observability.v1.InstrumentationStatus", InstrumentationStatus, "INSTRUMENTATION_STATUS_"] }
        ]);
    }
    create(value?: PartialMessage<TriggerTestStreamCallResponse>): TriggerTestStreamCallResponse {
        const message = { success: false, message: "", status: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TriggerTestStreamCallResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TriggerTestStreamCallResponse): TriggerTestStreamCallResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* llm.observability.v1.InstrumentationStatus status */ 3:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TriggerTestStreamCallResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* llm.observability.v1.InstrumentationStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.TriggerTestStreamCallResponse
 */
export const TriggerTestStreamCallResponse = new TriggerTestStreamCallResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InstrumentationEvent$Type extends MessageType<InstrumentationEvent> {
    constructor() {
        super("llm.observability.v1.InstrumentationEvent", [
            { no: 1, name: "event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "timestamp_utc", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "service_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "action", kind: "enum", T: () => ["llm.observability.v1.InstrumentationStatus", InstrumentationStatus, "INSTRUMENTATION_STATUS_"] },
            { no: 5, name: "metadata", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InstrumentationEvent>): InstrumentationEvent {
        const message = { eventId: "", timestampUtc: "", serviceName: "", action: 0, metadata: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<InstrumentationEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InstrumentationEvent): InstrumentationEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_id */ 1:
                    message.eventId = reader.string();
                    break;
                case /* string timestamp_utc */ 2:
                    message.timestampUtc = reader.string();
                    break;
                case /* string service_name */ 3:
                    message.serviceName = reader.string();
                    break;
                case /* llm.observability.v1.InstrumentationStatus action */ 4:
                    message.action = reader.int32();
                    break;
                case /* string metadata */ 5:
                    message.metadata = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InstrumentationEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_id = 1; */
        if (message.eventId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventId);
        /* string timestamp_utc = 2; */
        if (message.timestampUtc !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.timestampUtc);
        /* string service_name = 3; */
        if (message.serviceName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.serviceName);
        /* llm.observability.v1.InstrumentationStatus action = 4; */
        if (message.action !== 0)
            writer.tag(4, WireType.Varint).int32(message.action);
        /* string metadata = 5; */
        if (message.metadata !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.metadata);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.InstrumentationEvent
 */
export const InstrumentationEvent = new InstrumentationEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CountTokensRequest$Type extends MessageType<CountTokensRequest> {
    constructor() {
        super("llm.observability.v1.CountTokensRequest", [
            { no: 1, name: "prompt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CountTokensRequest>): CountTokensRequest {
        const message = { prompt: "", model: "", provider: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CountTokensRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CountTokensRequest): CountTokensRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string prompt */ 1:
                    message.prompt = reader.string();
                    break;
                case /* string model */ 2:
                    message.model = reader.string();
                    break;
                case /* string provider */ 3:
                    message.provider = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CountTokensRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string prompt = 1; */
        if (message.prompt !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.prompt);
        /* string model = 2; */
        if (message.model !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.model);
        /* string provider = 3; */
        if (message.provider !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.provider);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.CountTokensRequest
 */
export const CountTokensRequest = new CountTokensRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CountTokensResponse$Type extends MessageType<CountTokensResponse> {
    constructor() {
        super("llm.observability.v1.CountTokensResponse", [
            { no: 1, name: "tokens", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "method", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CountTokensResponse>): CountTokensResponse {
        const message = { tokens: 0, method: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CountTokensResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CountTokensResponse): CountTokensResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 tokens */ 1:
                    message.tokens = reader.int32();
                    break;
                case /* string method */ 2:
                    message.method = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CountTokensResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 tokens = 1; */
        if (message.tokens !== 0)
            writer.tag(1, WireType.Varint).int32(message.tokens);
        /* string method = 2; */
        if (message.method !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.method);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.CountTokensResponse
 */
export const CountTokensResponse = new CountTokensResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanPiiInjectionRequest$Type extends MessageType<ScanPiiInjectionRequest> {
    constructor() {
        super("llm.observability.v1.ScanPiiInjectionRequest", [
            { no: 1, name: "prompt", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScanPiiInjectionRequest>): ScanPiiInjectionRequest {
        const message = { prompt: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ScanPiiInjectionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanPiiInjectionRequest): ScanPiiInjectionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string prompt */ 1:
                    message.prompt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanPiiInjectionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string prompt = 1; */
        if (message.prompt !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.prompt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.ScanPiiInjectionRequest
 */
export const ScanPiiInjectionRequest = new ScanPiiInjectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanPiiInjectionResponse$Type extends MessageType<ScanPiiInjectionResponse> {
    constructor() {
        super("llm.observability.v1.ScanPiiInjectionResponse", [
            { no: 1, name: "pii_detected", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "injection_attempt", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ScanPiiInjectionResponse>): ScanPiiInjectionResponse {
        const message = { piiDetected: false, injectionAttempt: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ScanPiiInjectionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanPiiInjectionResponse): ScanPiiInjectionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool pii_detected */ 1:
                    message.piiDetected = reader.bool();
                    break;
                case /* bool injection_attempt */ 2:
                    message.injectionAttempt = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanPiiInjectionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool pii_detected = 1; */
        if (message.piiDetected !== false)
            writer.tag(1, WireType.Varint).bool(message.piiDetected);
        /* bool injection_attempt = 2; */
        if (message.injectionAttempt !== false)
            writer.tag(2, WireType.Varint).bool(message.injectionAttempt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.ScanPiiInjectionResponse
 */
export const ScanPiiInjectionResponse = new ScanPiiInjectionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InitMetricsRequest$Type extends MessageType<InitMetricsRequest> {
    constructor() {
        super("llm.observability.v1.InitMetricsRequest", [
            { no: 1, name: "port", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<InitMetricsRequest>): InitMetricsRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<InitMetricsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitMetricsRequest): InitMetricsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional int32 port */ 1:
                    message.port = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitMetricsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional int32 port = 1; */
        if (message.port !== undefined)
            writer.tag(1, WireType.Varint).int32(message.port);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.InitMetricsRequest
 */
export const InitMetricsRequest = new InitMetricsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMetricsHealthRequest$Type extends MessageType<GetMetricsHealthRequest> {
    constructor() {
        super("llm.observability.v1.GetMetricsHealthRequest", []);
    }
    create(value?: PartialMessage<GetMetricsHealthRequest>): GetMetricsHealthRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetMetricsHealthRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMetricsHealthRequest): GetMetricsHealthRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: GetMetricsHealthRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.GetMetricsHealthRequest
 */
export const GetMetricsHealthRequest = new GetMetricsHealthRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InitMetricsResponse$Type extends MessageType<InitMetricsResponse> {
    constructor() {
        super("llm.observability.v1.InitMetricsResponse", [
            { no: 1, name: "initialized", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InitMetricsResponse>): InitMetricsResponse {
        const message = { initialized: false, message: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<InitMetricsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitMetricsResponse): InitMetricsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool initialized */ 1:
                    message.initialized = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitMetricsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool initialized = 1; */
        if (message.initialized !== false)
            writer.tag(1, WireType.Varint).bool(message.initialized);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.InitMetricsResponse
 */
export const InitMetricsResponse = new InitMetricsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMetricsHealthResponse$Type extends MessageType<GetMetricsHealthResponse> {
    constructor() {
        super("llm.observability.v1.GetMetricsHealthResponse", [
            { no: 1, name: "initialized", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMetricsHealthResponse>): GetMetricsHealthResponse {
        const message = { initialized: false, message: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetMetricsHealthResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMetricsHealthResponse): GetMetricsHealthResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool initialized */ 1:
                    message.initialized = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMetricsHealthResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool initialized = 1; */
        if (message.initialized !== false)
            writer.tag(1, WireType.Varint).bool(message.initialized);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.GetMetricsHealthResponse
 */
export const GetMetricsHealthResponse = new GetMetricsHealthResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordMetricsRequest$Type extends MessageType<RecordMetricsRequest> {
    constructor() {
        super("llm.observability.v1.RecordMetricsRequest", [
            { no: 1, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "service_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "prompt_tokens", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "completion_tokens", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "cost_usd_micro", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "latency_ms_total", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "latency_ms_ttft", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "finish_reason", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "pii_detected", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "injection_attempt", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "retry_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RecordMetricsRequest>): RecordMetricsRequest {
        const message = { model: "", provider: "", serviceName: "", status: "", piiDetected: false, injectionAttempt: false, retryCount: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RecordMetricsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordMetricsRequest): RecordMetricsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string model */ 1:
                    message.model = reader.string();
                    break;
                case /* string provider */ 2:
                    message.provider = reader.string();
                    break;
                case /* string service_name */ 3:
                    message.serviceName = reader.string();
                    break;
                case /* optional int32 prompt_tokens */ 4:
                    message.promptTokens = reader.int32();
                    break;
                case /* optional int32 completion_tokens */ 5:
                    message.completionTokens = reader.int32();
                    break;
                case /* optional int64 cost_usd_micro */ 6:
                    message.costUsdMicro = reader.int64().toBigInt();
                    break;
                case /* optional int32 latency_ms_total */ 7:
                    message.latencyMsTotal = reader.int32();
                    break;
                case /* optional int32 latency_ms_ttft */ 8:
                    message.latencyMsTtft = reader.int32();
                    break;
                case /* optional string finish_reason */ 9:
                    message.finishReason = reader.string();
                    break;
                case /* string status */ 10:
                    message.status = reader.string();
                    break;
                case /* bool pii_detected */ 11:
                    message.piiDetected = reader.bool();
                    break;
                case /* bool injection_attempt */ 12:
                    message.injectionAttempt = reader.bool();
                    break;
                case /* int32 retry_count */ 13:
                    message.retryCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordMetricsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string model = 1; */
        if (message.model !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.model);
        /* string provider = 2; */
        if (message.provider !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.provider);
        /* string service_name = 3; */
        if (message.serviceName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.serviceName);
        /* optional int32 prompt_tokens = 4; */
        if (message.promptTokens !== undefined)
            writer.tag(4, WireType.Varint).int32(message.promptTokens);
        /* optional int32 completion_tokens = 5; */
        if (message.completionTokens !== undefined)
            writer.tag(5, WireType.Varint).int32(message.completionTokens);
        /* optional int64 cost_usd_micro = 6; */
        if (message.costUsdMicro !== undefined)
            writer.tag(6, WireType.Varint).int64(message.costUsdMicro);
        /* optional int32 latency_ms_total = 7; */
        if (message.latencyMsTotal !== undefined)
            writer.tag(7, WireType.Varint).int32(message.latencyMsTotal);
        /* optional int32 latency_ms_ttft = 8; */
        if (message.latencyMsTtft !== undefined)
            writer.tag(8, WireType.Varint).int32(message.latencyMsTtft);
        /* optional string finish_reason = 9; */
        if (message.finishReason !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.finishReason);
        /* string status = 10; */
        if (message.status !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.status);
        /* bool pii_detected = 11; */
        if (message.piiDetected !== false)
            writer.tag(11, WireType.Varint).bool(message.piiDetected);
        /* bool injection_attempt = 12; */
        if (message.injectionAttempt !== false)
            writer.tag(12, WireType.Varint).bool(message.injectionAttempt);
        /* int32 retry_count = 13; */
        if (message.retryCount !== 0)
            writer.tag(13, WireType.Varint).int32(message.retryCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.RecordMetricsRequest
 */
export const RecordMetricsRequest = new RecordMetricsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordMetricsResponse$Type extends MessageType<RecordMetricsResponse> {
    constructor() {
        super("llm.observability.v1.RecordMetricsResponse", [
            { no: 1, name: "recorded", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "cost_usd_micro", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "price_version", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RecordMetricsResponse>): RecordMetricsResponse {
        const message = { recorded: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RecordMetricsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordMetricsResponse): RecordMetricsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool recorded */ 1:
                    message.recorded = reader.bool();
                    break;
                case /* optional int64 cost_usd_micro */ 2:
                    message.costUsdMicro = reader.int64().toBigInt();
                    break;
                case /* optional string price_version */ 3:
                    message.priceVersion = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordMetricsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool recorded = 1; */
        if (message.recorded !== false)
            writer.tag(1, WireType.Varint).bool(message.recorded);
        /* optional int64 cost_usd_micro = 2; */
        if (message.costUsdMicro !== undefined)
            writer.tag(2, WireType.Varint).int64(message.costUsdMicro);
        /* optional string price_version = 3; */
        if (message.priceVersion !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.priceVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.RecordMetricsResponse
 */
export const RecordMetricsResponse = new RecordMetricsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordMetricsBatchRequest$Type extends MessageType<RecordMetricsBatchRequest> {
    constructor() {
        super("llm.observability.v1.RecordMetricsBatchRequest", [
            { no: 1, name: "spans", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => RecordMetricsRequest }
        ]);
    }
    create(value?: PartialMessage<RecordMetricsBatchRequest>): RecordMetricsBatchRequest {
        const message = { spans: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RecordMetricsBatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordMetricsBatchRequest): RecordMetricsBatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated llm.observability.v1.RecordMetricsRequest spans */ 1:
                    message.spans.push(RecordMetricsRequest.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordMetricsBatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated llm.observability.v1.RecordMetricsRequest spans = 1; */
        for (let i = 0; i < message.spans.length; i++)
            RecordMetricsRequest.internalBinaryWrite(message.spans[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.RecordMetricsBatchRequest
 */
export const RecordMetricsBatchRequest = new RecordMetricsBatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordMetricsBatchResponse$Type extends MessageType<RecordMetricsBatchResponse> {
    constructor() {
        super("llm.observability.v1.RecordMetricsBatchResponse", [
            { no: 1, name: "recorded_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RecordMetricsBatchResponse>): RecordMetricsBatchResponse {
        const message = { recordedCount: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RecordMetricsBatchResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordMetricsBatchResponse): RecordMetricsBatchResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 recorded_count */ 1:
                    message.recordedCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordMetricsBatchResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 recorded_count = 1; */
        if (message.recordedCount !== 0)
            writer.tag(1, WireType.Varint).int32(message.recordedCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.observability.v1.RecordMetricsBatchResponse
 */
export const RecordMetricsBatchResponse = new RecordMetricsBatchResponse$Type();
/**
 * @generated ServiceType for protobuf service llm.observability.v1.InstrumentationControlService
 */
export const InstrumentationControlService = new ServiceType("llm.observability.v1.InstrumentationControlService", [
    { name: "InitInstrumentation", options: {}, I: InitInstrumentationRequest, O: InitInstrumentationResponse },
    { name: "DisableInstrumentation", options: {}, I: DisableInstrumentationRequest, O: DisableInstrumentationResponse },
    { name: "GetStatus", options: {}, I: GetStatusRequest, O: GetStatusResponse },
    { name: "DetectProvider", options: {}, I: DetectProviderRequest, O: DetectProviderResponse },
    { name: "TriggerTestCall", options: {}, I: TriggerTestCallRequest, O: TriggerTestCallResponse },
    { name: "TriggerTestStreamCall", options: {}, I: TriggerTestStreamCallRequest, O: TriggerTestStreamCallResponse },
    { name: "CountTokens", options: {}, I: CountTokensRequest, O: CountTokensResponse },
    { name: "ScanPiiInjection", options: {}, I: ScanPiiInjectionRequest, O: ScanPiiInjectionResponse },
    { name: "InitMetrics", options: {}, I: InitMetricsRequest, O: InitMetricsResponse },
    { name: "GetMetricsHealth", options: {}, I: GetMetricsHealthRequest, O: GetMetricsHealthResponse },
    { name: "RecordMetrics", options: {}, I: RecordMetricsRequest, O: RecordMetricsResponse },
    { name: "RecordMetricsBatch", options: {}, I: RecordMetricsBatchRequest, O: RecordMetricsBatchResponse }
]);
