export const HTTP_CONSTANTS = {
  DEFAULT_SERVICE_SUB: "web-app-service",
  DEFAULT_JWT_SECRET: "development-jwt-secret-key-32-bytes-min!!",
  JWT_ALG: "HS256",
  JWT_TYP: "JWT",
  HEADER_CONTENT_TYPE: "Content-Type",
  HEADER_ACCEPT: "Accept",
  HEADER_AUTHORIZATION: "Authorization",
  HEADER_TRACEPARENT: "traceparent",
  HEADER_X_TRACE_ID: "x-trace-id",
  HEADER_X_REQUEST_ID: "x-request-id",
  HEADER_X_CORRELATION_ID: "x-correlation-id",
  HEADER_X_IDEMPOTENCY_KEY: "x-idempotency-key",
  HEADER_X_TENANT_ID: "x-tenant-id",
  HEADER_TRACESTATE: "tracestate",
  HEADER_RETRY_AFTER: "Retry-After",
  HEADER_CACHE_CONTROL: "Cache-Control",
  CONTENT_TYPE_JSON: "application/json",
  BEARER_PREFIX: "Bearer ",
  DEFAULT_TENANT_ID: "tenant-default" as string,
  DEFAULT_TRACESTATE: "rojo=1",

  DEFAULT_SERVICE_REGISTRY_URL: "http://localhost:31426",
  SERVICE_NAME_LATENCY_ENGINE: "latency-engine",
  SERVICE_NAME_AUTH_SERVICE: "auth-service",
  SERVICE_NAME_WEB_APP: "web-app",
  SERVICE_NAME_CLICKHOUSE: "clickhouse",
  SERVICE_NAME_REDIS: "redis",
  SERVICE_NAME_KAFKA: "kafka",
  SERVICE_NAME_OTEL_COLLECTOR: "otel-collector",
  ENDPOINT_RESOLVE: "/v1/resolve",
  ENDPOINT_REGISTER: "/v1/register",
  ENDPOINT_HEARTBEAT: "/v1/heartbeat",
  ENDPOINT_DEREGISTER: "/v1/deregister",
  ENDPOINT_HEALTH: "/api/health",
  ENDPOINT_ROOT: "/",

  ENDPOINT_AUTH_SIGN_IN: "/auth/sign-in",
  ENDPOINT_AUTH_SIGN_UP: "/auth/sign-up",
  ENDPOINT_AUTH_CALLBACK: "/auth/callback",
  ENDPOINT_FAVICON: "/favicon.ico",
  PREFIX_NEXT: "/_next",
  PREFIX_API: "/api",
  PARAM_CALLBACK_URL: "callbackUrl",

  PARAM_SERVICE: "service",
  HOST_LOCALHOST: "localhost",
  PROTOCOL_HTTP: "http",
  PROTOCOL_TCP: "tcp",


  ENV_SERVICE_REGISTRY_URL: "SERVICE_REGISTRY_URL",
  ENV_SERVICE_REGISTRY_SECRET: "SERVICE_REGISTRY_SECRET",
  ENV_SERVICE_REGISTRY_TOKEN: "SERVICE_REGISTRY_TOKEN",
  ENV_SERVICE_NAME: "SERVICE_NAME",
  ENV_HOST: "HOST",
  ENV_PORT: "PORT",
  ENV_NEXT_RUNTIME: "NEXT_RUNTIME",
  RUNTIME_NODEJS: "nodejs",

  DEFAULT_RESOLVER_TTL_MS: 30000,
  DEFAULT_RESOLVER_TIMEOUT_MS: 2000,
  DEFAULT_HEARTBEAT_INTERVAL_MS: 5000,
  DEFAULT_PORT_WEB_APP: 31400,

  SIGNAL_SIGINT: "SIGINT",
  SIGNAL_SIGTERM: "SIGTERM",
  MSG_MISSING_INSTANCE_ID: "Registration response missing instance ID",

  TRACER_NAME: "http-client",
  ERROR_NAME_ABORT: "AbortError",
  MSG_PIPELINE_FAILED: "HTTP Request Pipeline Failed",

  CACHE_NO_CACHE: "no-cache",
  CACHE_NO_STORE: "no-store",

  METHOD_GET: "GET",
  METHOD_POST: "POST",
  METHOD_PATCH: "PATCH",
  METHOD_PUT: "PUT",
  METHOD_DELETE: "DELETE",

  CIRCUIT_CLOSED: "CLOSED",
  CIRCUIT_OPEN: "OPEN",
  CIRCUIT_HALF_OPEN: "HALF_OPEN",

  ATTR_HTTP_METHOD: "http.method",
  ATTR_HTTP_URL: "http.url",
  ATTR_HTTP_TARGET: "http.target",
  ATTR_HTTP_STATUS_CODE: "http.status_code",
  ATTR_HTTP_CACHE_HIT: "http.cache_hit",
  ATTR_HTTP_CIRCUIT_STATE: "http.circuit_state",
  ATTR_HTTP_RETRY_ATTEMPT: "http.retry_attempt",
  ATTR_HTTP_RETRY_BACKOFF_MS: "http.retry_backoff_ms",
  ATTR_TENANT_ID: "tenant.id",
  ATTR_IDEMPOTENCY_KEY: "http.idempotency_key",
  ATTR_REQUEST_CANCELLED: "http.request_cancelled",
  ATTR_REQUEST_ID: "request_id",
  ATTR_CORRELATION_ID: "correlation_id",
  DEFAULT_HTTP_SERVICE_NAME: "http-service",

  ATTR_EXECUTION_PATH: "execution.path",
  ATTR_RESULT_STATUS: "execution.status",
  ATTR_ERROR_DETAIL: "execution.error_detail",
  ATTR_CODE_FUNCTION: "code.function",
  ATTR_CODE_FILEPATH: "code.filepath",
  ATTR_CODE_LINENO: "code.lineno",

  PATH_POSITIVE: "positive_path",
  PATH_NEGATIVE: "negative_path",
  STATUS_SUCCESS: "success",
  STATUS_FAILURE: "failure",

  EVENT_SINGLEFLIGHT_HIT: "decision.singleflight_collapsed",
  EVENT_CACHE_EVALUATED: "decision.cache_evaluated",
  EVENT_CIRCUIT_EVALUATED: "decision.circuit_breaker_evaluated",
  EVENT_REQUEST_CANCELLED: "decision.request_cancelled",
  EVENT_RETRY_DECISION: "decision.retry_evaluated",
  EVENT_EXECUTION_SUCCESS: "execution.success",
  EVENT_EXECUTION_FAILURE: "execution.failure",

  EVENT_STEP_REQUEST_INTERCEPTORS: "step.request_interceptors_executed",
  EVENT_STEP_SINGLEFLIGHT_CHECK: "step.singleflight_check_completed",
  EVENT_STEP_HEADERS_RESOLVED: "step.header_providers_resolved",
  EVENT_STEP_FETCH_INITIATED: "step.fetch_attempt_initiated",
  EVENT_STEP_RESPONSE_INTERCEPTORS: "step.response_interceptors_executed",
  EVENT_STEP_ERROR_HANDLED: "step.error_interceptors_handled",

  KEY_CACHE_BYPASSED: "cache.bypassed",
  KEY_CACHE_HIT: "cache.hit",
  KEY_CACHE_KEY: "cache.key",
  KEY_CIRCUIT_STATE: "circuit.state",
  KEY_CIRCUIT_CAN_EXECUTE: "circuit.can_execute",
  KEY_CIRCUIT_FAILURES: "circuit.failures",
  KEY_CANCELLED_KEY: "request.cancelled_key",
  KEY_RETRY_ATTEMPT: "retry.attempt",
  KEY_RETRY_SHOULD_RETRY: "retry.should_retry",
  KEY_RETRY_ERROR_MSG: "retry.error_message",
  KEY_INTERCEPTORS_COUNT: "interceptors.count",
  KEY_HEADERS_COUNT: "headers.provider_count",

  ALLOWED_TELEMETRY_ATTRIBUTES: [
    "http.method",
    "http.url",
    "http.status_code",
    "http.cache_hit",
    "http.circuit_state",
    "http.retry_attempt",
    "http.retry_backoff_ms",
    "tenant.id",
    "http.idempotency_key",
    "http.request_cancelled",
    "execution.path",
    "execution.status",
    "execution.error_detail",
    "code.function",
    "code.filepath",
    "code.lineno",
    "cache.bypassed",
    "cache.hit",
    "cache.key",
    "circuit.state",
    "circuit.can_execute",
    "circuit.failures",
    "request.cancelled_key",
    "retry.attempt",
    "retry.should_retry",
    "retry.error_message",
    "interceptors.count",
    "headers.provider_count",
    "rule.id",
    "rule.name",
    "rule.conditions_passed",
    "rule.priority",
    "rule.async_passed",
    "rules.evaluated_count",
    "rules.triggered_count",
    "rules.triggered_ids",
    "rules.triggered_names"
  ]
} as const;
