<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm/observability/v1/instrumentation.proto

namespace LlmObservability\Platform\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>llm.observability.v1.DetectProviderRequest</code>
 */
class DetectProviderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string url = 1 [json_name = "url"];</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>string body = 2 [json_name = "body"];</code>
     */
    protected $body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *     @type string $body
     * }
     */
    public function __construct($data = NULL) {
        \Llm\Observability\V1\GPBMetadata\Instrumentation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string url = 1 [json_name = "url"];</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 1 [json_name = "url"];</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 2 [json_name = "body"];</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 2 [json_name = "body"];</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

}

