<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm/observability/v1/span.proto

namespace LlmObservability\Platform\V1;

use UnexpectedValueException;

/**
 * Environment Enum captures the deployment environment.
 *
 * Protobuf type <code>llm.observability.v1.Environment</code>
 */
class Environment
{
    /**
     * Generated from protobuf enum <code>ENVIRONMENT_UNSPECIFIED = 0;</code>
     */
    const ENVIRONMENT_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>ENVIRONMENT_PRODUCTION = 1;</code>
     */
    const ENVIRONMENT_PRODUCTION = 1;
    /**
     * Generated from protobuf enum <code>ENVIRONMENT_STAGING = 2;</code>
     */
    const ENVIRONMENT_STAGING = 2;
    /**
     * Generated from protobuf enum <code>ENVIRONMENT_DEV = 3;</code>
     */
    const ENVIRONMENT_DEV = 3;

    private static $valueToName = [
        self::ENVIRONMENT_UNSPECIFIED => 'ENVIRONMENT_UNSPECIFIED',
        self::ENVIRONMENT_PRODUCTION => 'ENVIRONMENT_PRODUCTION',
        self::ENVIRONMENT_STAGING => 'ENVIRONMENT_STAGING',
        self::ENVIRONMENT_DEV => 'ENVIRONMENT_DEV',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

