<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm/observability/v1/instrumentation.proto

namespace LlmObservability\Platform\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>llm.observability.v1.ModelPriceProto</code>
 */
class ModelPriceProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string model = 1 [json_name = "model"];</code>
     */
    protected $model = '';
    /**
     * Generated from protobuf field <code>string provider = 2 [json_name = "provider"];</code>
     */
    protected $provider = '';
    /**
     * Generated from protobuf field <code>double input_price_per_1m = 3 [json_name = "inputPricePer1m"];</code>
     */
    protected $input_price_per_1m = 0.0;
    /**
     * Generated from protobuf field <code>double output_price_per_1m = 4 [json_name = "outputPricePer1m"];</code>
     */
    protected $output_price_per_1m = 0.0;
    /**
     * Generated from protobuf field <code>string version = 5 [json_name = "version"];</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $model
     *     @type string $provider
     *     @type float $input_price_per_1m
     *     @type float $output_price_per_1m
     *     @type string $version
     * }
     */
    public function __construct($data = NULL) {
        \Llm\Observability\V1\GPBMetadata\Instrumentation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string model = 1 [json_name = "model"];</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>string model = 1 [json_name = "model"];</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string provider = 2 [json_name = "provider"];</code>
     * @return string
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * Generated from protobuf field <code>string provider = 2 [json_name = "provider"];</code>
     * @param string $var
     * @return $this
     */
    public function setProvider($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double input_price_per_1m = 3 [json_name = "inputPricePer1m"];</code>
     * @return float
     */
    public function getInputPricePer1M()
    {
        return $this->input_price_per_1m;
    }

    /**
     * Generated from protobuf field <code>double input_price_per_1m = 3 [json_name = "inputPricePer1m"];</code>
     * @param float $var
     * @return $this
     */
    public function setInputPricePer1M($var)
    {
        GPBUtil::checkDouble($var);
        $this->input_price_per_1m = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double output_price_per_1m = 4 [json_name = "outputPricePer1m"];</code>
     * @return float
     */
    public function getOutputPricePer1M()
    {
        return $this->output_price_per_1m;
    }

    /**
     * Generated from protobuf field <code>double output_price_per_1m = 4 [json_name = "outputPricePer1m"];</code>
     * @param float $var
     * @return $this
     */
    public function setOutputPricePer1M($var)
    {
        GPBUtil::checkDouble($var);
        $this->output_price_per_1m = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 5 [json_name = "version"];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 5 [json_name = "version"];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

