<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm/observability/v1/instrumentation.proto

namespace LlmObservability\Platform\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>llm.observability.v1.RecordMetricsBatchRequest</code>
 */
class RecordMetricsBatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .llm.observability.v1.RecordMetricsRequest spans = 1 [json_name = "spans"];</code>
     */
    private $spans;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\LlmObservability\Platform\V1\RecordMetricsRequest>|\Google\Protobuf\Internal\RepeatedField $spans
     * }
     */
    public function __construct($data = NULL) {
        \Llm\Observability\V1\GPBMetadata\Instrumentation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .llm.observability.v1.RecordMetricsRequest spans = 1 [json_name = "spans"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpans()
    {
        return $this->spans;
    }

    /**
     * Generated from protobuf field <code>repeated .llm.observability.v1.RecordMetricsRequest spans = 1 [json_name = "spans"];</code>
     * @param array<\LlmObservability\Platform\V1\RecordMetricsRequest>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpans($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LlmObservability\Platform\V1\RecordMetricsRequest::class);
        $this->spans = $arr;

        return $this;
    }

}

