<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm/observability/v1/instrumentation.proto

namespace LlmObservability\Platform\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>llm.observability.v1.RecordMetricsBatchResponse</code>
 */
class RecordMetricsBatchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 recorded_count = 1 [json_name = "recordedCount"];</code>
     */
    protected $recorded_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $recorded_count
     * }
     */
    public function __construct($data = NULL) {
        \Llm\Observability\V1\GPBMetadata\Instrumentation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 recorded_count = 1 [json_name = "recordedCount"];</code>
     * @return int
     */
    public function getRecordedCount()
    {
        return $this->recorded_count;
    }

    /**
     * Generated from protobuf field <code>int32 recorded_count = 1 [json_name = "recordedCount"];</code>
     * @param int $var
     * @return $this
     */
    public function setRecordedCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->recorded_count = $var;

        return $this;
    }

}

