<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm/observability/v1/span.proto

namespace LlmObservability\Platform\V1;

use UnexpectedValueException;

/**
 * TokenCountMethod captures how the token counts were determined.
 *
 * Protobuf type <code>llm.observability.v1.TokenCountMethod</code>
 */
class TokenCountMethod
{
    /**
     * Generated from protobuf enum <code>TOKEN_COUNT_METHOD_UNSPECIFIED = 0;</code>
     */
    const TOKEN_COUNT_METHOD_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>TOKEN_COUNT_METHOD_TIKTOKEN = 1;</code>
     */
    const TOKEN_COUNT_METHOD_TIKTOKEN = 1;
    /**
     * Generated from protobuf enum <code>TOKEN_COUNT_METHOD_ESTIMATED = 2;</code>
     */
    const TOKEN_COUNT_METHOD_ESTIMATED = 2;

    private static $valueToName = [
        self::TOKEN_COUNT_METHOD_UNSPECIFIED => 'TOKEN_COUNT_METHOD_UNSPECIFIED',
        self::TOKEN_COUNT_METHOD_TIKTOKEN => 'TOKEN_COUNT_METHOD_TIKTOKEN',
        self::TOKEN_COUNT_METHOD_ESTIMATED => 'TOKEN_COUNT_METHOD_ESTIMATED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

