from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
MODELS_DIR = PROJECT_ROOT / "configs" / "models"
OUTPUT_SQL = Path(__file__).resolve().parent / "seed_model_catalog.postgres.sql"
OUTPUT_MONGO = Path(__file__).resolve().parent / "seed_model_catalog.mongo.js"

from services.shared.cloudflare_catalog import build_cloudflare_virtual_records


def load_records() -> List[Dict]:
    records: List[Dict] = []
    for yaml_path in sorted(MODELS_DIR.rglob("*.yaml")):
        with open(yaml_path, "r") as f:
            config = yaml.safe_load(f) or {}
        model = config.get("model", {}) if isinstance(config, dict) else {}
        key = str(yaml_path.relative_to(PROJECT_ROOT))
        provider = model.get("provider")
        model_id = model.get("id")
        if not provider or not model_id:
            continue
        records.append(
            {
                "key": key,
                "provider": provider,
                "id": model_id,
                "name": model.get("name"),
                "source": "filesystem",
                "config": config,
            }
        )
    records.extend(build_cloudflare_virtual_records())
    return dedupe(records)


def dedupe(records: List[Dict]) -> List[Dict]:
    seen: set[Tuple[str, str]] = set()
    deduped: List[Dict] = []
    for record in records:
        identity = (str(record.get("provider") or ""), str(record.get("id") or ""))
        if identity in seen:
            continue
        seen.add(identity)
        deduped.append(record)
    return deduped


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def build_sql(records: List[Dict]) -> str:
    lines = [
        "-- Auto-generated by scripts/db/generate_model_seed_files.py",
        "CREATE TABLE IF NOT EXISTS model_catalog (",
        "  key TEXT PRIMARY KEY,",
        "  provider TEXT NOT NULL,",
        "  model_id TEXT NOT NULL,",
        "  name TEXT,",
        "  source TEXT NOT NULL DEFAULT 'filesystem',",
        "  config_json JSONB NOT NULL",
        ");",
        "",
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_model_catalog_provider_model_id ON model_catalog(provider, model_id);",
        "",
        "INSERT INTO model_catalog (key, provider, model_id, name, source, config_json)",
        "VALUES",
    ]

    value_lines = []
    for record in records:
        config_json = json.dumps(record["config"], separators=(",", ":"))
        value_lines.append(
            "  ('{key}','{provider}','{model_id}','{name}','{source}','{config_json}'::jsonb)".format(
                key=sql_escape(str(record["key"])),
                provider=sql_escape(str(record.get("provider") or "")),
                model_id=sql_escape(str(record.get("id") or "")),
                name=sql_escape(str(record.get("name") or "")),
                source=sql_escape(str(record.get("source") or "filesystem")),
                config_json=sql_escape(config_json),
            )
        )

    lines.append(",\n".join(value_lines))
    lines.append("ON CONFLICT (key) DO UPDATE SET")
    lines.append("  provider = EXCLUDED.provider,")
    lines.append("  model_id = EXCLUDED.model_id,")
    lines.append("  name = EXCLUDED.name,")
    lines.append("  source = EXCLUDED.source,")
    lines.append("  config_json = EXCLUDED.config_json;")
    lines.append("")

    return "\n".join(lines)


def build_mongo(records: List[Dict]) -> str:
    docs = json.dumps(records, indent=2)
    return f"""// Auto-generated by scripts/db/generate_model_seed_files.py
const docs = {docs};

db.model_configs.createIndex({{ key: 1 }}, {{ unique: true }});
db.model_configs.createIndex({{ provider: 1, id: 1 }}, {{ unique: true }});

docs.forEach((doc) => {{
  db.model_configs.updateOne(
    {{ key: doc.key }},
    {{ $set: doc }},
    {{ upsert: true }}
  );
}});
"""


def main() -> None:
    records = load_records()
    OUTPUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_SQL.write_text(build_sql(records))
    OUTPUT_MONGO.write_text(build_mongo(records))
    print(f"Generated {len(records)} deduplicated model records")
    print(f"- {OUTPUT_SQL}")
    print(f"- {OUTPUT_MONGO}")


if __name__ == "__main__":
    main()
