// Auto-generated by scripts/db/generate_model_seed_files.py
const docs = [
  {
    "key": "configs/models/local/deepseek/v1/cpu/1.5b.yaml",
    "provider": "local",
    "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
    "name": "Deepseek v1 1.5B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
        "name": "Deepseek v1 1.5B (CPU)",
        "version": "v1",
        "size": "1.5b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 6,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/deepseek/v1/cpu/14b.yaml",
    "provider": "local",
    "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    "name": "Deepseek v1 14B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
        "name": "Deepseek v1 14B (CPU)",
        "version": "v1",
        "size": "14b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 48,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/deepseek/v1/cpu/32b.yaml",
    "provider": "local",
    "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    "name": "Deepseek v1 32B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
        "name": "Deepseek v1 32B (CPU)",
        "version": "v1",
        "size": "32b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 96,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/deepseek/v1/cpu/7b.yaml",
    "provider": "local",
    "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
    "name": "Deepseek v1 7B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        "name": "Deepseek v1 7B (CPU)",
        "version": "v1",
        "size": "7b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 24,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/gemma/v2/cpu/27b.yaml",
    "provider": "local",
    "id": "google/gemma-2-27b-it",
    "name": "Gemma v2 27B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "google/gemma-2-27b-it",
        "name": "Gemma v2 27B (CPU)",
        "version": "v2",
        "size": "27b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 90,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/gemma/v2/cpu/2b-cpu-only.yaml",
    "provider": "local",
    "id": "google/gemma-2-2b-it",
    "name": "Gemma v2 2B (CPU Optimized)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "google/gemma-2-2b-it",
        "name": "Gemma v2 2B (CPU Optimized)",
        "version": "v2",
        "size": "2b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.9,
          "max_tokens": 128
        },
        "resources": {
          "min_ram_gb": 6,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/gemma/v2/cpu/9b.yaml",
    "provider": "local",
    "id": "google/gemma-2-9b-it",
    "name": "Gemma v2 9B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "google/gemma-2-9b-it",
        "name": "Gemma v2 9B (CPU)",
        "version": "v2",
        "size": "9b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 30,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/glm/v4/cpu/9b.yaml",
    "provider": "local",
    "id": "THUDM/glm-4-9b-chat",
    "name": "Glm v4 9B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "THUDM/glm-4-9b-chat",
        "name": "Glm v4 9B (CPU)",
        "version": "v4",
        "size": "9b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 36,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/llama/v3.1/cpu/70b.yaml",
    "provider": "local",
    "id": "meta-llama/Llama-3.1-70B-Instruct",
    "name": "Llama v3.1 70B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "meta-llama/Llama-3.1-70B-Instruct",
        "name": "Llama v3.1 70B (CPU)",
        "version": "v3.1",
        "size": "70b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 210,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/llama/v3.1/cpu/8b-it.yaml",
    "provider": "local",
    "id": "meta-llama/Llama-3.1-8B-Instruct",
    "name": "Llama 3.1 8B Instruct (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "meta-llama/Llama-3.1-8B-Instruct",
        "name": "Llama 3.1 8B Instruct (CPU)",
        "version": "3.1",
        "size": "8b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 24,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/llama/v3.2/cpu/1b.yaml",
    "provider": "local",
    "id": "meta-llama/Llama-3.2-1B-Instruct",
    "name": "Llama v3.2 1B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "meta-llama/Llama-3.2-1B-Instruct",
        "name": "Llama v3.2 1B (CPU)",
        "version": "v3.2",
        "size": "1b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 6,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/llama/v3.2/cpu/3b.yaml",
    "provider": "local",
    "id": "meta-llama/Llama-3.2-3B-Instruct",
    "name": "Llama v3.2 3B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "meta-llama/Llama-3.2-3B-Instruct",
        "name": "Llama v3.2 3B (CPU)",
        "version": "v3.2",
        "size": "3b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 12,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/mistral/mixtral/cpu/8x22b.yaml",
    "provider": "local",
    "id": "mistralai/Mixtral-8x22B-Instruct-v0.1",
    "name": "Mistral mixtral 8X22B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "mistralai/Mixtral-8x22B-Instruct-v0.1",
        "name": "Mistral mixtral 8X22B (CPU)",
        "version": "mixtral",
        "size": "8x22b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 420,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/mistral/mixtral/cpu/8x7b.yaml",
    "provider": "local",
    "id": "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "name": "Mistral mixtral 8X7B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "mistralai/Mixtral-8x7B-Instruct-v0.1",
        "name": "Mistral mixtral 8X7B (CPU)",
        "version": "mixtral",
        "size": "8x7b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 144,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/mistral/v0.3/cpu/7b.yaml",
    "provider": "local",
    "id": "mistralai/Mistral-7B-Instruct-v0.3",
    "name": "Mistral v0.3 7B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "mistralai/Mistral-7B-Instruct-v0.3",
        "name": "Mistral v0.3 7B (CPU)",
        "version": "v0.3",
        "size": "7b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 24,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/phi/v3/cpu/14b.yaml",
    "provider": "local",
    "id": "microsoft/Phi-3-medium-4k-instruct",
    "name": "Phi v3 14B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "microsoft/Phi-3-medium-4k-instruct",
        "name": "Phi v3 14B (CPU)",
        "version": "v3",
        "size": "14b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 48,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/phi/v3/cpu/3b.yaml",
    "provider": "local",
    "id": "microsoft/Phi-3-mini-4k-instruct",
    "name": "Phi v3 3B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "microsoft/Phi-3-mini-4k-instruct",
        "name": "Phi v3 3B (CPU)",
        "version": "v3",
        "size": "3b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 12,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/phi/v4/cpu/14b.yaml",
    "provider": "local",
    "id": "microsoft/phi-4",
    "name": "Phi v4 14B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "microsoft/phi-4",
        "name": "Phi v4 14B (CPU)",
        "version": "v4",
        "size": "14b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 48,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/qwen/v2.5/cpu/0.5b.yaml",
    "provider": "local",
    "id": "Qwen/Qwen2.5-0.5B-Instruct",
    "name": "Qwen v2.5 0.5B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "Qwen/Qwen2.5-0.5B-Instruct",
        "name": "Qwen v2.5 0.5B (CPU)",
        "version": "v2.5",
        "size": "0.5b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 3,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/qwen/v2.5/cpu/1.5b.yaml",
    "provider": "local",
    "id": "Qwen/Qwen2.5-1.5B-Instruct",
    "name": "Qwen v2.5 1.5B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "Qwen/Qwen2.5-1.5B-Instruct",
        "name": "Qwen v2.5 1.5B (CPU)",
        "version": "v2.5",
        "size": "1.5b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 6,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/qwen/v2.5/cpu/14b.yaml",
    "provider": "local",
    "id": "Qwen/Qwen2.5-14B-Instruct",
    "name": "Qwen v2.5 14B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "Qwen/Qwen2.5-14B-Instruct",
        "name": "Qwen v2.5 14B (CPU)",
        "version": "v2.5",
        "size": "14b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 48,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/qwen/v2.5/cpu/32b.yaml",
    "provider": "local",
    "id": "Qwen/Qwen2.5-32B-Instruct",
    "name": "Qwen v2.5 32B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "Qwen/Qwen2.5-32B-Instruct",
        "name": "Qwen v2.5 32B (CPU)",
        "version": "v2.5",
        "size": "32b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 96,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/qwen/v2.5/cpu/72b.yaml",
    "provider": "local",
    "id": "Qwen/Qwen2.5-72B-Instruct",
    "name": "Qwen v2.5 72B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "Qwen/Qwen2.5-72B-Instruct",
        "name": "Qwen v2.5 72B (CPU)",
        "version": "v2.5",
        "size": "72b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 216,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/qwen/v2.5/cpu/7b.yaml",
    "provider": "local",
    "id": "Qwen/Qwen2.5-7B-Instruct",
    "name": "Qwen v2.5 7B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "Qwen/Qwen2.5-7B-Instruct",
        "name": "Qwen v2.5 7B (CPU)",
        "version": "v2.5",
        "size": "7b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 24,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/yi/v1.5/cpu/34b.yaml",
    "provider": "local",
    "id": "01-ai/Yi-1.5-34B-Chat",
    "name": "Yi v1.5 34B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "01-ai/Yi-1.5-34B-Chat",
        "name": "Yi v1.5 34B (CPU)",
        "version": "v1.5",
        "size": "34b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 120,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/yi/v1.5/cpu/6b.yaml",
    "provider": "local",
    "id": "01-ai/Yi-1.5-6B-Chat",
    "name": "Yi v1.5 6B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "01-ai/Yi-1.5-6B-Chat",
        "name": "Yi v1.5 6B (CPU)",
        "version": "v1.5",
        "size": "6b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 21,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "configs/models/local/yi/v1.5/cpu/9b.yaml",
    "provider": "local",
    "id": "01-ai/Yi-1.5-9B-Chat",
    "name": "Yi v1.5 9B (CPU)",
    "source": "filesystem",
    "config": {
      "model": {
        "id": "01-ai/Yi-1.5-9B-Chat",
        "name": "Yi v1.5 9B (CPU)",
        "version": "v1.5",
        "size": "9b",
        "provider": "local",
        "backend": "transformers",
        "parameters": {
          "temperature": 0.7,
          "top_p": 0.95,
          "max_tokens": 4096
        },
        "resources": {
          "min_ram_gb": 36,
          "accelerator": "cpu"
        },
        "quantization": "none",
        "device_map": "cpu",
        "trust_remote_code": true
      }
    }
  },
  {
    "key": "catalog/cloudflare/aisingapore/gemma-sea-lion-v4-27b-it",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
    "name": "Cloudflare Workers AI - SEA-LION v4 27B IT",
    "config": {
      "model": {
        "id": "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
        "name": "Cloudflare Workers AI - SEA-LION v4 27B IT",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/deepseek/deepseek-r1-distill-qwen-32b",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/deepseek/deepseek-r1-distill-qwen-32b",
    "name": "Cloudflare Workers AI - DeepSeek R1 Distill Qwen 32B",
    "config": {
      "model": {
        "id": "@cf/deepseek/deepseek-r1-distill-qwen-32b",
        "name": "Cloudflare Workers AI - DeepSeek R1 Distill Qwen 32B",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/google/gemma-3-12b-it",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/google/gemma-3-12b-it",
    "name": "Cloudflare Workers AI - Google Gemma 3 12B IT",
    "config": {
      "model": {
        "id": "@cf/google/gemma-3-12b-it",
        "name": "Cloudflare Workers AI - Google Gemma 3 12B IT",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/google/gemma-4-26b-a4b-it",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/google/gemma-4-26b-a4b-it",
    "name": "Cloudflare Workers AI - Google Gemma 4 26B A4B IT",
    "config": {
      "model": {
        "id": "@cf/google/gemma-4-26b-a4b-it",
        "name": "Cloudflare Workers AI - Google Gemma 4 26B A4B IT",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/ibm/granite-4.0-h-micro",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/ibm/granite-4.0-h-micro",
    "name": "Cloudflare Workers AI - IBM Granite 4.0 H Micro",
    "config": {
      "model": {
        "id": "@cf/ibm/granite-4.0-h-micro",
        "name": "Cloudflare Workers AI - IBM Granite 4.0 H Micro",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-3.1-70b-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-3.1-70b-instruct",
    "name": "Cloudflare Workers AI - Meta Llama 3.1 70B Instruct",
    "config": {
      "model": {
        "id": "@cf/meta/llama-3.1-70b-instruct",
        "name": "Cloudflare Workers AI - Meta Llama 3.1 70B Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-3.1-8b-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-3.1-8b-instruct",
    "name": "Cloudflare Workers AI - Meta Llama 3.1 8B Instruct",
    "config": {
      "model": {
        "id": "@cf/meta/llama-3.1-8b-instruct",
        "name": "Cloudflare Workers AI - Meta Llama 3.1 8B Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-3.1-8b-instruct-fp8",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-3.1-8b-instruct-fp8",
    "name": "Cloudflare Workers AI - Meta Llama 3.1 8B Instruct FP8",
    "config": {
      "model": {
        "id": "@cf/meta/llama-3.1-8b-instruct-fp8",
        "name": "Cloudflare Workers AI - Meta Llama 3.1 8B Instruct FP8",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-3.2-11b-vision-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-3.2-11b-vision-instruct",
    "name": "Cloudflare Workers AI - Meta Llama 3.2 11B Vision Instruct",
    "config": {
      "model": {
        "id": "@cf/meta/llama-3.2-11b-vision-instruct",
        "name": "Cloudflare Workers AI - Meta Llama 3.2 11B Vision Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-3.2-1b-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-3.2-1b-instruct",
    "name": "Cloudflare Workers AI - Meta Llama 3.2 1B Instruct",
    "config": {
      "model": {
        "id": "@cf/meta/llama-3.2-1b-instruct",
        "name": "Cloudflare Workers AI - Meta Llama 3.2 1B Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-3.2-3b-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-3.2-3b-instruct",
    "name": "Cloudflare Workers AI - Meta Llama 3.2 3B Instruct",
    "config": {
      "model": {
        "id": "@cf/meta/llama-3.2-3b-instruct",
        "name": "Cloudflare Workers AI - Meta Llama 3.2 3B Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-3.3-70b-instruct-fp8-fast",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    "name": "Cloudflare Workers AI - Meta Llama 3.3 70B Instruct FP8 Fast",
    "config": {
      "model": {
        "id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        "name": "Cloudflare Workers AI - Meta Llama 3.3 70B Instruct FP8 Fast",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-4-scout-17b-16e-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-4-scout-17b-16e-instruct",
    "name": "Cloudflare Workers AI - Meta Llama 4 Scout 17B 16E Instruct",
    "config": {
      "model": {
        "id": "@cf/meta/llama-4-scout-17b-16e-instruct",
        "name": "Cloudflare Workers AI - Meta Llama 4 Scout 17B 16E Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/llama-guard-3-8b",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/llama-guard-3-8b",
    "name": "Cloudflare Workers AI - Meta Llama Guard 3 8B",
    "config": {
      "model": {
        "id": "@cf/meta/llama-guard-3-8b",
        "name": "Cloudflare Workers AI - Meta Llama Guard 3 8B",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/meta/meta-llama-3-8b-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/meta/meta-llama-3-8b-instruct",
    "name": "Cloudflare Workers AI - Meta Llama 3 8B Instruct",
    "config": {
      "model": {
        "id": "@cf/meta/meta-llama-3-8b-instruct",
        "name": "Cloudflare Workers AI - Meta Llama 3 8B Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/mistralai/mistral-small-3.1-24b-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/mistralai/mistral-small-3.1-24b-instruct",
    "name": "Cloudflare Workers AI - Mistral Small 3.1 24B Instruct",
    "config": {
      "model": {
        "id": "@cf/mistralai/mistral-small-3.1-24b-instruct",
        "name": "Cloudflare Workers AI - Mistral Small 3.1 24B Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/moonshot-ai/kimi-k2.5",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/moonshot-ai/kimi-k2.5",
    "name": "Cloudflare Workers AI - Moonshot AI Kimi K2.5",
    "config": {
      "model": {
        "id": "@cf/moonshot-ai/kimi-k2.5",
        "name": "Cloudflare Workers AI - Moonshot AI Kimi K2.5",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/moonshot-ai/kimi-k2.6",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/moonshot-ai/kimi-k2.6",
    "name": "Cloudflare Workers AI - Moonshot AI Kimi K2.6",
    "config": {
      "model": {
        "id": "@cf/moonshot-ai/kimi-k2.6",
        "name": "Cloudflare Workers AI - Moonshot AI Kimi K2.6",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/nvidia/nemotron-3-120b-a12b",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/nvidia/nemotron-3-120b-a12b",
    "name": "Cloudflare Workers AI - NVIDIA Nemotron 3 120B A12B",
    "config": {
      "model": {
        "id": "@cf/nvidia/nemotron-3-120b-a12b",
        "name": "Cloudflare Workers AI - NVIDIA Nemotron 3 120B A12B",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/openai/gpt-oss-120b",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/openai/gpt-oss-120b",
    "name": "Cloudflare Workers AI - OpenAI gpt-oss-120b",
    "config": {
      "model": {
        "id": "@cf/openai/gpt-oss-120b",
        "name": "Cloudflare Workers AI - OpenAI gpt-oss-120b",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/openai/gpt-oss-20b",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/openai/gpt-oss-20b",
    "name": "Cloudflare Workers AI - OpenAI gpt-oss-20b",
    "config": {
      "model": {
        "id": "@cf/openai/gpt-oss-20b",
        "name": "Cloudflare Workers AI - OpenAI gpt-oss-20b",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/qwen/qwen2.5-coder-32b-instruct",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/qwen/qwen2.5-coder-32b-instruct",
    "name": "Cloudflare Workers AI - Qwen2.5 Coder 32B Instruct",
    "config": {
      "model": {
        "id": "@cf/qwen/qwen2.5-coder-32b-instruct",
        "name": "Cloudflare Workers AI - Qwen2.5 Coder 32B Instruct",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/qwen/qwen3-30b-a3b-fp8",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/qwen/qwen3-30b-a3b-fp8",
    "name": "Cloudflare Workers AI - Qwen3 30B A3B FP8",
    "config": {
      "model": {
        "id": "@cf/qwen/qwen3-30b-a3b-fp8",
        "name": "Cloudflare Workers AI - Qwen3 30B A3B FP8",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/qwen/qwq-32b",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/qwen/qwq-32b",
    "name": "Cloudflare Workers AI - Qwen QwQ 32B",
    "config": {
      "model": {
        "id": "@cf/qwen/qwq-32b",
        "name": "Cloudflare Workers AI - Qwen QwQ 32B",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  },
  {
    "key": "catalog/cloudflare/zhipu-ai/glm-4.7-flash",
    "source": "cloudflare_catalog",
    "provider": "cloudflare",
    "id": "@cf/zhipu-ai/glm-4.7-flash",
    "name": "Cloudflare Workers AI - Zhipu AI GLM 4.7 Flash",
    "config": {
      "model": {
        "id": "@cf/zhipu-ai/glm-4.7-flash",
        "name": "Cloudflare Workers AI - Zhipu AI GLM 4.7 Flash",
        "provider": "cloudflare",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 1024
        }
      }
    }
  }
];

db.model_configs.createIndex({ key: 1 }, { unique: true });
db.model_configs.createIndex({ provider: 1, id: 1 }, { unique: true });

docs.forEach((doc) => {
  db.model_configs.updateOne(
    { key: doc.key },
    { $set: doc },
    { upsert: true }
  );
});
