// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializeclearFallbackTrackerResponse")
public inline fun clearFallbackTrackerResponse(block: com.llmobservability.platform.v1.ClearFallbackTrackerResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.ClearFallbackTrackerResponse =
  com.llmobservability.platform.v1.ClearFallbackTrackerResponseKt.Dsl._create(com.llmobservability.platform.v1.ClearFallbackTrackerResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.ClearFallbackTrackerResponse`
 */
public object ClearFallbackTrackerResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.ClearFallbackTrackerResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.ClearFallbackTrackerResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.ClearFallbackTrackerResponse = _builder.build()

    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.ClearFallbackTrackerResponse.copy(block: `com.llmobservability.platform.v1`.ClearFallbackTrackerResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.ClearFallbackTrackerResponse =
  `com.llmobservability.platform.v1`.ClearFallbackTrackerResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

