// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializedisableInstrumentationResponse")
public inline fun disableInstrumentationResponse(block: com.llmobservability.platform.v1.DisableInstrumentationResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.DisableInstrumentationResponse =
  com.llmobservability.platform.v1.DisableInstrumentationResponseKt.Dsl._create(com.llmobservability.platform.v1.DisableInstrumentationResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.DisableInstrumentationResponse`
 */
public object DisableInstrumentationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.DisableInstrumentationResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.DisableInstrumentationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.DisableInstrumentationResponse = _builder.build()

    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `string message = 2 [json_name = "message"];`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 2 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `.llm.observability.v1.InstrumentationStatus status = 3 [json_name = "status"];`
     */
    public var status: com.llmobservability.platform.v1.InstrumentationStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.llm.observability.v1.InstrumentationStatus status = 3 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.DisableInstrumentationResponse.copy(block: `com.llmobservability.platform.v1`.DisableInstrumentationResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.DisableInstrumentationResponse =
  `com.llmobservability.platform.v1`.DisableInstrumentationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

