// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializegetMetricsHealthRequest")
public inline fun getMetricsHealthRequest(block: com.llmobservability.platform.v1.GetMetricsHealthRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.GetMetricsHealthRequest =
  com.llmobservability.platform.v1.GetMetricsHealthRequestKt.Dsl._create(com.llmobservability.platform.v1.GetMetricsHealthRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.GetMetricsHealthRequest`
 */
public object GetMetricsHealthRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.GetMetricsHealthRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.GetMetricsHealthRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.GetMetricsHealthRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.GetMetricsHealthRequest.copy(block: `com.llmobservability.platform.v1`.GetMetricsHealthRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.GetMetricsHealthRequest =
  `com.llmobservability.platform.v1`.GetMetricsHealthRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

