// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializegetMetricsHealthResponse")
public inline fun getMetricsHealthResponse(block: com.llmobservability.platform.v1.GetMetricsHealthResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.GetMetricsHealthResponse =
  com.llmobservability.platform.v1.GetMetricsHealthResponseKt.Dsl._create(com.llmobservability.platform.v1.GetMetricsHealthResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.GetMetricsHealthResponse`
 */
public object GetMetricsHealthResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.GetMetricsHealthResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.GetMetricsHealthResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.GetMetricsHealthResponse = _builder.build()

    /**
     * `bool initialized = 1 [json_name = "initialized"];`
     */
    public var initialized: kotlin.Boolean
      @JvmName("getInitialized")
      get() = _builder.getInitialized()
      @JvmName("setInitialized")
      set(value) {
        _builder.setInitialized(value)
      }
    /**
     * `bool initialized = 1 [json_name = "initialized"];`
     */
    public fun clearInitialized() {
      _builder.clearInitialized()
    }

    /**
     * `string message = 2 [json_name = "message"];`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 2 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.GetMetricsHealthResponse.copy(block: `com.llmobservability.platform.v1`.GetMetricsHealthResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.GetMetricsHealthResponse =
  `com.llmobservability.platform.v1`.GetMetricsHealthResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

