// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializeinitInstrumentationRequest")
public inline fun initInstrumentationRequest(block: com.llmobservability.platform.v1.InitInstrumentationRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.InitInstrumentationRequest =
  com.llmobservability.platform.v1.InitInstrumentationRequestKt.Dsl._create(com.llmobservability.platform.v1.InitInstrumentationRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.InitInstrumentationRequest`
 */
public object InitInstrumentationRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.InitInstrumentationRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.InitInstrumentationRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.InitInstrumentationRequest = _builder.build()

    /**
     * `string service_name = 1 [json_name = "serviceName"];`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 1 [json_name = "serviceName"];`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `string environment = 2 [json_name = "environment"];`
     */
    public var environment: kotlin.String
      @JvmName("getEnvironment")
      get() = _builder.getEnvironment()
      @JvmName("setEnvironment")
      set(value) {
        _builder.setEnvironment(value)
      }
    /**
     * `string environment = 2 [json_name = "environment"];`
     */
    public fun clearEnvironment() {
      _builder.clearEnvironment()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.InitInstrumentationRequest.copy(block: `com.llmobservability.platform.v1`.InitInstrumentationRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.InitInstrumentationRequest =
  `com.llmobservability.platform.v1`.InitInstrumentationRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

