// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializeinstrumentationEvent")
public inline fun instrumentationEvent(block: com.llmobservability.platform.v1.InstrumentationEventKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.InstrumentationEvent =
  com.llmobservability.platform.v1.InstrumentationEventKt.Dsl._create(com.llmobservability.platform.v1.InstrumentationEvent.newBuilder()).apply { block() }._build()
/**
 * ```
 * Event for publishing instrumentation state changes to Kafka
 * ```
 *
 * Protobuf type `llm.observability.v1.InstrumentationEvent`
 */
public object InstrumentationEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.InstrumentationEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.InstrumentationEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.InstrumentationEvent = _builder.build()

    /**
     * `string event_id = 1 [json_name = "eventId"];`
     */
    public var eventId: kotlin.String
      @JvmName("getEventId")
      get() = _builder.getEventId()
      @JvmName("setEventId")
      set(value) {
        _builder.setEventId(value)
      }
    /**
     * `string event_id = 1 [json_name = "eventId"];`
     */
    public fun clearEventId() {
      _builder.clearEventId()
    }

    /**
     * `string timestamp_utc = 2 [json_name = "timestampUtc"];`
     */
    public var timestampUtc: kotlin.String
      @JvmName("getTimestampUtc")
      get() = _builder.getTimestampUtc()
      @JvmName("setTimestampUtc")
      set(value) {
        _builder.setTimestampUtc(value)
      }
    /**
     * `string timestamp_utc = 2 [json_name = "timestampUtc"];`
     */
    public fun clearTimestampUtc() {
      _builder.clearTimestampUtc()
    }

    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `.llm.observability.v1.InstrumentationStatus action = 4 [json_name = "action"];`
     */
    public var action: com.llmobservability.platform.v1.InstrumentationStatus
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    public var actionValue: kotlin.Int
      @JvmName("getActionValue")
      get() = _builder.getActionValue()
      @JvmName("setActionValue")
      set(value) {
        _builder.setActionValue(value)
      }
    /**
     * `.llm.observability.v1.InstrumentationStatus action = 4 [json_name = "action"];`
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * ```
     * JSON blob for extra details
     * ```
     *
     * `string metadata = 5 [json_name = "metadata"];`
     */
    public var metadata: kotlin.String
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * ```
     * JSON blob for extra details
     * ```
     *
     * `string metadata = 5 [json_name = "metadata"];`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.InstrumentationEvent.copy(block: `com.llmobservability.platform.v1`.InstrumentationEventKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.InstrumentationEvent =
  `com.llmobservability.platform.v1`.InstrumentationEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

