// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/span.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializelLMSpan")
public inline fun lLMSpan(block: com.llmobservability.platform.v1.LLMSpanKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.LLMSpan =
  com.llmobservability.platform.v1.LLMSpanKt.Dsl._create(com.llmobservability.platform.v1.LLMSpan.newBuilder()).apply { block() }._build()
/**
 * ```
 * LLMSpan represents a single, raw observability span for an LLM call.
 * ```
 *
 * Protobuf type `llm.observability.v1.LLMSpan`
 */
public object LLMSpanKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.LLMSpan.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.LLMSpan.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.LLMSpan = _builder.build()

    /**
     * ```
     * Generated before API call (UUID v4)
     * ```
     *
     * `string span_id = 1 [json_name = "spanId"];`
     */
    public var spanId: kotlin.String
      @JvmName("getSpanId")
      get() = _builder.getSpanId()
      @JvmName("setSpanId")
      set(value) {
        _builder.setSpanId(value)
      }
    /**
     * ```
     * Generated before API call (UUID v4)
     * ```
     *
     * `string span_id = 1 [json_name = "spanId"];`
     */
    public fun clearSpanId() {
      _builder.clearSpanId()
    }

    /**
     * ```
     * Propagated from caller (UUID v4), nullable
     * ```
     *
     * `optional string trace_id = 2 [json_name = "traceId"];`
     */
    public var traceId: kotlin.String
      @JvmName("getTraceId")
      get() = _builder.getTraceId()
      @JvmName("setTraceId")
      set(value) {
        _builder.setTraceId(value)
      }
    /**
     * ```
     * Propagated from caller (UUID v4), nullable
     * ```
     *
     * `optional string trace_id = 2 [json_name = "traceId"];`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
    /**
     * ```
     * Propagated from caller (UUID v4), nullable
     * ```
     *
     * `optional string trace_id = 2 [json_name = "traceId"];`
     * @return Whether the traceId field is set.
     */
    public fun hasTraceId(): kotlin.Boolean {
      return _builder.hasTraceId()
    }

    /**
     * ```
     * For tool-call chains (UUID v4), nullable
     * ```
     *
     * `optional string parent_span_id = 3 [json_name = "parentSpanId"];`
     */
    public var parentSpanId: kotlin.String
      @JvmName("getParentSpanId")
      get() = _builder.getParentSpanId()
      @JvmName("setParentSpanId")
      set(value) {
        _builder.setParentSpanId(value)
      }
    /**
     * ```
     * For tool-call chains (UUID v4), nullable
     * ```
     *
     * `optional string parent_span_id = 3 [json_name = "parentSpanId"];`
     */
    public fun clearParentSpanId() {
      _builder.clearParentSpanId()
    }
    /**
     * ```
     * For tool-call chains (UUID v4), nullable
     * ```
     *
     * `optional string parent_span_id = 3 [json_name = "parentSpanId"];`
     * @return Whether the parentSpanId field is set.
     */
    public fun hasParentSpanId(): kotlin.Boolean {
      return _builder.hasParentSpanId()
    }

    /**
     * ```
     * Bump on breaking change. Hardcoded = 1
     * ```
     *
     * `int32 schema_version = 4 [json_name = "schemaVersion"];`
     */
    public var schemaVersion: kotlin.Int
      @JvmName("getSchemaVersion")
      get() = _builder.getSchemaVersion()
      @JvmName("setSchemaVersion")
      set(value) {
        _builder.setSchemaVersion(value)
      }
    /**
     * ```
     * Bump on breaking change. Hardcoded = 1
     * ```
     *
     * `int32 schema_version = 4 [json_name = "schemaVersion"];`
     */
    public fun clearSchemaVersion() {
      _builder.clearSchemaVersion()
    }

    /**
     * ```
     * SDK config ('gpt-4o', etc)
     * ```
     *
     * `string model = 5 [json_name = "model"];`
     */
    public var model: kotlin.String
      @JvmName("getModel")
      get() = _builder.getModel()
      @JvmName("setModel")
      set(value) {
        _builder.setModel(value)
      }
    /**
     * ```
     * SDK config ('gpt-4o', etc)
     * ```
     *
     * `string model = 5 [json_name = "model"];`
     */
    public fun clearModel() {
      _builder.clearModel()
    }

    /**
     * ```
     * SDK config ('openai', 'anthropic', etc)
     * ```
     *
     * `string provider = 6 [json_name = "provider"];`
     */
    public var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * ```
     * SDK config ('openai', 'anthropic', etc)
     * ```
     *
     * `string provider = 6 [json_name = "provider"];`
     */
    public fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * ```
     * SDK config ('checkout-service')
     * ```
     *
     * `string service_name = 7 [json_name = "serviceName"];`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * ```
     * SDK config ('checkout-service')
     * ```
     *
     * `string service_name = 7 [json_name = "serviceName"];`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * ```
     * SDK decorator arg ('/api/summarize')
     * ```
     *
     * `string endpoint = 8 [json_name = "endpoint"];`
     */
    public var endpoint: kotlin.String
      @JvmName("getEndpoint")
      get() = _builder.getEndpoint()
      @JvmName("setEndpoint")
      set(value) {
        _builder.setEndpoint(value)
      }
    /**
     * ```
     * SDK decorator arg ('/api/summarize')
     * ```
     *
     * `string endpoint = 8 [json_name = "endpoint"];`
     */
    public fun clearEndpoint() {
      _builder.clearEndpoint()
    }

    /**
     * ```
     * SDK config
     * ```
     *
     * `.llm.observability.v1.Environment environment = 9 [json_name = "environment"];`
     */
    public var environment: com.llmobservability.platform.v1.Environment
      @JvmName("getEnvironment")
      get() = _builder.getEnvironment()
      @JvmName("setEnvironment")
      set(value) {
        _builder.setEnvironment(value)
      }
    public var environmentValue: kotlin.Int
      @JvmName("getEnvironmentValue")
      get() = _builder.getEnvironmentValue()
      @JvmName("setEnvironmentValue")
      set(value) {
        _builder.setEnvironmentValue(value)
      }
    /**
     * ```
     * SDK config
     * ```
     *
     * `.llm.observability.v1.Environment environment = 9 [json_name = "environment"];`
     */
    public fun clearEnvironment() {
      _builder.clearEnvironment()
    }

    /**
     * ```
     * SDK call arg. Null for anonymous
     * ```
     *
     * `optional string user_id = 10 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * ```
     * SDK call arg. Null for anonymous
     * ```
     *
     * `optional string user_id = 10 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * ```
     * SDK call arg. Null for anonymous
     * ```
     *
     * `optional string user_id = 10 [json_name = "userId"];`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    /**
     * ```
     * SDK call arg. Null for stateless
     * ```
     *
     * `optional string session_id = 11 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.getSessionId()
      @JvmName("setSessionId")
      set(value) {
        _builder.setSessionId(value)
      }
    /**
     * ```
     * SDK call arg. Null for stateless
     * ```
     *
     * `optional string session_id = 11 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }
    /**
     * ```
     * SDK call arg. Null for stateless
     * ```
     *
     * `optional string session_id = 11 [json_name = "sessionId"];`
     * @return Whether the sessionId field is set.
     */
    public fun hasSessionId(): kotlin.Boolean {
      return _builder.hasSessionId()
    }

    /**
     * ```
     * Exact BPE count, > 0
     * ```
     *
     * `int32 prompt_tokens = 12 [json_name = "promptTokens"];`
     */
    public var promptTokens: kotlin.Int
      @JvmName("getPromptTokens")
      get() = _builder.getPromptTokens()
      @JvmName("setPromptTokens")
      set(value) {
        _builder.setPromptTokens(value)
      }
    /**
     * ```
     * Exact BPE count, > 0
     * ```
     *
     * `int32 prompt_tokens = 12 [json_name = "promptTokens"];`
     */
    public fun clearPromptTokens() {
      _builder.clearPromptTokens()
    }

    /**
     * ```
     * Exact BPE count, >= 0
     * ```
     *
     * `int32 completion_tokens = 13 [json_name = "completionTokens"];`
     */
    public var completionTokens: kotlin.Int
      @JvmName("getCompletionTokens")
      get() = _builder.getCompletionTokens()
      @JvmName("setCompletionTokens")
      set(value) {
        _builder.setCompletionTokens(value)
      }
    /**
     * ```
     * Exact BPE count, >= 0
     * ```
     *
     * `int32 completion_tokens = 13 [json_name = "completionTokens"];`
     */
    public fun clearCompletionTokens() {
      _builder.clearCompletionTokens()
    }

    /**
     * ```
     * Time to first chunk byte
     * ```
     *
     * `optional int32 latency_ms_ttft = 14 [json_name = "latencyMsTtft"];`
     */
    public var latencyMsTtft: kotlin.Int
      @JvmName("getLatencyMsTtft")
      get() = _builder.getLatencyMsTtft()
      @JvmName("setLatencyMsTtft")
      set(value) {
        _builder.setLatencyMsTtft(value)
      }
    /**
     * ```
     * Time to first chunk byte
     * ```
     *
     * `optional int32 latency_ms_ttft = 14 [json_name = "latencyMsTtft"];`
     */
    public fun clearLatencyMsTtft() {
      _builder.clearLatencyMsTtft()
    }
    /**
     * ```
     * Time to first chunk byte
     * ```
     *
     * `optional int32 latency_ms_ttft = 14 [json_name = "latencyMsTtft"];`
     * @return Whether the latencyMsTtft field is set.
     */
    public fun hasLatencyMsTtft(): kotlin.Boolean {
      return _builder.hasLatencyMsTtft()
    }

    /**
     * ```
     * Full wall clock, > 0
     * ```
     *
     * `int32 latency_ms_total = 15 [json_name = "latencyMsTotal"];`
     */
    public var latencyMsTotal: kotlin.Int
      @JvmName("getLatencyMsTotal")
      get() = _builder.getLatencyMsTotal()
      @JvmName("setLatencyMsTotal")
      set(value) {
        _builder.setLatencyMsTotal(value)
      }
    /**
     * ```
     * Full wall clock, > 0
     * ```
     *
     * `int32 latency_ms_total = 15 [json_name = "latencyMsTotal"];`
     */
    public fun clearLatencyMsTotal() {
      _builder.clearLatencyMsTotal()
    }

    /**
     * ```
     * Provider response finish reason
     * ```
     *
     * `.llm.observability.v1.FinishReason finish_reason = 16 [json_name = "finishReason"];`
     */
    public var finishReason: com.llmobservability.platform.v1.FinishReason
      @JvmName("getFinishReason")
      get() = _builder.getFinishReason()
      @JvmName("setFinishReason")
      set(value) {
        _builder.setFinishReason(value)
      }
    public var finishReasonValue: kotlin.Int
      @JvmName("getFinishReasonValue")
      get() = _builder.getFinishReasonValue()
      @JvmName("setFinishReasonValue")
      set(value) {
        _builder.setFinishReasonValue(value)
      }
    /**
     * ```
     * Provider response finish reason
     * ```
     *
     * `.llm.observability.v1.FinishReason finish_reason = 16 [json_name = "finishReason"];`
     */
    public fun clearFinishReason() {
      _builder.clearFinishReason()
    }

    /**
     * ```
     * SDK computed cost in micro-USD, >= 0
     * ```
     *
     * `int64 cost_usd_micro = 17 [json_name = "costUsdMicro"];`
     */
    public var costUsdMicro: kotlin.Long
      @JvmName("getCostUsdMicro")
      get() = _builder.getCostUsdMicro()
      @JvmName("setCostUsdMicro")
      set(value) {
        _builder.setCostUsdMicro(value)
      }
    /**
     * ```
     * SDK computed cost in micro-USD, >= 0
     * ```
     *
     * `int64 cost_usd_micro = 17 [json_name = "costUsdMicro"];`
     */
    public fun clearCostUsdMicro() {
      _builder.clearCostUsdMicro()
    }

    /**
     * ```
     * SDK config price version date
     * ```
     *
     * `string price_version = 18 [json_name = "priceVersion"];`
     */
    public var priceVersion: kotlin.String
      @JvmName("getPriceVersion")
      get() = _builder.getPriceVersion()
      @JvmName("setPriceVersion")
      set(value) {
        _builder.setPriceVersion(value)
      }
    /**
     * ```
     * SDK config price version date
     * ```
     *
     * `string price_version = 18 [json_name = "priceVersion"];`
     */
    public fun clearPriceVersion() {
      _builder.clearPriceVersion()
    }

    /**
     * ```
     * SDK token method
     * ```
     *
     * `.llm.observability.v1.TokenCountMethod token_count_method = 19 [json_name = "tokenCountMethod"];`
     */
    public var tokenCountMethod: com.llmobservability.platform.v1.TokenCountMethod
      @JvmName("getTokenCountMethod")
      get() = _builder.getTokenCountMethod()
      @JvmName("setTokenCountMethod")
      set(value) {
        _builder.setTokenCountMethod(value)
      }
    public var tokenCountMethodValue: kotlin.Int
      @JvmName("getTokenCountMethodValue")
      get() = _builder.getTokenCountMethodValue()
      @JvmName("setTokenCountMethodValue")
      set(value) {
        _builder.setTokenCountMethodValue(value)
      }
    /**
     * ```
     * SDK token method
     * ```
     *
     * `.llm.observability.v1.TokenCountMethod token_count_method = 19 [json_name = "tokenCountMethod"];`
     */
    public fun clearTokenCountMethod() {
      _builder.clearTokenCountMethod()
    }

    /**
     * ```
     * TRUE if hash(span_id) % 100 == 0
     * ```
     *
     * `bool is_sampled = 20 [json_name = "isSampled"];`
     */
    public var isSampled: kotlin.Boolean
      @JvmName("getIsSampled")
      get() = _builder.getIsSampled()
      @JvmName("setIsSampled")
      set(value) {
        _builder.setIsSampled(value)
      }
    /**
     * ```
     * TRUE if hash(span_id) % 100 == 0
     * ```
     *
     * `bool is_sampled = 20 [json_name = "isSampled"];`
     */
    public fun clearIsSampled() {
      _builder.clearIsSampled()
    }

    /**
     * ```
     * 0 for first-attempt calls
     * ```
     *
     * `int32 retry_count = 21 [json_name = "retryCount"];`
     */
    public var retryCount: kotlin.Int
      @JvmName("getRetryCount")
      get() = _builder.getRetryCount()
      @JvmName("setRetryCount")
      set(value) {
        _builder.setRetryCount(value)
      }
    /**
     * ```
     * 0 for first-attempt calls
     * ```
     *
     * `int32 retry_count = 21 [json_name = "retryCount"];`
     */
    public fun clearRetryCount() {
      _builder.clearRetryCount()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AttemptedModelsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Fallback chains
     * ```
     *
     * `repeated string attempted_models = 22 [json_name = "attemptedModels"];`
     * @return A list containing the attemptedModels.
     */
    public val attemptedModels: com.google.protobuf.kotlin.DslList<kotlin.String, AttemptedModelsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAttemptedModelsList()
      )
    /**
     * ```
     * Fallback chains
     * ```
     *
     * `repeated string attempted_models = 22 [json_name = "attemptedModels"];`
     * @param value The attemptedModels to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAttemptedModels")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttemptedModelsProxy>.add(value: kotlin.String) {
      _builder.addAttemptedModels(value)
    }
    /**
     * ```
     * Fallback chains
     * ```
     *
     * `repeated string attempted_models = 22 [json_name = "attemptedModels"];`
     * @param value The attemptedModels to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAttemptedModels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttemptedModelsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * Fallback chains
     * ```
     *
     * `repeated string attempted_models = 22 [json_name = "attemptedModels"];`
     * @param values The attemptedModels to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAttemptedModels")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttemptedModelsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAttemptedModels(values)
    }
    /**
     * ```
     * Fallback chains
     * ```
     *
     * `repeated string attempted_models = 22 [json_name = "attemptedModels"];`
     * @param values The attemptedModels to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAttemptedModels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttemptedModelsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * Fallback chains
     * ```
     *
     * `repeated string attempted_models = 22 [json_name = "attemptedModels"];`
     * @param index The index to set the value at.
     * @param value The attemptedModels to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAttemptedModels")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttemptedModelsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setAttemptedModels(index, value)
    }/**
     * ```
     * Fallback chains
     * ```
     *
     * `repeated string attempted_models = 22 [json_name = "attemptedModels"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAttemptedModels")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttemptedModelsProxy>.clear() {
      _builder.clearAttemptedModels()
    }
    /**
     * ```
     * Aho-Corasick computed inline before emit
     * ```
     *
     * `bool pii_detected = 23 [json_name = "piiDetected"];`
     */
    public var piiDetected: kotlin.Boolean
      @JvmName("getPiiDetected")
      get() = _builder.getPiiDetected()
      @JvmName("setPiiDetected")
      set(value) {
        _builder.setPiiDetected(value)
      }
    /**
     * ```
     * Aho-Corasick computed inline before emit
     * ```
     *
     * `bool pii_detected = 23 [json_name = "piiDetected"];`
     */
    public fun clearPiiDetected() {
      _builder.clearPiiDetected()
    }

    /**
     * ```
     * Aho-Corasick jailbreak/injection pattern matched
     * ```
     *
     * `bool injection_attempt = 24 [json_name = "injectionAttempt"];`
     */
    public var injectionAttempt: kotlin.Boolean
      @JvmName("getInjectionAttempt")
      get() = _builder.getInjectionAttempt()
      @JvmName("setInjectionAttempt")
      set(value) {
        _builder.setInjectionAttempt(value)
      }
    /**
     * ```
     * Aho-Corasick jailbreak/injection pattern matched
     * ```
     *
     * `bool injection_attempt = 24 [json_name = "injectionAttempt"];`
     */
    public fun clearInjectionAttempt() {
      _builder.clearInjectionAttempt()
    }

    /**
     * ```
     * SDK (client clock) UTC, ISO 8601 string or Unix nanoseconds.
     * ```
     *
     * `string timestamp_utc = 25 [json_name = "timestampUtc"];`
     */
    public var timestampUtc: kotlin.String
      @JvmName("getTimestampUtc")
      get() = _builder.getTimestampUtc()
      @JvmName("setTimestampUtc")
      set(value) {
        _builder.setTimestampUtc(value)
      }
    /**
     * ```
     * SDK (client clock) UTC, ISO 8601 string or Unix nanoseconds.
     * ```
     *
     * `string timestamp_utc = 25 [json_name = "timestampUtc"];`
     */
    public fun clearTimestampUtc() {
      _builder.clearTimestampUtc()
    }

    /**
     * ```
     * SAMPLED-ONLY FIELDS
     * SHA256(prompt_text) 64-char hex. Null if pii_detected.
     * ```
     *
     * `optional string prompt_hash = 26 [json_name = "promptHash"];`
     */
    public var promptHash: kotlin.String
      @JvmName("getPromptHash")
      get() = _builder.getPromptHash()
      @JvmName("setPromptHash")
      set(value) {
        _builder.setPromptHash(value)
      }
    /**
     * ```
     * SAMPLED-ONLY FIELDS
     * SHA256(prompt_text) 64-char hex. Null if pii_detected.
     * ```
     *
     * `optional string prompt_hash = 26 [json_name = "promptHash"];`
     */
    public fun clearPromptHash() {
      _builder.clearPromptHash()
    }
    /**
     * ```
     * SAMPLED-ONLY FIELDS
     * SHA256(prompt_text) 64-char hex. Null if pii_detected.
     * ```
     *
     * `optional string prompt_hash = 26 [json_name = "promptHash"];`
     * @return Whether the promptHash field is set.
     */
    public fun hasPromptHash(): kotlin.Boolean {
      return _builder.hasPromptHash()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PromptEmbeddingProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];`
     */
     public val promptEmbedding: com.google.protobuf.kotlin.DslList<kotlin.Float, PromptEmbeddingProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPromptEmbeddingList()
      )
    /**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];`
     * @param value The promptEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPromptEmbedding")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, PromptEmbeddingProxy>.add(value: kotlin.Float) {
      _builder.addPromptEmbedding(value)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];`
     * @param value The promptEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPromptEmbedding")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, PromptEmbeddingProxy>.plusAssign(value: kotlin.Float) {
      add(value)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];`
     * @param values The promptEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPromptEmbedding")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, PromptEmbeddingProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Float>) {
      _builder.addAllPromptEmbedding(values)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];`
     * @param values The promptEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPromptEmbedding")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, PromptEmbeddingProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Float>) {
      addAll(values)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];`
     * @param index The index to set the value at.
     * @param value The promptEmbedding to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPromptEmbedding")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, PromptEmbeddingProxy>.set(index: kotlin.Int, value: kotlin.Float) {
      _builder.setPromptEmbedding(index, value)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPromptEmbedding")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, PromptEmbeddingProxy>.clear() {
      _builder.clearPromptEmbedding()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResponseEmbeddingProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float response_embedding = 28 [json_name = "responseEmbedding"];`
     */
     public val responseEmbedding: com.google.protobuf.kotlin.DslList<kotlin.Float, ResponseEmbeddingProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getResponseEmbeddingList()
      )
    /**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float response_embedding = 28 [json_name = "responseEmbedding"];`
     * @param value The responseEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addResponseEmbedding")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, ResponseEmbeddingProxy>.add(value: kotlin.Float) {
      _builder.addResponseEmbedding(value)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float response_embedding = 28 [json_name = "responseEmbedding"];`
     * @param value The responseEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignResponseEmbedding")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, ResponseEmbeddingProxy>.plusAssign(value: kotlin.Float) {
      add(value)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float response_embedding = 28 [json_name = "responseEmbedding"];`
     * @param values The responseEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllResponseEmbedding")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, ResponseEmbeddingProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Float>) {
      _builder.addAllResponseEmbedding(values)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float response_embedding = 28 [json_name = "responseEmbedding"];`
     * @param values The responseEmbedding to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllResponseEmbedding")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, ResponseEmbeddingProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Float>) {
      addAll(values)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float response_embedding = 28 [json_name = "responseEmbedding"];`
     * @param index The index to set the value at.
     * @param value The responseEmbedding to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setResponseEmbedding")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, ResponseEmbeddingProxy>.set(index: kotlin.Int, value: kotlin.Float) {
      _builder.setResponseEmbedding(index, value)
    }/**
     * ```
     * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
     * ```
     *
     * `repeated float response_embedding = 28 [json_name = "responseEmbedding"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearResponseEmbedding")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, ResponseEmbeddingProxy>.clear() {
      _builder.clearResponseEmbedding()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.LLMSpan.copy(block: `com.llmobservability.platform.v1`.LLMSpanKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.LLMSpan =
  `com.llmobservability.platform.v1`.LLMSpanKt.Dsl._create(this.toBuilder()).apply { block() }._build()

