// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializemodelPriceProto")
public inline fun modelPriceProto(block: com.llmobservability.platform.v1.ModelPriceProtoKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.ModelPriceProto =
  com.llmobservability.platform.v1.ModelPriceProtoKt.Dsl._create(com.llmobservability.platform.v1.ModelPriceProto.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.ModelPriceProto`
 */
public object ModelPriceProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.ModelPriceProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.ModelPriceProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.ModelPriceProto = _builder.build()

    /**
     * `string model = 1 [json_name = "model"];`
     */
    public var model: kotlin.String
      @JvmName("getModel")
      get() = _builder.getModel()
      @JvmName("setModel")
      set(value) {
        _builder.setModel(value)
      }
    /**
     * `string model = 1 [json_name = "model"];`
     */
    public fun clearModel() {
      _builder.clearModel()
    }

    /**
     * `string provider = 2 [json_name = "provider"];`
     */
    public var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * `string provider = 2 [json_name = "provider"];`
     */
    public fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * `double input_price_per_1m = 3 [json_name = "inputPricePer1m"];`
     */
    public var inputPricePer1M: kotlin.Double
      @JvmName("getInputPricePer1M")
      get() = _builder.getInputPricePer1M()
      @JvmName("setInputPricePer1M")
      set(value) {
        _builder.setInputPricePer1M(value)
      }
    /**
     * `double input_price_per_1m = 3 [json_name = "inputPricePer1m"];`
     */
    public fun clearInputPricePer1M() {
      _builder.clearInputPricePer1M()
    }

    /**
     * `double output_price_per_1m = 4 [json_name = "outputPricePer1m"];`
     */
    public var outputPricePer1M: kotlin.Double
      @JvmName("getOutputPricePer1M")
      get() = _builder.getOutputPricePer1M()
      @JvmName("setOutputPricePer1M")
      set(value) {
        _builder.setOutputPricePer1M(value)
      }
    /**
     * `double output_price_per_1m = 4 [json_name = "outputPricePer1m"];`
     */
    public fun clearOutputPricePer1M() {
      _builder.clearOutputPricePer1M()
    }

    /**
     * `string version = 5 [json_name = "version"];`
     */
    public var version: kotlin.String
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    /**
     * `string version = 5 [json_name = "version"];`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.ModelPriceProto.copy(block: `com.llmobservability.platform.v1`.ModelPriceProtoKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.ModelPriceProto =
  `com.llmobservability.platform.v1`.ModelPriceProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

