// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/span.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializerecordSpanResponse")
public inline fun recordSpanResponse(block: com.llmobservability.platform.v1.RecordSpanResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.RecordSpanResponse =
  com.llmobservability.platform.v1.RecordSpanResponseKt.Dsl._create(com.llmobservability.platform.v1.RecordSpanResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.RecordSpanResponse`
 */
public object RecordSpanResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.RecordSpanResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.RecordSpanResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.RecordSpanResponse = _builder.build()

    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * `bool success = 1 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SpanWarningsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * For returning W-series warnings
     * ```
     *
     * `repeated string span_warnings = 2 [json_name = "spanWarnings"];`
     * @return A list containing the spanWarnings.
     */
    public val spanWarnings: com.google.protobuf.kotlin.DslList<kotlin.String, SpanWarningsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSpanWarningsList()
      )
    /**
     * ```
     * For returning W-series warnings
     * ```
     *
     * `repeated string span_warnings = 2 [json_name = "spanWarnings"];`
     * @param value The spanWarnings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSpanWarnings")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SpanWarningsProxy>.add(value: kotlin.String) {
      _builder.addSpanWarnings(value)
    }
    /**
     * ```
     * For returning W-series warnings
     * ```
     *
     * `repeated string span_warnings = 2 [json_name = "spanWarnings"];`
     * @param value The spanWarnings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSpanWarnings")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SpanWarningsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * For returning W-series warnings
     * ```
     *
     * `repeated string span_warnings = 2 [json_name = "spanWarnings"];`
     * @param values The spanWarnings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSpanWarnings")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SpanWarningsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllSpanWarnings(values)
    }
    /**
     * ```
     * For returning W-series warnings
     * ```
     *
     * `repeated string span_warnings = 2 [json_name = "spanWarnings"];`
     * @param values The spanWarnings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSpanWarnings")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SpanWarningsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * For returning W-series warnings
     * ```
     *
     * `repeated string span_warnings = 2 [json_name = "spanWarnings"];`
     * @param index The index to set the value at.
     * @param value The spanWarnings to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSpanWarnings")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, SpanWarningsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setSpanWarnings(index, value)
    }/**
     * ```
     * For returning W-series warnings
     * ```
     *
     * `repeated string span_warnings = 2 [json_name = "spanWarnings"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSpanWarnings")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, SpanWarningsProxy>.clear() {
      _builder.clearSpanWarnings()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.RecordSpanResponse.copy(block: `com.llmobservability.platform.v1`.RecordSpanResponseKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.RecordSpanResponse =
  `com.llmobservability.platform.v1`.RecordSpanResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

