// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializerecordMetricsRequest")
public inline fun recordMetricsRequest(block: com.llmobservability.platform.v1.RecordMetricsRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.RecordMetricsRequest =
  com.llmobservability.platform.v1.RecordMetricsRequestKt.Dsl._create(com.llmobservability.platform.v1.RecordMetricsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.RecordMetricsRequest`
 */
public object RecordMetricsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.RecordMetricsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.RecordMetricsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.RecordMetricsRequest = _builder.build()

    /**
     * `string model = 1 [json_name = "model"];`
     */
    public var model: kotlin.String
      @JvmName("getModel")
      get() = _builder.getModel()
      @JvmName("setModel")
      set(value) {
        _builder.setModel(value)
      }
    /**
     * `string model = 1 [json_name = "model"];`
     */
    public fun clearModel() {
      _builder.clearModel()
    }

    /**
     * `string provider = 2 [json_name = "provider"];`
     */
    public var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * `string provider = 2 [json_name = "provider"];`
     */
    public fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `optional int32 prompt_tokens = 4 [json_name = "promptTokens"];`
     */
    public var promptTokens: kotlin.Int
      @JvmName("getPromptTokens")
      get() = _builder.getPromptTokens()
      @JvmName("setPromptTokens")
      set(value) {
        _builder.setPromptTokens(value)
      }
    /**
     * `optional int32 prompt_tokens = 4 [json_name = "promptTokens"];`
     */
    public fun clearPromptTokens() {
      _builder.clearPromptTokens()
    }
    /**
     * `optional int32 prompt_tokens = 4 [json_name = "promptTokens"];`
     * @return Whether the promptTokens field is set.
     */
    public fun hasPromptTokens(): kotlin.Boolean {
      return _builder.hasPromptTokens()
    }

    /**
     * `optional int32 completion_tokens = 5 [json_name = "completionTokens"];`
     */
    public var completionTokens: kotlin.Int
      @JvmName("getCompletionTokens")
      get() = _builder.getCompletionTokens()
      @JvmName("setCompletionTokens")
      set(value) {
        _builder.setCompletionTokens(value)
      }
    /**
     * `optional int32 completion_tokens = 5 [json_name = "completionTokens"];`
     */
    public fun clearCompletionTokens() {
      _builder.clearCompletionTokens()
    }
    /**
     * `optional int32 completion_tokens = 5 [json_name = "completionTokens"];`
     * @return Whether the completionTokens field is set.
     */
    public fun hasCompletionTokens(): kotlin.Boolean {
      return _builder.hasCompletionTokens()
    }

    /**
     * `optional int64 cost_usd_micro = 6 [json_name = "costUsdMicro"];`
     */
    public var costUsdMicro: kotlin.Long
      @JvmName("getCostUsdMicro")
      get() = _builder.getCostUsdMicro()
      @JvmName("setCostUsdMicro")
      set(value) {
        _builder.setCostUsdMicro(value)
      }
    /**
     * `optional int64 cost_usd_micro = 6 [json_name = "costUsdMicro"];`
     */
    public fun clearCostUsdMicro() {
      _builder.clearCostUsdMicro()
    }
    /**
     * `optional int64 cost_usd_micro = 6 [json_name = "costUsdMicro"];`
     * @return Whether the costUsdMicro field is set.
     */
    public fun hasCostUsdMicro(): kotlin.Boolean {
      return _builder.hasCostUsdMicro()
    }

    /**
     * `optional int32 latency_ms_total = 7 [json_name = "latencyMsTotal"];`
     */
    public var latencyMsTotal: kotlin.Int
      @JvmName("getLatencyMsTotal")
      get() = _builder.getLatencyMsTotal()
      @JvmName("setLatencyMsTotal")
      set(value) {
        _builder.setLatencyMsTotal(value)
      }
    /**
     * `optional int32 latency_ms_total = 7 [json_name = "latencyMsTotal"];`
     */
    public fun clearLatencyMsTotal() {
      _builder.clearLatencyMsTotal()
    }
    /**
     * `optional int32 latency_ms_total = 7 [json_name = "latencyMsTotal"];`
     * @return Whether the latencyMsTotal field is set.
     */
    public fun hasLatencyMsTotal(): kotlin.Boolean {
      return _builder.hasLatencyMsTotal()
    }

    /**
     * `optional int32 latency_ms_ttft = 8 [json_name = "latencyMsTtft"];`
     */
    public var latencyMsTtft: kotlin.Int
      @JvmName("getLatencyMsTtft")
      get() = _builder.getLatencyMsTtft()
      @JvmName("setLatencyMsTtft")
      set(value) {
        _builder.setLatencyMsTtft(value)
      }
    /**
     * `optional int32 latency_ms_ttft = 8 [json_name = "latencyMsTtft"];`
     */
    public fun clearLatencyMsTtft() {
      _builder.clearLatencyMsTtft()
    }
    /**
     * `optional int32 latency_ms_ttft = 8 [json_name = "latencyMsTtft"];`
     * @return Whether the latencyMsTtft field is set.
     */
    public fun hasLatencyMsTtft(): kotlin.Boolean {
      return _builder.hasLatencyMsTtft()
    }

    /**
     * `optional string finish_reason = 9 [json_name = "finishReason"];`
     */
    public var finishReason: kotlin.String
      @JvmName("getFinishReason")
      get() = _builder.getFinishReason()
      @JvmName("setFinishReason")
      set(value) {
        _builder.setFinishReason(value)
      }
    /**
     * `optional string finish_reason = 9 [json_name = "finishReason"];`
     */
    public fun clearFinishReason() {
      _builder.clearFinishReason()
    }
    /**
     * `optional string finish_reason = 9 [json_name = "finishReason"];`
     * @return Whether the finishReason field is set.
     */
    public fun hasFinishReason(): kotlin.Boolean {
      return _builder.hasFinishReason()
    }

    /**
     * `string status = 10 [json_name = "status"];`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * `string status = 10 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `bool pii_detected = 11 [json_name = "piiDetected"];`
     */
    public var piiDetected: kotlin.Boolean
      @JvmName("getPiiDetected")
      get() = _builder.getPiiDetected()
      @JvmName("setPiiDetected")
      set(value) {
        _builder.setPiiDetected(value)
      }
    /**
     * `bool pii_detected = 11 [json_name = "piiDetected"];`
     */
    public fun clearPiiDetected() {
      _builder.clearPiiDetected()
    }

    /**
     * `bool injection_attempt = 12 [json_name = "injectionAttempt"];`
     */
    public var injectionAttempt: kotlin.Boolean
      @JvmName("getInjectionAttempt")
      get() = _builder.getInjectionAttempt()
      @JvmName("setInjectionAttempt")
      set(value) {
        _builder.setInjectionAttempt(value)
      }
    /**
     * `bool injection_attempt = 12 [json_name = "injectionAttempt"];`
     */
    public fun clearInjectionAttempt() {
      _builder.clearInjectionAttempt()
    }

    /**
     * `int32 retry_count = 13 [json_name = "retryCount"];`
     */
    public var retryCount: kotlin.Int
      @JvmName("getRetryCount")
      get() = _builder.getRetryCount()
      @JvmName("setRetryCount")
      set(value) {
        _builder.setRetryCount(value)
      }
    /**
     * `int32 retry_count = 13 [json_name = "retryCount"];`
     */
    public fun clearRetryCount() {
      _builder.clearRetryCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.RecordMetricsRequest.copy(block: `com.llmobservability.platform.v1`.RecordMetricsRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.RecordMetricsRequest =
  `com.llmobservability.platform.v1`.RecordMetricsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

