// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.llmobservability.platform.v1;

@kotlin.jvm.JvmName("-initializetriggerTestStreamCallRequest")
public inline fun triggerTestStreamCallRequest(block: com.llmobservability.platform.v1.TriggerTestStreamCallRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.TriggerTestStreamCallRequest =
  com.llmobservability.platform.v1.TriggerTestStreamCallRequestKt.Dsl._create(com.llmobservability.platform.v1.TriggerTestStreamCallRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `llm.observability.v1.TriggerTestStreamCallRequest`
 */
public object TriggerTestStreamCallRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.llmobservability.platform.v1.TriggerTestStreamCallRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.llmobservability.platform.v1.TriggerTestStreamCallRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.llmobservability.platform.v1.TriggerTestStreamCallRequest = _builder.build()

    /**
     * `string provider = 1 [json_name = "provider"];`
     */
    public var provider: kotlin.String
      @JvmName("getProvider")
      get() = _builder.getProvider()
      @JvmName("setProvider")
      set(value) {
        _builder.setProvider(value)
      }
    /**
     * `string provider = 1 [json_name = "provider"];`
     */
    public fun clearProvider() {
      _builder.clearProvider()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChunksProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string chunks = 2 [json_name = "chunks"];`
     * @return A list containing the chunks.
     */
    public val chunks: com.google.protobuf.kotlin.DslList<kotlin.String, ChunksProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getChunksList()
      )
    /**
     * `repeated string chunks = 2 [json_name = "chunks"];`
     * @param value The chunks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addChunks")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChunksProxy>.add(value: kotlin.String) {
      _builder.addChunks(value)
    }
    /**
     * `repeated string chunks = 2 [json_name = "chunks"];`
     * @param value The chunks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignChunks")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChunksProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string chunks = 2 [json_name = "chunks"];`
     * @param values The chunks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllChunks")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChunksProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllChunks(values)
    }
    /**
     * `repeated string chunks = 2 [json_name = "chunks"];`
     * @param values The chunks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllChunks")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChunksProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string chunks = 2 [json_name = "chunks"];`
     * @param index The index to set the value at.
     * @param value The chunks to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setChunks")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChunksProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setChunks(index, value)
    }/**
     * `repeated string chunks = 2 [json_name = "chunks"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearChunks")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChunksProxy>.clear() {
      _builder.clearChunks()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.llmobservability.platform.v1.TriggerTestStreamCallRequest.copy(block: `com.llmobservability.platform.v1`.TriggerTestStreamCallRequestKt.Dsl.() -> kotlin.Unit): com.llmobservability.platform.v1.TriggerTestStreamCallRequest =
  `com.llmobservability.platform.v1`.TriggerTestStreamCallRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

