version: "3.8"

services:
  postgresql:
    container_name: temporal-postgresql
    image: postgres:14
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    ports:
      - "5432:5432"
    volumes:
      - temporal_pg_data:/var/lib/postgresql/data
    networks:
      - temporal-network

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.25
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - temporal-network

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1.25
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    networks:
      - temporal-network

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:2.26.2
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
      - TEMPORAL_CSRF_ENABLED=true

    ports:
      - "8080:8080"
    networks:
      - temporal-network
    
    labels:
      traefik.enable: "true"
      traefik.docker.network: "temporal-network"
      
      traefik.http.routers.temporal-ui-scaibu.rule: "Host(`scaibu.temporal`)"
      traefik.http.routers.temporal-ui-scaibu.entrypoints: "traefik"
      traefik.http.routers.temporal-ui-scaibu.service: "temporal-ui-svc"
      traefik.http.routers.temporal-ui-scaibu.middlewares: "security-headers"
      
      traefik.http.services.temporal-ui-svc.loadbalancer.server.port: "8080"
      
      traefik.http.middlewares.security-headers.headers.framedeny: "true"
      traefik.http.middlewares.security-headers.headers.contenttypenosniff: "true"

volumes:
  temporal_pg_data:

networks:
  temporal-network:
    external: true
