export const TRACES_TEXT = {
  HEADER_TITLE: "Distributed Spans & Execution Traces",
  HEADER_SUBTITLE: "Search and inspect distributed execution spans, OpenTelemetry trace trees, and latency bottlenecks.",
  SEARCH_PLACEHOLDER: "Search trace ID, operation...",
  KPI_TOTAL_TRACES: "Total Traces",
  KPI_TOTAL_TRACES_DESC: "Recorded execution streams",
  KPI_AVG_LATENCY: "Avg Latency",
  KPI_AVG_LATENCY_DESC: "Average trace duration",
  KPI_ERROR_RATE: "Error Rate",
  KPI_ERROR_RATE_DESC: "Trace failures ratio",
  KPI_TOTAL_TOKENS: "Total Tokens",
  KPI_TOTAL_TOKENS_DESC: "total spend",

  FILTER_ALL_SERVICES: "All Services",
  FILTER_ALL_STATUSES: "All Statuses",
  FILTER_ALL_MODELS: "All Models",
  FILTER_STATUS_SUCCESS: "Success",
  FILTER_STATUS_ERROR: "Error",
  FILTER_MIN_DURATION_PREFIX: "Min:",
  FILTER_MIN_DURATION_PLACEHOLDER: "0 ms",
  FILTER_RESET_BUTTON: "Reset All Filters",

  TABLE_TRACE_ID: "Trace ID",
  TABLE_ROOT_OPERATION: "Root Operation",
  TABLE_SERVICE: "Service",
  TABLE_MODEL: "Model",
  TABLE_DURATION: "Duration",
  TABLE_TOKENS: "Tokens",
  TABLE_EST_COST: "Est. Cost",
  TABLE_STATUS: "Status",
  TABLE_ACTION_FLAME: "Flame Graph",
  NO_TRACES_MATCH: "No distributed traces recorded matching your filter parameters.",

  WATERFALL_BACK_LINK: "Back to Traces Explorer",
  WATERFALL_TRACE_ID_LABEL: "Trace ID:",
  WATERFALL_TOTAL_DURATION: "Total Duration:",
  WATERFALL_TOTAL_SPANS: "Total Spans:",
  WATERFALL_CLICK_INFO: "Click any span row to inspect OpenTelemetry metadata & payloads",
  WATERFALL_COL_SPAN: "Span Name & Service",
  WATERFALL_COL_ID: "Span ID",
  WATERFALL_COL_DURATION: "Duration",
  WATERFALL_COL_TIMELINE: "Execution Timeline Waterfall",

  DRAWER_TITLE: "Execution Timing",
  DRAWER_CLOSE: "Close span details drawer",
  DRAWER_START_OFFSET: "Start Offset",
  DRAWER_DURATION: "Duration",
  DRAWER_TRACE_PCT: "% of Trace",
  DRAWER_SPAN_IDENTIFIERS: "Span Identifiers",
  DRAWER_SPAN_ID: "Span ID:",
  DRAWER_PARENT_SPAN_ID: "Parent Span ID:",
  DRAWER_MODEL_TARGET: "Model Target:",
  DRAWER_OTEL_ATTRIBUTES: "OpenTelemetry Attributes",
  DRAWER_NO_ATTRIBUTES: "No attributes attached to this span.",
  DRAWER_COL_KEY: "Attribute Key",
  DRAWER_COL_VALUE: "Value",
  DRAWER_PAYLOAD_HEADER: "Prompt & Completion Payload",
  DRAWER_PROMPT_INPUT: "Prompt Input",
  DRAWER_COMPLETION_OUTPUT: "Completion Output",
  DRAWER_COPY_BUTTON: "Copy",
} as const;
