export const OTEL_ATTRIBUTES = {
  SERVICE_NAME: "service.name",
  ENDPOINT: "endpoint",
  LLM_MODEL: "llm.model",
  LLM_PROVIDER: "llm.provider",
  PROMPT_TOKENS: "llm.usage.prompt_tokens",
  COMPLETION_TOKENS: "llm.usage.completion_tokens",
  LATENCY_TTFT_MS: "llm.latency_ms_ttft",
  LATENCY_TOTAL_MS: "llm.latency_ms_total",
  COST_USD_MICRO: "llm.cost_usd_micro",
  FINISH_REASON: "llm.finish_reason",
  PII_DETECTED: "llm.pii_detected",
  INJECTION_ATTEMPT: "llm.injection_attempt",
  SPAN_WARNINGS: "llm.span_warnings",
  PROMPT_TEXT: "llm.prompt",
  COMPLETION_TEXT: "llm.completion",
  ENVIRONMENT: "llm.environment",
  USER_ID: "user.id",
  SESSION_ID: "session.id",
} as const;
