from typing import Protocol

class RedisPort(Protocol):
    def acquire_rate_limit(self, key: str, ttl_seconds: int) -> bool: ...
    def get_open_incident(self, model: str, endpoint: str) -> str | None: ...
    def set_open_incident(self, model: str, endpoint: str, incident_id: str, ttl: int) -> None: ...
    def delete_open_incident(self, model: str, endpoint: str) -> None: ...

