from typing import Protocol, Tuple, List
from shared.types.ewma_types import ClusterCost


class ClickHousePort(Protocol):
    def get_active_pairs(self) -> List[Tuple[str, str]]: ...

    def get_cost_history(
        self, service: str, model: str, hour_of_week: int
    ) -> List[float]: ...

    def get_global_model_avg(self, model: str, hour_of_week: int) -> float: ...

    def get_current_cost_1h(self, service: str, model: str) -> float: ...

    def get_cost_by_cluster_1h(self, service: str, model: str) -> List[ClusterCost]: ...

    def get_active_keys(self, dimension: str) -> List[str]: ...

    def get_clickhouse_sum_1h(self, dimension: str, key: str) -> int: ...

    def get_spans_for_correction(self, hours: int) -> List[dict]: ...

    def insert_correction_rows(self, rows: List[dict]) -> None: ...

