// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface DetectProviderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.DetectProviderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string body = 2 [json_name = "body"];</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2 [json_name = "body"];</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
