// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface DetectProviderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.DetectProviderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string provider = 1 [json_name = "provider"];</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <code>string provider = 1 [json_name = "provider"];</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();
}
