// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/span.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

/**
 * <pre>
 * FinishReasonEnum captures the possible ways an LLM generation can complete.
 * </pre>
 *
 * Protobuf enum {@code llm.observability.v1.FinishReason}
 */
public enum FinishReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FINISH_REASON_UNSPECIFIED = 0;</code>
   */
  FINISH_REASON_UNSPECIFIED(0),
  /**
   * <code>FINISH_REASON_STOP = 1;</code>
   */
  FINISH_REASON_STOP(1),
  /**
   * <code>FINISH_REASON_LENGTH = 2;</code>
   */
  FINISH_REASON_LENGTH(2),
  /**
   * <code>FINISH_REASON_CONTENT_FILTER = 3;</code>
   */
  FINISH_REASON_CONTENT_FILTER(3),
  /**
   * <code>FINISH_REASON_TIMEOUT = 4;</code>
   */
  FINISH_REASON_TIMEOUT(4),
  /**
   * <code>FINISH_REASON_TOOL_CALLS = 5;</code>
   */
  FINISH_REASON_TOOL_CALLS(5),
  /**
   * <code>FINISH_REASON_CACHE_HIT = 6;</code>
   */
  FINISH_REASON_CACHE_HIT(6),
  /**
   * <code>FINISH_REASON_CLIENT_DISCONNECT = 7;</code>
   */
  FINISH_REASON_CLIENT_DISCONNECT(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FINISH_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int FINISH_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <code>FINISH_REASON_STOP = 1;</code>
   */
  public static final int FINISH_REASON_STOP_VALUE = 1;
  /**
   * <code>FINISH_REASON_LENGTH = 2;</code>
   */
  public static final int FINISH_REASON_LENGTH_VALUE = 2;
  /**
   * <code>FINISH_REASON_CONTENT_FILTER = 3;</code>
   */
  public static final int FINISH_REASON_CONTENT_FILTER_VALUE = 3;
  /**
   * <code>FINISH_REASON_TIMEOUT = 4;</code>
   */
  public static final int FINISH_REASON_TIMEOUT_VALUE = 4;
  /**
   * <code>FINISH_REASON_TOOL_CALLS = 5;</code>
   */
  public static final int FINISH_REASON_TOOL_CALLS_VALUE = 5;
  /**
   * <code>FINISH_REASON_CACHE_HIT = 6;</code>
   */
  public static final int FINISH_REASON_CACHE_HIT_VALUE = 6;
  /**
   * <code>FINISH_REASON_CLIENT_DISCONNECT = 7;</code>
   */
  public static final int FINISH_REASON_CLIENT_DISCONNECT_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FinishReason valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FinishReason forNumber(int value) {
    switch (value) {
      case 0: return FINISH_REASON_UNSPECIFIED;
      case 1: return FINISH_REASON_STOP;
      case 2: return FINISH_REASON_LENGTH;
      case 3: return FINISH_REASON_CONTENT_FILTER;
      case 4: return FINISH_REASON_TIMEOUT;
      case 5: return FINISH_REASON_TOOL_CALLS;
      case 6: return FINISH_REASON_CACHE_HIT;
      case 7: return FINISH_REASON_CLIENT_DISCONNECT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FinishReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FinishReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FinishReason>() {
          public FinishReason findValueByNumber(int number) {
            return FinishReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.llmobservability.platform.v1.SpanProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final FinishReason[] VALUES = values();

  public static FinishReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FinishReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:llm.observability.v1.FinishReason)
}

