// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface InitInstrumentationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.InitInstrumentationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1 [json_name = "serviceName"];</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1 [json_name = "serviceName"];</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string environment = 2 [json_name = "environment"];</code>
   * @return The environment.
   */
  java.lang.String getEnvironment();
  /**
   * <code>string environment = 2 [json_name = "environment"];</code>
   * @return The bytes for environment.
   */
  com.google.protobuf.ByteString
      getEnvironmentBytes();
}
