// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface InstrumentationEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.InstrumentationEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1 [json_name = "eventId"];</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1 [json_name = "eventId"];</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string timestamp_utc = 2 [json_name = "timestampUtc"];</code>
   * @return The timestampUtc.
   */
  java.lang.String getTimestampUtc();
  /**
   * <code>string timestamp_utc = 2 [json_name = "timestampUtc"];</code>
   * @return The bytes for timestampUtc.
   */
  com.google.protobuf.ByteString
      getTimestampUtcBytes();

  /**
   * <code>string service_name = 3 [json_name = "serviceName"];</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 3 [json_name = "serviceName"];</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>.llm.observability.v1.InstrumentationStatus action = 4 [json_name = "action"];</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.llm.observability.v1.InstrumentationStatus action = 4 [json_name = "action"];</code>
   * @return The action.
   */
  com.llmobservability.platform.v1.InstrumentationStatus getAction();

  /**
   * <pre>
   * JSON blob for extra details
   * </pre>
   *
   * <code>string metadata = 5 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  java.lang.String getMetadata();
  /**
   * <pre>
   * JSON blob for extra details
   * </pre>
   *
   * <code>string metadata = 5 [json_name = "metadata"];</code>
   * @return The bytes for metadata.
   */
  com.google.protobuf.ByteString
      getMetadataBytes();
}
