// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public final class InstrumentationProto {
  private InstrumentationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_InitInstrumentationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_InitInstrumentationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_DisableInstrumentationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_DisableInstrumentationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_GetStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_GetStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_DetectProviderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_DetectProviderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_DetectProviderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_DetectProviderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_TriggerTestCallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_TriggerTestCallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_TriggerTestStreamCallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_TriggerTestStreamCallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_InstrumentationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_InstrumentationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_InitInstrumentationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_InitInstrumentationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_DisableInstrumentationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_DisableInstrumentationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_GetStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_GetStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_TriggerTestCallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_TriggerTestCallResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_TriggerTestStreamCallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_TriggerTestStreamCallResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_InstrumentationEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_InstrumentationEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_CountTokensRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_CountTokensRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llm_observability_v1_CountTokensResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_llm_observability_v1_CountTokensResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*llm/observability/v1/instrumentation.p" +
      "roto\022\024llm.observability.v1\"a\n\032InitInstru" +
      "mentationRequest\022!\n\014service_name\030\001 \001(\tR\013" +
      "serviceName\022 \n\013environment\030\002 \001(\tR\013enviro" +
      "nment\"\037\n\035DisableInstrumentationRequest\"\022" +
      "\n\020GetStatusRequest\"=\n\025DetectProviderRequ" +
      "est\022\020\n\003url\030\001 \001(\tR\003url\022\022\n\004body\030\002 \001(\tR\004bod" +
      "y\"J\n\026DetectProviderResponse\022\032\n\010provider\030" +
      "\001 \001(\tR\010provider\022\024\n\005model\030\002 \001(\tR\005model\"L\n" +
      "\026TriggerTestCallRequest\022\026\n\006method\030\001 \001(\tR" +
      "\006method\022\032\n\010provider\030\002 \001(\tR\010provider\"R\n\034T" +
      "riggerTestStreamCallRequest\022\032\n\010provider\030" +
      "\001 \001(\tR\010provider\022\026\n\006chunks\030\002 \003(\tR\006chunks\"" +
      "\222\001\n\027InstrumentationResponse\022\030\n\007success\030\001" +
      " \001(\010R\007success\022\030\n\007message\030\002 \001(\tR\007message\022" +
      "C\n\006status\030\003 \001(\0162+.llm.observability.v1.I" +
      "nstrumentationStatusR\006status\"\226\001\n\033InitIns" +
      "trumentationResponse\022\030\n\007success\030\001 \001(\010R\007s" +
      "uccess\022\030\n\007message\030\002 \001(\tR\007message\022C\n\006stat" +
      "us\030\003 \001(\0162+.llm.observability.v1.Instrume" +
      "ntationStatusR\006status\"\231\001\n\036DisableInstrum" +
      "entationResponse\022\030\n\007success\030\001 \001(\010R\007succe" +
      "ss\022\030\n\007message\030\002 \001(\tR\007message\022C\n\006status\030\003" +
      " \001(\0162+.llm.observability.v1.Instrumentat" +
      "ionStatusR\006status\"\214\001\n\021GetStatusResponse\022" +
      "\030\n\007success\030\001 \001(\010R\007success\022\030\n\007message\030\002 \001" +
      "(\tR\007message\022C\n\006status\030\003 \001(\0162+.llm.observ" +
      "ability.v1.InstrumentationStatusR\006status" +
      "\"\222\001\n\027TriggerTestCallResponse\022\030\n\007success\030" +
      "\001 \001(\010R\007success\022\030\n\007message\030\002 \001(\tR\007message" +
      "\022C\n\006status\030\003 \001(\0162+.llm.observability.v1." +
      "InstrumentationStatusR\006status\"\230\001\n\035Trigge" +
      "rTestStreamCallResponse\022\030\n\007success\030\001 \001(\010" +
      "R\007success\022\030\n\007message\030\002 \001(\tR\007message\022C\n\006s" +
      "tatus\030\003 \001(\0162+.llm.observability.v1.Instr" +
      "umentationStatusR\006status\"\332\001\n\024Instrumenta" +
      "tionEvent\022\031\n\010event_id\030\001 \001(\tR\007eventId\022#\n\r" +
      "timestamp_utc\030\002 \001(\tR\014timestampUtc\022!\n\014ser" +
      "vice_name\030\003 \001(\tR\013serviceName\022C\n\006action\030\004" +
      " \001(\0162+.llm.observability.v1.Instrumentat" +
      "ionStatusR\006action\022\032\n\010metadata\030\005 \001(\tR\010met" +
      "adata\"^\n\022CountTokensRequest\022\026\n\006prompt\030\001 " +
      "\001(\tR\006prompt\022\024\n\005model\030\002 \001(\tR\005model\022\032\n\010pro" +
      "vider\030\003 \001(\tR\010provider\"E\n\023CountTokensResp" +
      "onse\022\026\n\006tokens\030\001 \001(\005R\006tokens\022\026\n\006method\030\002" +
      " \001(\tR\006method*\260\001\n\025InstrumentationStatus\022&" +
      "\n\"INSTRUMENTATION_STATUS_UNSPECIFIED\020\000\022&" +
      "\n\"INSTRUMENTATION_STATUS_INITIALIZED\020\001\022#" +
      "\n\037INSTRUMENTATION_STATUS_DISABLED\020\002\022\"\n\036I" +
      "NSTRUMENTATION_STATUS_PARTIAL\020\0032\303\006\n\035Inst" +
      "rumentationControlService\022z\n\023InitInstrum" +
      "entation\0220.llm.observability.v1.InitInst" +
      "rumentationRequest\0321.llm.observability.v" +
      "1.InitInstrumentationResponse\022\203\001\n\026Disabl" +
      "eInstrumentation\0223.llm.observability.v1." +
      "DisableInstrumentationRequest\0324.llm.obse" +
      "rvability.v1.DisableInstrumentationRespo" +
      "nse\022\\\n\tGetStatus\022&.llm.observability.v1." +
      "GetStatusRequest\032\'.llm.observability.v1." +
      "GetStatusResponse\022k\n\016DetectProvider\022+.ll" +
      "m.observability.v1.DetectProviderRequest" +
      "\032,.llm.observability.v1.DetectProviderRe" +
      "sponse\022n\n\017TriggerTestCall\022,.llm.observab" +
      "ility.v1.TriggerTestCallRequest\032-.llm.ob" +
      "servability.v1.TriggerTestCallResponse\022\200" +
      "\001\n\025TriggerTestStreamCall\0222.llm.observabi" +
      "lity.v1.TriggerTestStreamCallRequest\0323.l" +
      "lm.observability.v1.TriggerTestStreamCal" +
      "lResponse\022b\n\013CountTokens\022(.llm.observabi" +
      "lity.v1.CountTokensRequest\032).llm.observa" +
      "bility.v1.CountTokensResponseB\342\001\n com.ll" +
      "mobservability.platform.v1B\024Instrumentat" +
      "ionProtoP\001Z.github.com/llm-observability" +
      "/platform/proto/v1\242\002\003LOX\252\002\024Llm.Observabi" +
      "lity.V1\312\002\034LlmObservability\\Platform\\V1\342\002" +
      " Llm\\Observability\\V1\\GPBMetadata\352\002\026Llm:" +
      ":Observability::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_llm_observability_v1_InitInstrumentationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llm_observability_v1_InitInstrumentationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_InitInstrumentationRequest_descriptor,
        new java.lang.String[] { "ServiceName", "Environment", });
    internal_static_llm_observability_v1_DisableInstrumentationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_llm_observability_v1_DisableInstrumentationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_DisableInstrumentationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_llm_observability_v1_GetStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_llm_observability_v1_GetStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_GetStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_llm_observability_v1_DetectProviderRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_llm_observability_v1_DetectProviderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_DetectProviderRequest_descriptor,
        new java.lang.String[] { "Url", "Body", });
    internal_static_llm_observability_v1_DetectProviderResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_llm_observability_v1_DetectProviderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_DetectProviderResponse_descriptor,
        new java.lang.String[] { "Provider", "Model", });
    internal_static_llm_observability_v1_TriggerTestCallRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_llm_observability_v1_TriggerTestCallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_TriggerTestCallRequest_descriptor,
        new java.lang.String[] { "Method", "Provider", });
    internal_static_llm_observability_v1_TriggerTestStreamCallRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_llm_observability_v1_TriggerTestStreamCallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_TriggerTestStreamCallRequest_descriptor,
        new java.lang.String[] { "Provider", "Chunks", });
    internal_static_llm_observability_v1_InstrumentationResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_llm_observability_v1_InstrumentationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_InstrumentationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Status", });
    internal_static_llm_observability_v1_InitInstrumentationResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_llm_observability_v1_InitInstrumentationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_InitInstrumentationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Status", });
    internal_static_llm_observability_v1_DisableInstrumentationResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_llm_observability_v1_DisableInstrumentationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_DisableInstrumentationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Status", });
    internal_static_llm_observability_v1_GetStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_llm_observability_v1_GetStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_GetStatusResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Status", });
    internal_static_llm_observability_v1_TriggerTestCallResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_llm_observability_v1_TriggerTestCallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_TriggerTestCallResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Status", });
    internal_static_llm_observability_v1_TriggerTestStreamCallResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_llm_observability_v1_TriggerTestStreamCallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_TriggerTestStreamCallResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Status", });
    internal_static_llm_observability_v1_InstrumentationEvent_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_llm_observability_v1_InstrumentationEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_InstrumentationEvent_descriptor,
        new java.lang.String[] { "EventId", "TimestampUtc", "ServiceName", "Action", "Metadata", });
    internal_static_llm_observability_v1_CountTokensRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_llm_observability_v1_CountTokensRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_CountTokensRequest_descriptor,
        new java.lang.String[] { "Prompt", "Model", "Provider", });
    internal_static_llm_observability_v1_CountTokensResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_llm_observability_v1_CountTokensResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_llm_observability_v1_CountTokensResponse_descriptor,
        new java.lang.String[] { "Tokens", "Method", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
