// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: span.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface LLMSpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.LLMSpan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Generated before API call (UUID v4)
   * </pre>
   *
   * <code>string span_id = 1 [json_name = "spanId"];</code>
   * @return The spanId.
   */
  java.lang.String getSpanId();
  /**
   * <pre>
   * Generated before API call (UUID v4)
   * </pre>
   *
   * <code>string span_id = 1 [json_name = "spanId"];</code>
   * @return The bytes for spanId.
   */
  com.google.protobuf.ByteString
      getSpanIdBytes();

  /**
   * <pre>
   * Propagated from caller (UUID v4), nullable
   * </pre>
   *
   * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
   * @return Whether the traceId field is set.
   */
  boolean hasTraceId();
  /**
   * <pre>
   * Propagated from caller (UUID v4), nullable
   * </pre>
   *
   * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * Propagated from caller (UUID v4), nullable
   * </pre>
   *
   * <code>optional string trace_id = 2 [json_name = "traceId"];</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <pre>
   * For tool-call chains (UUID v4), nullable
   * </pre>
   *
   * <code>optional string parent_span_id = 3 [json_name = "parentSpanId"];</code>
   * @return Whether the parentSpanId field is set.
   */
  boolean hasParentSpanId();
  /**
   * <pre>
   * For tool-call chains (UUID v4), nullable
   * </pre>
   *
   * <code>optional string parent_span_id = 3 [json_name = "parentSpanId"];</code>
   * @return The parentSpanId.
   */
  java.lang.String getParentSpanId();
  /**
   * <pre>
   * For tool-call chains (UUID v4), nullable
   * </pre>
   *
   * <code>optional string parent_span_id = 3 [json_name = "parentSpanId"];</code>
   * @return The bytes for parentSpanId.
   */
  com.google.protobuf.ByteString
      getParentSpanIdBytes();

  /**
   * <pre>
   * Bump on breaking change. Hardcoded = 1
   * </pre>
   *
   * <code>int32 schema_version = 4 [json_name = "schemaVersion"];</code>
   * @return The schemaVersion.
   */
  int getSchemaVersion();

  /**
   * <pre>
   * SDK config ('gpt-4o', etc)
   * </pre>
   *
   * <code>string model = 5 [json_name = "model"];</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <pre>
   * SDK config ('gpt-4o', etc)
   * </pre>
   *
   * <code>string model = 5 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <pre>
   * SDK config ('openai', 'anthropic', etc)
   * </pre>
   *
   * <code>string provider = 6 [json_name = "provider"];</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <pre>
   * SDK config ('openai', 'anthropic', etc)
   * </pre>
   *
   * <code>string provider = 6 [json_name = "provider"];</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <pre>
   * SDK config ('checkout-service')
   * </pre>
   *
   * <code>string service_name = 7 [json_name = "serviceName"];</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <pre>
   * SDK config ('checkout-service')
   * </pre>
   *
   * <code>string service_name = 7 [json_name = "serviceName"];</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <pre>
   * SDK decorator arg ('/api/summarize')
   * </pre>
   *
   * <code>string endpoint = 8 [json_name = "endpoint"];</code>
   * @return The endpoint.
   */
  java.lang.String getEndpoint();
  /**
   * <pre>
   * SDK decorator arg ('/api/summarize')
   * </pre>
   *
   * <code>string endpoint = 8 [json_name = "endpoint"];</code>
   * @return The bytes for endpoint.
   */
  com.google.protobuf.ByteString
      getEndpointBytes();

  /**
   * <pre>
   * SDK config
   * </pre>
   *
   * <code>.llm.observability.v1.Environment environment = 9 [json_name = "environment"];</code>
   * @return The enum numeric value on the wire for environment.
   */
  int getEnvironmentValue();
  /**
   * <pre>
   * SDK config
   * </pre>
   *
   * <code>.llm.observability.v1.Environment environment = 9 [json_name = "environment"];</code>
   * @return The environment.
   */
  com.llmobservability.platform.v1.Environment getEnvironment();

  /**
   * <pre>
   * SDK call arg. Null for anonymous
   * </pre>
   *
   * <code>optional string user_id = 10 [json_name = "userId"];</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <pre>
   * SDK call arg. Null for anonymous
   * </pre>
   *
   * <code>optional string user_id = 10 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * SDK call arg. Null for anonymous
   * </pre>
   *
   * <code>optional string user_id = 10 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * SDK call arg. Null for stateless
   * </pre>
   *
   * <code>optional string session_id = 11 [json_name = "sessionId"];</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <pre>
   * SDK call arg. Null for stateless
   * </pre>
   *
   * <code>optional string session_id = 11 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * SDK call arg. Null for stateless
   * </pre>
   *
   * <code>optional string session_id = 11 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * Exact BPE count, &gt; 0
   * </pre>
   *
   * <code>int32 prompt_tokens = 12 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  int getPromptTokens();

  /**
   * <pre>
   * Exact BPE count, &gt;= 0
   * </pre>
   *
   * <code>int32 completion_tokens = 13 [json_name = "completionTokens"];</code>
   * @return The completionTokens.
   */
  int getCompletionTokens();

  /**
   * <pre>
   * Time to first chunk byte
   * </pre>
   *
   * <code>optional int32 latency_ms_ttft = 14 [json_name = "latencyMsTtft"];</code>
   * @return Whether the latencyMsTtft field is set.
   */
  boolean hasLatencyMsTtft();
  /**
   * <pre>
   * Time to first chunk byte
   * </pre>
   *
   * <code>optional int32 latency_ms_ttft = 14 [json_name = "latencyMsTtft"];</code>
   * @return The latencyMsTtft.
   */
  int getLatencyMsTtft();

  /**
   * <pre>
   * Full wall clock, &gt; 0
   * </pre>
   *
   * <code>int32 latency_ms_total = 15 [json_name = "latencyMsTotal"];</code>
   * @return The latencyMsTotal.
   */
  int getLatencyMsTotal();

  /**
   * <pre>
   * Provider response finish reason
   * </pre>
   *
   * <code>.llm.observability.v1.FinishReason finish_reason = 16 [json_name = "finishReason"];</code>
   * @return The enum numeric value on the wire for finishReason.
   */
  int getFinishReasonValue();
  /**
   * <pre>
   * Provider response finish reason
   * </pre>
   *
   * <code>.llm.observability.v1.FinishReason finish_reason = 16 [json_name = "finishReason"];</code>
   * @return The finishReason.
   */
  com.llmobservability.platform.v1.FinishReason getFinishReason();

  /**
   * <pre>
   * SDK computed cost in micro-USD, &gt;= 0
   * </pre>
   *
   * <code>int64 cost_usd_micro = 17 [json_name = "costUsdMicro"];</code>
   * @return The costUsdMicro.
   */
  long getCostUsdMicro();

  /**
   * <pre>
   * SDK config price version date
   * </pre>
   *
   * <code>string price_version = 18 [json_name = "priceVersion"];</code>
   * @return The priceVersion.
   */
  java.lang.String getPriceVersion();
  /**
   * <pre>
   * SDK config price version date
   * </pre>
   *
   * <code>string price_version = 18 [json_name = "priceVersion"];</code>
   * @return The bytes for priceVersion.
   */
  com.google.protobuf.ByteString
      getPriceVersionBytes();

  /**
   * <pre>
   * SDK token method
   * </pre>
   *
   * <code>.llm.observability.v1.TokenCountMethod token_count_method = 19 [json_name = "tokenCountMethod"];</code>
   * @return The enum numeric value on the wire for tokenCountMethod.
   */
  int getTokenCountMethodValue();
  /**
   * <pre>
   * SDK token method
   * </pre>
   *
   * <code>.llm.observability.v1.TokenCountMethod token_count_method = 19 [json_name = "tokenCountMethod"];</code>
   * @return The tokenCountMethod.
   */
  com.llmobservability.platform.v1.TokenCountMethod getTokenCountMethod();

  /**
   * <pre>
   * TRUE if hash(span_id) % 100 == 0
   * </pre>
   *
   * <code>bool is_sampled = 20 [json_name = "isSampled"];</code>
   * @return The isSampled.
   */
  boolean getIsSampled();

  /**
   * <pre>
   * 0 for first-attempt calls
   * </pre>
   *
   * <code>int32 retry_count = 21 [json_name = "retryCount"];</code>
   * @return The retryCount.
   */
  int getRetryCount();

  /**
   * <pre>
   * Fallback chains
   * </pre>
   *
   * <code>repeated string attempted_models = 22 [json_name = "attemptedModels"];</code>
   * @return A list containing the attemptedModels.
   */
  java.util.List<java.lang.String>
      getAttemptedModelsList();
  /**
   * <pre>
   * Fallback chains
   * </pre>
   *
   * <code>repeated string attempted_models = 22 [json_name = "attemptedModels"];</code>
   * @return The count of attemptedModels.
   */
  int getAttemptedModelsCount();
  /**
   * <pre>
   * Fallback chains
   * </pre>
   *
   * <code>repeated string attempted_models = 22 [json_name = "attemptedModels"];</code>
   * @param index The index of the element to return.
   * @return The attemptedModels at the given index.
   */
  java.lang.String getAttemptedModels(int index);
  /**
   * <pre>
   * Fallback chains
   * </pre>
   *
   * <code>repeated string attempted_models = 22 [json_name = "attemptedModels"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the attemptedModels at the given index.
   */
  com.google.protobuf.ByteString
      getAttemptedModelsBytes(int index);

  /**
   * <pre>
   * Aho-Corasick computed inline before emit
   * </pre>
   *
   * <code>bool pii_detected = 23 [json_name = "piiDetected"];</code>
   * @return The piiDetected.
   */
  boolean getPiiDetected();

  /**
   * <pre>
   * Aho-Corasick jailbreak/injection pattern matched
   * </pre>
   *
   * <code>bool injection_attempt = 24 [json_name = "injectionAttempt"];</code>
   * @return The injectionAttempt.
   */
  boolean getInjectionAttempt();

  /**
   * <pre>
   * SDK (client clock) UTC, ISO 8601 string or Unix nanoseconds.
   * </pre>
   *
   * <code>string timestamp_utc = 25 [json_name = "timestampUtc"];</code>
   * @return The timestampUtc.
   */
  java.lang.String getTimestampUtc();
  /**
   * <pre>
   * SDK (client clock) UTC, ISO 8601 string or Unix nanoseconds.
   * </pre>
   *
   * <code>string timestamp_utc = 25 [json_name = "timestampUtc"];</code>
   * @return The bytes for timestampUtc.
   */
  com.google.protobuf.ByteString
      getTimestampUtcBytes();

  /**
   * <pre>
   * SAMPLED-ONLY FIELDS
   * SHA256(prompt_text) 64-char hex. Null if pii_detected.
   * </pre>
   *
   * <code>optional string prompt_hash = 26 [json_name = "promptHash"];</code>
   * @return Whether the promptHash field is set.
   */
  boolean hasPromptHash();
  /**
   * <pre>
   * SAMPLED-ONLY FIELDS
   * SHA256(prompt_text) 64-char hex. Null if pii_detected.
   * </pre>
   *
   * <code>optional string prompt_hash = 26 [json_name = "promptHash"];</code>
   * @return The promptHash.
   */
  java.lang.String getPromptHash();
  /**
   * <pre>
   * SAMPLED-ONLY FIELDS
   * SHA256(prompt_text) 64-char hex. Null if pii_detected.
   * </pre>
   *
   * <code>optional string prompt_hash = 26 [json_name = "promptHash"];</code>
   * @return The bytes for promptHash.
   */
  com.google.protobuf.ByteString
      getPromptHashBytes();

  /**
   * <pre>
   * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
   * </pre>
   *
   * <code>repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];</code>
   * @return A list containing the promptEmbedding.
   */
  java.util.List<java.lang.Float> getPromptEmbeddingList();
  /**
   * <pre>
   * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
   * </pre>
   *
   * <code>repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];</code>
   * @return The count of promptEmbedding.
   */
  int getPromptEmbeddingCount();
  /**
   * <pre>
   * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
   * </pre>
   *
   * <code>repeated float prompt_embedding = 27 [json_name = "promptEmbedding"];</code>
   * @param index The index of the element to return.
   * @return The promptEmbedding at the given index.
   */
  float getPromptEmbedding(int index);

  /**
   * <pre>
   * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
   * </pre>
   *
   * <code>repeated float response_embedding = 28 [json_name = "responseEmbedding"];</code>
   * @return A list containing the responseEmbedding.
   */
  java.util.List<java.lang.Float> getResponseEmbeddingList();
  /**
   * <pre>
   * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
   * </pre>
   *
   * <code>repeated float response_embedding = 28 [json_name = "responseEmbedding"];</code>
   * @return The count of responseEmbedding.
   */
  int getResponseEmbeddingCount();
  /**
   * <pre>
   * MiniLM-L6-v2 384-dim vector. Null if pii_detected.
   * </pre>
   *
   * <code>repeated float response_embedding = 28 [json_name = "responseEmbedding"];</code>
   * @param index The index of the element to return.
   * @return The responseEmbedding at the given index.
   */
  float getResponseEmbedding(int index);
}
