// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface ModelPriceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.ModelPriceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model = 1 [json_name = "model"];</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 1 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string provider = 2 [json_name = "provider"];</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <code>string provider = 2 [json_name = "provider"];</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <code>double input_price_per_1m = 3 [json_name = "inputPricePer1m"];</code>
   * @return The inputPricePer1m.
   */
  double getInputPricePer1M();

  /**
   * <code>double output_price_per_1m = 4 [json_name = "outputPricePer1m"];</code>
   * @return The outputPricePer1m.
   */
  double getOutputPricePer1M();

  /**
   * <code>string version = 5 [json_name = "version"];</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 5 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
