// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/span.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface RecordSpanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.RecordSpanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.llm.observability.v1.LLMSpan span = 1 [json_name = "span"];</code>
   * @return Whether the span field is set.
   */
  boolean hasSpan();
  /**
   * <code>.llm.observability.v1.LLMSpan span = 1 [json_name = "span"];</code>
   * @return The span.
   */
  com.llmobservability.platform.v1.LLMSpan getSpan();
  /**
   * <code>.llm.observability.v1.LLMSpan span = 1 [json_name = "span"];</code>
   */
  com.llmobservability.platform.v1.LLMSpanOrBuilder getSpanOrBuilder();
}
