// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface RecordMetricsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.RecordMetricsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model = 1 [json_name = "model"];</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 1 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string provider = 2 [json_name = "provider"];</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <code>string provider = 2 [json_name = "provider"];</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <code>string service_name = 3 [json_name = "serviceName"];</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 3 [json_name = "serviceName"];</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>optional int32 prompt_tokens = 4 [json_name = "promptTokens"];</code>
   * @return Whether the promptTokens field is set.
   */
  boolean hasPromptTokens();
  /**
   * <code>optional int32 prompt_tokens = 4 [json_name = "promptTokens"];</code>
   * @return The promptTokens.
   */
  int getPromptTokens();

  /**
   * <code>optional int32 completion_tokens = 5 [json_name = "completionTokens"];</code>
   * @return Whether the completionTokens field is set.
   */
  boolean hasCompletionTokens();
  /**
   * <code>optional int32 completion_tokens = 5 [json_name = "completionTokens"];</code>
   * @return The completionTokens.
   */
  int getCompletionTokens();

  /**
   * <code>optional int64 cost_usd_micro = 6 [json_name = "costUsdMicro"];</code>
   * @return Whether the costUsdMicro field is set.
   */
  boolean hasCostUsdMicro();
  /**
   * <code>optional int64 cost_usd_micro = 6 [json_name = "costUsdMicro"];</code>
   * @return The costUsdMicro.
   */
  long getCostUsdMicro();

  /**
   * <code>optional int32 latency_ms_total = 7 [json_name = "latencyMsTotal"];</code>
   * @return Whether the latencyMsTotal field is set.
   */
  boolean hasLatencyMsTotal();
  /**
   * <code>optional int32 latency_ms_total = 7 [json_name = "latencyMsTotal"];</code>
   * @return The latencyMsTotal.
   */
  int getLatencyMsTotal();

  /**
   * <code>optional int32 latency_ms_ttft = 8 [json_name = "latencyMsTtft"];</code>
   * @return Whether the latencyMsTtft field is set.
   */
  boolean hasLatencyMsTtft();
  /**
   * <code>optional int32 latency_ms_ttft = 8 [json_name = "latencyMsTtft"];</code>
   * @return The latencyMsTtft.
   */
  int getLatencyMsTtft();

  /**
   * <code>optional string finish_reason = 9 [json_name = "finishReason"];</code>
   * @return Whether the finishReason field is set.
   */
  boolean hasFinishReason();
  /**
   * <code>optional string finish_reason = 9 [json_name = "finishReason"];</code>
   * @return The finishReason.
   */
  java.lang.String getFinishReason();
  /**
   * <code>optional string finish_reason = 9 [json_name = "finishReason"];</code>
   * @return The bytes for finishReason.
   */
  com.google.protobuf.ByteString
      getFinishReasonBytes();

  /**
   * <code>string status = 10 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 10 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>bool pii_detected = 11 [json_name = "piiDetected"];</code>
   * @return The piiDetected.
   */
  boolean getPiiDetected();

  /**
   * <code>bool injection_attempt = 12 [json_name = "injectionAttempt"];</code>
   * @return The injectionAttempt.
   */
  boolean getInjectionAttempt();

  /**
   * <code>int32 retry_count = 13 [json_name = "retryCount"];</code>
   * @return The retryCount.
   */
  int getRetryCount();
}
