// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

/**
 * Protobuf type {@code llm.observability.v1.RecordMetricsResponse}
 */
public final class RecordMetricsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:llm.observability.v1.RecordMetricsResponse)
    RecordMetricsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecordMetricsResponse.newBuilder() to construct.
  private RecordMetricsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecordMetricsResponse() {
    priceVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecordMetricsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_RecordMetricsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_RecordMetricsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.llmobservability.platform.v1.RecordMetricsResponse.class, com.llmobservability.platform.v1.RecordMetricsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RECORDED_FIELD_NUMBER = 1;
  private boolean recorded_ = false;
  /**
   * <code>bool recorded = 1 [json_name = "recorded"];</code>
   * @return The recorded.
   */
  @java.lang.Override
  public boolean getRecorded() {
    return recorded_;
  }

  public static final int COST_USD_MICRO_FIELD_NUMBER = 2;
  private long costUsdMicro_ = 0L;
  /**
   * <code>optional int64 cost_usd_micro = 2 [json_name = "costUsdMicro"];</code>
   * @return Whether the costUsdMicro field is set.
   */
  @java.lang.Override
  public boolean hasCostUsdMicro() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 cost_usd_micro = 2 [json_name = "costUsdMicro"];</code>
   * @return The costUsdMicro.
   */
  @java.lang.Override
  public long getCostUsdMicro() {
    return costUsdMicro_;
  }

  public static final int PRICE_VERSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object priceVersion_ = "";
  /**
   * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
   * @return Whether the priceVersion field is set.
   */
  @java.lang.Override
  public boolean hasPriceVersion() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
   * @return The priceVersion.
   */
  @java.lang.Override
  public java.lang.String getPriceVersion() {
    java.lang.Object ref = priceVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      priceVersion_ = s;
      return s;
    }
  }
  /**
   * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
   * @return The bytes for priceVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPriceVersionBytes() {
    java.lang.Object ref = priceVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      priceVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (recorded_ != false) {
      output.writeBool(1, recorded_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(2, costUsdMicro_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, priceVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (recorded_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, recorded_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, costUsdMicro_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, priceVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.llmobservability.platform.v1.RecordMetricsResponse)) {
      return super.equals(obj);
    }
    com.llmobservability.platform.v1.RecordMetricsResponse other = (com.llmobservability.platform.v1.RecordMetricsResponse) obj;

    if (getRecorded()
        != other.getRecorded()) return false;
    if (hasCostUsdMicro() != other.hasCostUsdMicro()) return false;
    if (hasCostUsdMicro()) {
      if (getCostUsdMicro()
          != other.getCostUsdMicro()) return false;
    }
    if (hasPriceVersion() != other.hasPriceVersion()) return false;
    if (hasPriceVersion()) {
      if (!getPriceVersion()
          .equals(other.getPriceVersion())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECORDED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRecorded());
    if (hasCostUsdMicro()) {
      hash = (37 * hash) + COST_USD_MICRO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCostUsdMicro());
    }
    if (hasPriceVersion()) {
      hash = (37 * hash) + PRICE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getPriceVersion().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.llmobservability.platform.v1.RecordMetricsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.llmobservability.platform.v1.RecordMetricsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.llmobservability.platform.v1.RecordMetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.llmobservability.platform.v1.RecordMetricsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code llm.observability.v1.RecordMetricsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:llm.observability.v1.RecordMetricsResponse)
      com.llmobservability.platform.v1.RecordMetricsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_RecordMetricsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_RecordMetricsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.llmobservability.platform.v1.RecordMetricsResponse.class, com.llmobservability.platform.v1.RecordMetricsResponse.Builder.class);
    }

    // Construct using com.llmobservability.platform.v1.RecordMetricsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recorded_ = false;
      costUsdMicro_ = 0L;
      priceVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_RecordMetricsResponse_descriptor;
    }

    @java.lang.Override
    public com.llmobservability.platform.v1.RecordMetricsResponse getDefaultInstanceForType() {
      return com.llmobservability.platform.v1.RecordMetricsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.llmobservability.platform.v1.RecordMetricsResponse build() {
      com.llmobservability.platform.v1.RecordMetricsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.llmobservability.platform.v1.RecordMetricsResponse buildPartial() {
      com.llmobservability.platform.v1.RecordMetricsResponse result = new com.llmobservability.platform.v1.RecordMetricsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.llmobservability.platform.v1.RecordMetricsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.recorded_ = recorded_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.costUsdMicro_ = costUsdMicro_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.priceVersion_ = priceVersion_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.llmobservability.platform.v1.RecordMetricsResponse) {
        return mergeFrom((com.llmobservability.platform.v1.RecordMetricsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.llmobservability.platform.v1.RecordMetricsResponse other) {
      if (other == com.llmobservability.platform.v1.RecordMetricsResponse.getDefaultInstance()) return this;
      if (other.getRecorded() != false) {
        setRecorded(other.getRecorded());
      }
      if (other.hasCostUsdMicro()) {
        setCostUsdMicro(other.getCostUsdMicro());
      }
      if (other.hasPriceVersion()) {
        priceVersion_ = other.priceVersion_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              recorded_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              costUsdMicro_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              priceVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean recorded_ ;
    /**
     * <code>bool recorded = 1 [json_name = "recorded"];</code>
     * @return The recorded.
     */
    @java.lang.Override
    public boolean getRecorded() {
      return recorded_;
    }
    /**
     * <code>bool recorded = 1 [json_name = "recorded"];</code>
     * @param value The recorded to set.
     * @return This builder for chaining.
     */
    public Builder setRecorded(boolean value) {

      recorded_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool recorded = 1 [json_name = "recorded"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRecorded() {
      bitField0_ = (bitField0_ & ~0x00000001);
      recorded_ = false;
      onChanged();
      return this;
    }

    private long costUsdMicro_ ;
    /**
     * <code>optional int64 cost_usd_micro = 2 [json_name = "costUsdMicro"];</code>
     * @return Whether the costUsdMicro field is set.
     */
    @java.lang.Override
    public boolean hasCostUsdMicro() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 cost_usd_micro = 2 [json_name = "costUsdMicro"];</code>
     * @return The costUsdMicro.
     */
    @java.lang.Override
    public long getCostUsdMicro() {
      return costUsdMicro_;
    }
    /**
     * <code>optional int64 cost_usd_micro = 2 [json_name = "costUsdMicro"];</code>
     * @param value The costUsdMicro to set.
     * @return This builder for chaining.
     */
    public Builder setCostUsdMicro(long value) {

      costUsdMicro_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 cost_usd_micro = 2 [json_name = "costUsdMicro"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCostUsdMicro() {
      bitField0_ = (bitField0_ & ~0x00000002);
      costUsdMicro_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object priceVersion_ = "";
    /**
     * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
     * @return Whether the priceVersion field is set.
     */
    public boolean hasPriceVersion() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
     * @return The priceVersion.
     */
    public java.lang.String getPriceVersion() {
      java.lang.Object ref = priceVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
     * @return The bytes for priceVersion.
     */
    public com.google.protobuf.ByteString
        getPriceVersionBytes() {
      java.lang.Object ref = priceVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
     * @param value The priceVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPriceVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      priceVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceVersion() {
      priceVersion_ = getDefaultInstance().getPriceVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string price_version = 3 [json_name = "priceVersion"];</code>
     * @param value The bytes for priceVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPriceVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      priceVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:llm.observability.v1.RecordMetricsResponse)
  }

  // @@protoc_insertion_point(class_scope:llm.observability.v1.RecordMetricsResponse)
  private static final com.llmobservability.platform.v1.RecordMetricsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.llmobservability.platform.v1.RecordMetricsResponse();
  }

  public static com.llmobservability.platform.v1.RecordMetricsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordMetricsResponse>
      PARSER = new com.google.protobuf.AbstractParser<RecordMetricsResponse>() {
    @java.lang.Override
    public RecordMetricsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecordMetricsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordMetricsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.llmobservability.platform.v1.RecordMetricsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

