// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

/**
 * Protobuf type {@code llm.observability.v1.TrackFallbackResponse}
 */
public final class TrackFallbackResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:llm.observability.v1.TrackFallbackResponse)
    TrackFallbackResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrackFallbackResponse.newBuilder() to construct.
  private TrackFallbackResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrackFallbackResponse() {
    attemptedModels_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrackFallbackResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_TrackFallbackResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_TrackFallbackResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.llmobservability.platform.v1.TrackFallbackResponse.class, com.llmobservability.platform.v1.TrackFallbackResponse.Builder.class);
  }

  public static final int RETRY_COUNT_FIELD_NUMBER = 1;
  private int retryCount_ = 0;
  /**
   * <code>int32 retry_count = 1 [json_name = "retryCount"];</code>
   * @return The retryCount.
   */
  @java.lang.Override
  public int getRetryCount() {
    return retryCount_;
  }

  public static final int ATTEMPTED_MODELS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList attemptedModels_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
   * @return A list containing the attemptedModels.
   */
  public com.google.protobuf.ProtocolStringList
      getAttemptedModelsList() {
    return attemptedModels_;
  }
  /**
   * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
   * @return The count of attemptedModels.
   */
  public int getAttemptedModelsCount() {
    return attemptedModels_.size();
  }
  /**
   * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
   * @param index The index of the element to return.
   * @return The attemptedModels at the given index.
   */
  public java.lang.String getAttemptedModels(int index) {
    return attemptedModels_.get(index);
  }
  /**
   * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the attemptedModels at the given index.
   */
  public com.google.protobuf.ByteString
      getAttemptedModelsBytes(int index) {
    return attemptedModels_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (retryCount_ != 0) {
      output.writeInt32(1, retryCount_);
    }
    for (int i = 0; i < attemptedModels_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, attemptedModels_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (retryCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, retryCount_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < attemptedModels_.size(); i++) {
        dataSize += computeStringSizeNoTag(attemptedModels_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAttemptedModelsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.llmobservability.platform.v1.TrackFallbackResponse)) {
      return super.equals(obj);
    }
    com.llmobservability.platform.v1.TrackFallbackResponse other = (com.llmobservability.platform.v1.TrackFallbackResponse) obj;

    if (getRetryCount()
        != other.getRetryCount()) return false;
    if (!getAttemptedModelsList()
        .equals(other.getAttemptedModelsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RETRY_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRetryCount();
    if (getAttemptedModelsCount() > 0) {
      hash = (37 * hash) + ATTEMPTED_MODELS_FIELD_NUMBER;
      hash = (53 * hash) + getAttemptedModelsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.llmobservability.platform.v1.TrackFallbackResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.llmobservability.platform.v1.TrackFallbackResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.llmobservability.platform.v1.TrackFallbackResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.llmobservability.platform.v1.TrackFallbackResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code llm.observability.v1.TrackFallbackResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:llm.observability.v1.TrackFallbackResponse)
      com.llmobservability.platform.v1.TrackFallbackResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_TrackFallbackResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_TrackFallbackResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.llmobservability.platform.v1.TrackFallbackResponse.class, com.llmobservability.platform.v1.TrackFallbackResponse.Builder.class);
    }

    // Construct using com.llmobservability.platform.v1.TrackFallbackResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      retryCount_ = 0;
      attemptedModels_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.llmobservability.platform.v1.InstrumentationProto.internal_static_llm_observability_v1_TrackFallbackResponse_descriptor;
    }

    @java.lang.Override
    public com.llmobservability.platform.v1.TrackFallbackResponse getDefaultInstanceForType() {
      return com.llmobservability.platform.v1.TrackFallbackResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.llmobservability.platform.v1.TrackFallbackResponse build() {
      com.llmobservability.platform.v1.TrackFallbackResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.llmobservability.platform.v1.TrackFallbackResponse buildPartial() {
      com.llmobservability.platform.v1.TrackFallbackResponse result = new com.llmobservability.platform.v1.TrackFallbackResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.llmobservability.platform.v1.TrackFallbackResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.retryCount_ = retryCount_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        attemptedModels_.makeImmutable();
        result.attemptedModels_ = attemptedModels_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.llmobservability.platform.v1.TrackFallbackResponse) {
        return mergeFrom((com.llmobservability.platform.v1.TrackFallbackResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.llmobservability.platform.v1.TrackFallbackResponse other) {
      if (other == com.llmobservability.platform.v1.TrackFallbackResponse.getDefaultInstance()) return this;
      if (other.getRetryCount() != 0) {
        setRetryCount(other.getRetryCount());
      }
      if (!other.attemptedModels_.isEmpty()) {
        if (attemptedModels_.isEmpty()) {
          attemptedModels_ = other.attemptedModels_;
          bitField0_ |= 0x00000002;
        } else {
          ensureAttemptedModelsIsMutable();
          attemptedModels_.addAll(other.attemptedModels_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              retryCount_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAttemptedModelsIsMutable();
              attemptedModels_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int retryCount_ ;
    /**
     * <code>int32 retry_count = 1 [json_name = "retryCount"];</code>
     * @return The retryCount.
     */
    @java.lang.Override
    public int getRetryCount() {
      return retryCount_;
    }
    /**
     * <code>int32 retry_count = 1 [json_name = "retryCount"];</code>
     * @param value The retryCount to set.
     * @return This builder for chaining.
     */
    public Builder setRetryCount(int value) {

      retryCount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 retry_count = 1 [json_name = "retryCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      retryCount_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList attemptedModels_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAttemptedModelsIsMutable() {
      if (!attemptedModels_.isModifiable()) {
        attemptedModels_ = new com.google.protobuf.LazyStringArrayList(attemptedModels_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @return A list containing the attemptedModels.
     */
    public com.google.protobuf.ProtocolStringList
        getAttemptedModelsList() {
      attemptedModels_.makeImmutable();
      return attemptedModels_;
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @return The count of attemptedModels.
     */
    public int getAttemptedModelsCount() {
      return attemptedModels_.size();
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @param index The index of the element to return.
     * @return The attemptedModels at the given index.
     */
    public java.lang.String getAttemptedModels(int index) {
      return attemptedModels_.get(index);
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the attemptedModels at the given index.
     */
    public com.google.protobuf.ByteString
        getAttemptedModelsBytes(int index) {
      return attemptedModels_.getByteString(index);
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @param index The index to set the value at.
     * @param value The attemptedModels to set.
     * @return This builder for chaining.
     */
    public Builder setAttemptedModels(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAttemptedModelsIsMutable();
      attemptedModels_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @param value The attemptedModels to add.
     * @return This builder for chaining.
     */
    public Builder addAttemptedModels(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAttemptedModelsIsMutable();
      attemptedModels_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @param values The attemptedModels to add.
     * @return This builder for chaining.
     */
    public Builder addAllAttemptedModels(
        java.lang.Iterable<java.lang.String> values) {
      ensureAttemptedModelsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, attemptedModels_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAttemptedModels() {
      attemptedModels_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attempted_models = 2 [json_name = "attemptedModels"];</code>
     * @param value The bytes of the attemptedModels to add.
     * @return This builder for chaining.
     */
    public Builder addAttemptedModelsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAttemptedModelsIsMutable();
      attemptedModels_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:llm.observability.v1.TrackFallbackResponse)
  }

  // @@protoc_insertion_point(class_scope:llm.observability.v1.TrackFallbackResponse)
  private static final com.llmobservability.platform.v1.TrackFallbackResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.llmobservability.platform.v1.TrackFallbackResponse();
  }

  public static com.llmobservability.platform.v1.TrackFallbackResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrackFallbackResponse>
      PARSER = new com.google.protobuf.AbstractParser<TrackFallbackResponse>() {
    @java.lang.Override
    public TrackFallbackResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TrackFallbackResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrackFallbackResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.llmobservability.platform.v1.TrackFallbackResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

