// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface TrackFallbackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.TrackFallbackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trace_id = 1 [json_name = "traceId"];</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string trace_id = 1 [json_name = "traceId"];</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2 [json_name = "model"];</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();
}
