// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm/observability/v1/instrumentation.proto

// Protobuf Java Version: 3.25.1
package com.llmobservability.platform.v1;

public interface TriggerTestStreamCallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:llm.observability.v1.TriggerTestStreamCallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string provider = 1 [json_name = "provider"];</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <code>string provider = 1 [json_name = "provider"];</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <code>repeated string chunks = 2 [json_name = "chunks"];</code>
   * @return A list containing the chunks.
   */
  java.util.List<java.lang.String>
      getChunksList();
  /**
   * <code>repeated string chunks = 2 [json_name = "chunks"];</code>
   * @return The count of chunks.
   */
  int getChunksCount();
  /**
   * <code>repeated string chunks = 2 [json_name = "chunks"];</code>
   * @param index The index of the element to return.
   * @return The chunks at the given index.
   */
  java.lang.String getChunks(int index);
  /**
   * <code>repeated string chunks = 2 [json_name = "chunks"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the chunks at the given index.
   */
  com.google.protobuf.ByteString
      getChunksBytes(int index);
}
