#!/usr/bin/env bash

# ==============================================================================
# Service Discovery Docker Controller Script
# Location: packages/configs/llm-obs-infra/scripts/discovery/run-service-discovery.sh
# ==============================================================================

set -euo pipefail

# Color Codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REGISTRY_URL="http://localhost:31426"

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

get_compose_cmd() {
    if docker compose version &> /dev/null; then
        echo "docker compose"
    elif command -v docker-compose &> /dev/null; then
        echo "docker-compose"
    else
        log_error "Neither 'docker compose' nor 'docker-compose' was found."
        exit 1
    fi
}

start_service_registry() {
    log_info "Ensuring 'llmobs-network' Docker network exists..."
    docker network create llmobs-network 2>/dev/null || true

    log_info "Navigating to package directory: ${INFRA_ROOT}"
    cd "${INFRA_ROOT}"

    COMPOSE_CMD=$(get_compose_cmd)
    log_info "Executing: ${COMPOSE_CMD} up -d llmobs-service-registry"
    ${COMPOSE_CMD} up -d --build llmobs-service-registry

    log_info "Waiting for Service Registry to become healthy on port 31426..."
    local retries=15
    while [ $retries -gt 0 ]; do
        if curl -s "${REGISTRY_URL}/health" | grep -q '"status"'; then
            log_success "llmobs-service-registry is ONLINE at ${REGISTRY_URL}"
            break
        fi
        sleep 1
        ((retries--))
    done

    if [ $retries -eq 0 ]; then
        log_warn "Health check timed out. Showing container logs:"
        ${COMPOSE_CMD} logs --tail=25 llmobs-service-registry
        exit 1
    fi

    show_status
}

show_status() {
    log_info "Fetching Active Services from Registry (${REGISTRY_URL}/v1/services)..."
    echo -e "${CYAN}----------------------------------------------------------------------${NC}"
    if curl -s "${REGISTRY_URL}/v1/services" | grep -q '"success"'; then
        curl -s "${REGISTRY_URL}/v1/services" | tr -d '\r'
    else
        log_warn "Service Registry is offline or returned no services."
    fi
    echo -e "\n${CYAN}----------------------------------------------------------------------${NC}"
}

search_service() {
    local target="${1:-}"
    if [ -z "$target" ]; then
        log_error "Usage: $0 search <service_name> (e.g. $0 search clickhouse)"
        exit 1
    fi

    log_info "Resolving active endpoint for service '${target}'..."
    echo -e "${CYAN}----------------------------------------------------------------------${NC}"
    curl -s "${REGISTRY_URL}/v1/resolve?service=${target}"
    echo -e "\n${CYAN}----------------------------------------------------------------------${NC}"
}

register_service() {
    local name="${1:-custom-service}"
    local port="${2:-8080}"
    local host="${3:-localhost}"

    log_info "Registering service '${name}' on ${host}:${port}..."
    curl -s -X POST "${REGISTRY_URL}/v1/register" \
      -H "Content-Type: application/json" \
      -d "{
        \"name\": \"${name}\",
        \"host\": \"${host}\",
        \"port\": ${port},
        \"protocol\": \"http\",
        \"healthCheck\": {
          \"protocol\": \"http\",
          \"path\": \"/health\"
        }
      }"
    echo ""
    log_success "Registered '${name}'! Traefik exporter triggered dynamic reconciliation."
    search_service "${name}"
}

view_traefik_dynamic_config() {
    log_info "Reading Dynamic Traefik Configuration generated by Service Discovery..."
    cd "${INFRA_ROOT}"
    COMPOSE_CMD=$(get_compose_cmd)
    echo -e "${MAGENTA}----------------------------------------------------------------------${NC}"
    ${COMPOSE_CMD} exec -T llmobs-service-registry cat /etc/traefik/dynamic/discovery.yml 2>/dev/null || \
      cat "${INFRA_ROOT}/config/traefik/dynamic/discovery.yml" 2>/dev/null || \
      log_warn "discovery.yml has not been generated yet."
    echo -e "\n${MAGENTA}----------------------------------------------------------------------${NC}"
}

show_logs() {
    cd "${INFRA_ROOT}"
    COMPOSE_CMD=$(get_compose_cmd)
    ${COMPOSE_CMD} logs -f --tail=50 llmobs-service-registry
}

stop_service_registry() {
    log_info "Stopping llmobs-service-registry container..."
    cd "${INFRA_ROOT}"
    COMPOSE_CMD=$(get_compose_cmd)
    ${COMPOSE_CMD} stop llmobs-service-registry
    log_success "Container stopped."
}

usage() {
    echo -e "${CYAN}======================================================================${NC}"
    echo -e "${GREEN} LLMObs Service Discovery Docker Controller ${NC}"
    echo -e "${CYAN}======================================================================${NC}"
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  start                        Run 'docker compose up -d llmobs-service-registry'"
    echo "  status                       List all active registered services in memory"
    echo "  search <name>                Search and resolve service (e.g. clickhouse, redis, grafana)"
    echo "  register <name> <port>       Dynamically register a new service/device"
    echo "  traefik-config               View live generated Traefik discovery.yml dynamic config"
    echo "  logs                         Follow live logs for llmobs-service-registry"
    echo "  stop                         Stop the llmobs-service-registry container"
    echo ""
}

case "${1:-}" in
    start)
        start_service_registry
        ;;
    status)
        show_status
        ;;
    search)
        search_service "${2:-}"
        ;;
    register)
        register_service "${2:-}" "${3:-8080}" "${4:-localhost}"
        ;;
    traefik-config)
        view_traefik_dynamic_config
        ;;
    logs)
        show_logs
        ;;
    stop)
        stop_service_registry
        ;;
    *)
        usage
        ;;
esac
