export const AUTH_CONSTANTS = {
  SERVICE_NAME: 'auth-service',
  SERVICE_VERSION: '1.0.0',
  DEFAULT_PORT: 3001,
  DEFAULT_ADMIN_EMAIL: 'admin@observability.io',
  DEFAULT_ADMIN_ID: 'usr-admin-001',
  DEFAULT_ADMIN_NAME: 'Observability Admin',
  DEFAULT_ADMIN_ROLE: 'admin',
  DEFAULT_ORG_ID: 'org-default-001',
  DEFAULT_ORG_NAME: 'Acme Observability',
  DEFAULT_ADMIN_PASSWORD_HASH: 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f',
  
  HEADERS: {
    CONTENT_TYPE_JSON: 'application/json',
    AUTHORIZATION: 'authorization',
    AUTHORIZATION_CAMEL: 'Authorization',
    FORWARDED_FOR: 'x-forwarded-for',
    USER_AGENT: 'user-agent',
    BEARER_PREFIX: 'Bearer ',
  },

  SECURITY_CONFIG: {
    CORS_HEADERS: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Requested-With',
      'Access-Control-Max-Age': '86400',
    },
    TOKEN_EXPIRE_SECONDS: 3600,
    SALT_ROUNDS: 10,
    PASSWORD_MIN_LENGTH: 12,
    PASSWORD_PATTERN: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*]).{12,}$',
  },

  ENDPOINTS: {
    HEALTH: '/health',
    METRICS: '/metrics',
    SIGN_UP: '/api/v1/auth/sign-up',
    SIGN_IN: '/api/v1/auth/sign-in',
    GET_SESSION: '/api/v1/auth/session',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
    CHANGE_PASSWORD: '/api/v1/auth/change-password',
    ORGANIZATIONS: '/api/v1/auth/organizations',
    ORGANIZATION_BY_ID: '/api/v1/auth/organizations/:id',
    USERS: '/api/v1/auth/users',
    USER_BLOCK: '/api/v1/auth/users/:id/block',
    USER_BY_ID: '/api/v1/auth/users/:id',
    API_KEYS: '/api/v1/auth/api-keys',
    API_KEY_VERIFY: '/api/v1/auth/api-keys/verify',
    PERMISSIONS: '/api/v1/auth/permissions',
    AUDIT_LOGS: '/api/v1/auth/audit-logs',
  },

  API_KEY_PREFIX_GENERAL: 'ak_gen_',
  API_KEY_PREFIX_TESTING: 'ak_tst_',
  API_KEY_PREFIX_SUPER_SECRET: 'ak_sec_',
  KEY_TYPE_GENERAL: 'general',
  KEY_TYPE_TESTING: 'testing',
  KEY_TYPE_SUPER_SECRET: 'super_secret',
  PERMISSION_TRACES_READ: 'traces:read',
  PERMISSION_TRACES_WRITE: 'traces:write',
  PERMISSION_METRICS_READ: 'metrics:read',
  PERMISSION_METRICS_WRITE: 'metrics:write',
  PERMISSION_LOGS_READ: 'logs:read',
  PERMISSION_LOGS_WRITE: 'logs:write',
  PERMISSION_ALERTS_READ: 'alerts:read',
  PERMISSION_ALERTS_WRITE: 'alerts:write',
  PERMISSION_ADMIN_ALL: 'admin:all',
  SPAN_DB_SYSTEM: 'db.system',
  SPAN_DB_SYSTEM_VAL: 'alloydb_omni',
  ROLE_ADMIN: 'admin',
  ROLE_MEMBER: 'member',
  ROLE_VIEWER: 'viewer',
  AUDIT_EVENT_SIGNIN: 'USER_SIGNIN',
  AUDIT_EVENT_SIGNUP: 'USER_SIGNUP',
  AUDIT_EVENT_PASSWORD_RESET: 'PASSWORD_RESET',
  AUDIT_EVENT_API_KEY_CREATED: 'API_KEY_CREATED',
} as const;
