export const AUTH_CONSTANTS = {
  SERVICE_NAME: 'auth-service',
  SERVICE_VERSION: '1.0.0',
  DEFAULT_ADMIN_EMAIL: 'admin@observability.io',
  DEFAULT_ADMIN_ID: 'usr-admin-001',
  DEFAULT_ADMIN_NAME: 'Observability Admin',
  DEFAULT_ADMIN_ROLE: 'admin',
  DEFAULT_ORG_ID: 'org-default-001',
  DEFAULT_ORG_NAME: 'Acme Observability',
  DEFAULT_ADMIN_PASSWORD_HASH: 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f',
  HEADER_AUTHORIZATION: 'authorization',
  HEADER_AUTHORIZATION_CAMEL: 'Authorization',
  HEADER_FORWARDED_FOR: 'x-forwarded-for',
  HEADER_USER_AGENT: 'user-agent',
  BEARER_PREFIX: 'Bearer ',
  API_KEY_PREFIX_GENERAL: 'ak_gen_',
  API_KEY_PREFIX_TESTING: 'ak_tst_',
  API_KEY_PREFIX_SUPER_SECRET: 'ak_sec_',
  KEY_TYPE_GENERAL: 'general',
  KEY_TYPE_TESTING: 'testing',
  KEY_TYPE_SUPER_SECRET: 'super_secret',
  PERMISSION_TRACES_READ: 'traces:read',
  PERMISSION_TRACES_WRITE: 'traces:write',
  PERMISSION_METRICS_READ: 'metrics:read',
  PERMISSION_METRICS_WRITE: 'metrics:write',
  PERMISSION_LOGS_READ: 'logs:read',
  PERMISSION_LOGS_WRITE: 'logs:write',
  PERMISSION_ALERTS_READ: 'alerts:read',
  PERMISSION_ALERTS_WRITE: 'alerts:write',
  PERMISSION_ADMIN_ALL: 'admin:all',
  SPAN_DB_SYSTEM: 'db.system',
  SPAN_DB_SYSTEM_VAL: 'alloydb_omni',
  ROLE_ADMIN: 'admin',
  ROLE_MEMBER: 'member',
  ROLE_VIEWER: 'viewer',
  AUDIT_EVENT_SIGNIN: 'USER_SIGNIN',
  AUDIT_EVENT_SIGNUP: 'USER_SIGNUP',
  AUDIT_EVENT_PASSWORD_RESET: 'PASSWORD_RESET',
  AUDIT_EVENT_API_KEY_CREATED: 'API_KEY_CREATED',
  PASSWORD_MIN_LENGTH: 12,
  PASSWORD_REGEX: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*]).{12,}$/,
} as const;
