sonar.projectKey=distributed-trace-analysis-engine
sonar.projectName=Distributed Trace Analysis Engine
sonar.projectVersion=0.1.0
sonar.language=rust
sonar.sources=src
sonar.exclusions=target/**,web/**,node_modules/**,*.json,*.yaml,*.yml
sonar.host.url=http://sonarqube:9000
sonar.token=squ_76c0c922be127a9b4e5f73461f28498afeb388a5
