receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  attributes:
    actions:
      - key: deployment.environment
        value: development
        action: upsert
      - key: service.namespace
        value: llmobs-platform
        action: upsert
      - key: network.transport
        value: tcp
        action: upsert
      - key: network.protocol.name
        value: otlp
        action: upsert

  resource:
    attributes:
      - key: infra.stack
        value: frontend-deployment
        action: upsert
      - key: infra.network
        value: llmobs-network
        action: upsert
      - key: telemetry.sdk.language
        value: collector
        action: upsert

exporters:
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes, resource, batch]
      exporters: [otlp, debug]
