receivers:
  filelog:
    include:
    - /etc/otelcol/container-logs.log
    start_at: beginning
    include_file_path: true
    include_file_name: true
    operators:
    - type: json_parser
      id: parser-json
      parse_from: body
      parse_to: attributes
processors:
  batch:
    timeout: 10s
    send_batch_size: 100
  resource:
    attributes:
    - key: service.name
      value: logs-pipeline
      action: upsert
exporters:
  loki:
    endpoint: http://loki-development:3100/loki/api/v1/push
  logging:
    loglevel: debug
service:
  pipelines:
    logs:
      receivers:
      - filelog
      processors:
      - resource
      - batch
      exporters:
      - loki
      - logging
  telemetry:
    logs:
      level: info
