receivers:
  filelog:
    include:
    - /home/j/live/dinesh/llm-chatbot-python/infrastructure/orchestrator/dynamicconfig/container-logs.log
    start_at: beginning
    include_file_path: true
    include_file_name: true
    operators:
    - type: json_parser
      id: parser-json
      parse_from: body
      parse_to: attributes
processors:
  batch:
    timeout: 10s
    send_batch_size: 100
  resource:
    attributes:
    - key: service.name
      value: logs-pipeline
      action: upsert
exporters:
  loki:
    endpoint: http://localhost:31002/loki/api/v1/push
<<<<<<< HEAD
  logging:
    loglevel: debug
=======
processors:
  batch:
    timeout: 10s
receivers:
  filelog:
    include:
    - infrastructure/orchestrator/dynamicconfig/container-logs.log
    start_at: beginning
>>>>>>> dcbfd98fbef16d9d913e8e94ea82905b860c2c85
service:
  pipelines:
    logs:
      receivers:
      - filelog
      processors:
      - resource
      - batch
      exporters:
      - loki
<<<<<<< HEAD
      - logging
  telemetry:
    logs:
      level: debug
=======
      processors:
      - batch
      receivers:
      - filelog
>>>>>>> dcbfd98fbef16d9d913e8e94ea82905b860c2c85
