// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitInstrumentationRequest {
    #[prost(string, tag="1")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub environment: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DisableInstrumentationRequest {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetStatusRequest {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectProviderRequest {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub body: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectProviderResponse {
    #[prost(string, tag="1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriggerTestCallRequest {
    #[prost(string, tag="1")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub provider: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriggerTestStreamCallRequest {
    #[prost(string, tag="1")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub chunks: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstrumentationResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration="InstrumentationStatus", tag="3")]
    pub status: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitInstrumentationResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration="InstrumentationStatus", tag="3")]
    pub status: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisableInstrumentationResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration="InstrumentationStatus", tag="3")]
    pub status: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration="InstrumentationStatus", tag="3")]
    pub status: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriggerTestCallResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration="InstrumentationStatus", tag="3")]
    pub status: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriggerTestStreamCallResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration="InstrumentationStatus", tag="3")]
    pub status: i32,
}
/// Event for publishing instrumentation state changes to Kafka
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstrumentationEvent {
    #[prost(string, tag="1")]
    pub event_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub timestamp_utc: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(enumeration="InstrumentationStatus", tag="4")]
    pub action: i32,
    /// JSON blob for extra details
    #[prost(string, tag="5")]
    pub metadata: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CountTokensRequest {
    #[prost(string, tag="1")]
    pub prompt: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub provider: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CountTokensResponse {
    #[prost(int32, tag="1")]
    pub tokens: i32,
    #[prost(string, tag="2")]
    pub method: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScanPiiInjectionRequest {
    #[prost(string, tag="1")]
    pub prompt: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ScanPiiInjectionResponse {
    #[prost(bool, tag="1")]
    pub pii_detected: bool,
    #[prost(bool, tag="2")]
    pub injection_attempt: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShouldSampleRequest {
    #[prost(string, tag="1")]
    pub span_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShouldSampleResponse {
    #[prost(bool, tag="1")]
    pub is_sampled: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InitMetricsRequest {
    #[prost(int32, optional, tag="1")]
    pub port: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetMetricsHealthRequest {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitMetricsResponse {
    #[prost(bool, tag="1")]
    pub initialized: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMetricsHealthResponse {
    #[prost(bool, tag="1")]
    pub initialized: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordMetricsRequest {
    #[prost(string, tag="1")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="4")]
    pub prompt_tokens: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="5")]
    pub completion_tokens: ::core::option::Option<i32>,
    #[prost(int64, optional, tag="6")]
    pub cost_usd_micro: ::core::option::Option<i64>,
    #[prost(int32, optional, tag="7")]
    pub latency_ms_total: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="8")]
    pub latency_ms_ttft: ::core::option::Option<i32>,
    #[prost(string, optional, tag="9")]
    pub finish_reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="10")]
    pub status: ::prost::alloc::string::String,
    #[prost(bool, tag="11")]
    pub pii_detected: bool,
    #[prost(bool, tag="12")]
    pub injection_attempt: bool,
    #[prost(int32, tag="13")]
    pub retry_count: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordMetricsResponse {
    #[prost(bool, tag="1")]
    pub recorded: bool,
    #[prost(int64, optional, tag="2")]
    pub cost_usd_micro: ::core::option::Option<i64>,
    #[prost(string, optional, tag="3")]
    pub price_version: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordMetricsBatchRequest {
    #[prost(message, repeated, tag="1")]
    pub spans: ::prost::alloc::vec::Vec<RecordMetricsRequest>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RecordMetricsBatchResponse {
    #[prost(int32, tag="1")]
    pub recorded_count: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEmbeddingRequest {
    #[prost(string, tag="1")]
    pub text: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEmbeddingResponse {
    #[prost(float, repeated, tag="1")]
    pub embedding: ::prost::alloc::vec::Vec<f32>,
}
/// InstrumentationStatus represents the current state of auto-instrumentation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InstrumentationStatus {
    Unspecified = 0,
    Initialized = 1,
    Disabled = 2,
    Partial = 3,
}
impl InstrumentationStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            InstrumentationStatus::Unspecified => "INSTRUMENTATION_STATUS_UNSPECIFIED",
            InstrumentationStatus::Initialized => "INSTRUMENTATION_STATUS_INITIALIZED",
            InstrumentationStatus::Disabled => "INSTRUMENTATION_STATUS_DISABLED",
            InstrumentationStatus::Partial => "INSTRUMENTATION_STATUS_PARTIAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INSTRUMENTATION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "INSTRUMENTATION_STATUS_INITIALIZED" => Some(Self::Initialized),
            "INSTRUMENTATION_STATUS_DISABLED" => Some(Self::Disabled),
            "INSTRUMENTATION_STATUS_PARTIAL" => Some(Self::Partial),
            _ => None,
        }
    }
}
/// LLMSpan represents a single, raw observability span for an LLM call.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LlmSpan {
    /// Generated before API call (UUID v4)
    #[prost(string, tag="1")]
    pub span_id: ::prost::alloc::string::String,
    /// Propagated from caller (UUID v4), nullable
    #[prost(string, optional, tag="2")]
    pub trace_id: ::core::option::Option<::prost::alloc::string::String>,
    /// For tool-call chains (UUID v4), nullable
    #[prost(string, optional, tag="3")]
    pub parent_span_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Bump on breaking change. Hardcoded = 1
    #[prost(int32, tag="4")]
    pub schema_version: i32,
    /// SDK config ('gpt-4o', etc)
    #[prost(string, tag="5")]
    pub model: ::prost::alloc::string::String,
    /// SDK config ('openai', 'anthropic', etc)
    #[prost(string, tag="6")]
    pub provider: ::prost::alloc::string::String,
    /// SDK config ('checkout-service')
    #[prost(string, tag="7")]
    pub service_name: ::prost::alloc::string::String,
    /// SDK decorator arg ('/api/summarize')
    #[prost(string, tag="8")]
    pub endpoint: ::prost::alloc::string::String,
    /// SDK config
    #[prost(enumeration="Environment", tag="9")]
    pub environment: i32,
    /// SDK call arg. Null for anonymous
    #[prost(string, optional, tag="10")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    /// SDK call arg. Null for stateless
    #[prost(string, optional, tag="11")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Exact BPE count, > 0
    #[prost(int32, tag="12")]
    pub prompt_tokens: i32,
    /// Exact BPE count, >= 0
    #[prost(int32, tag="13")]
    pub completion_tokens: i32,
    /// Time to first chunk byte
    #[prost(int32, optional, tag="14")]
    pub latency_ms_ttft: ::core::option::Option<i32>,
    /// Full wall clock, > 0
    #[prost(int32, tag="15")]
    pub latency_ms_total: i32,
    /// Provider response finish reason
    #[prost(enumeration="FinishReason", tag="16")]
    pub finish_reason: i32,
    /// SDK computed cost in micro-USD, >= 0
    #[prost(int64, tag="17")]
    pub cost_usd_micro: i64,
    /// SDK config price version date
    #[prost(string, tag="18")]
    pub price_version: ::prost::alloc::string::String,
    /// SDK token method
    #[prost(enumeration="TokenCountMethod", tag="19")]
    pub token_count_method: i32,
    /// TRUE if hash(span_id) % 100 == 0
    #[prost(bool, tag="20")]
    pub is_sampled: bool,
    /// 0 for first-attempt calls
    #[prost(int32, tag="21")]
    pub retry_count: i32,
    /// Fallback chains
    #[prost(string, repeated, tag="22")]
    pub attempted_models: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Aho-Corasick computed inline before emit
    #[prost(bool, tag="23")]
    pub pii_detected: bool,
    /// Aho-Corasick jailbreak/injection pattern matched
    #[prost(bool, tag="24")]
    pub injection_attempt: bool,
    /// SDK (client clock) UTC, ISO 8601 string or Unix nanoseconds.
    #[prost(string, tag="25")]
    pub timestamp_utc: ::prost::alloc::string::String,
    /// SAMPLED-ONLY FIELDS
    /// SHA256(prompt_text) 64-char hex. Null if pii_detected.
    #[prost(string, optional, tag="26")]
    pub prompt_hash: ::core::option::Option<::prost::alloc::string::String>,
    /// MiniLM-L6-v2 384-dim vector. Null if pii_detected.
    #[prost(float, repeated, tag="27")]
    pub prompt_embedding: ::prost::alloc::vec::Vec<f32>,
    /// MiniLM-L6-v2 384-dim vector. Null if pii_detected.
    #[prost(float, repeated, tag="28")]
    pub response_embedding: ::prost::alloc::vec::Vec<f32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordSpanRequest {
    #[prost(message, optional, tag="1")]
    pub span: ::core::option::Option<LlmSpan>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordSpanResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    /// For returning W-series warnings
    #[prost(string, repeated, tag="2")]
    pub span_warnings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// FinishReasonEnum captures the possible ways an LLM generation can complete.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FinishReason {
    Unspecified = 0,
    Stop = 1,
    Length = 2,
    ContentFilter = 3,
    Timeout = 4,
    ToolCalls = 5,
    CacheHit = 6,
    ClientDisconnect = 7,
}
impl FinishReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FinishReason::Unspecified => "FINISH_REASON_UNSPECIFIED",
            FinishReason::Stop => "FINISH_REASON_STOP",
            FinishReason::Length => "FINISH_REASON_LENGTH",
            FinishReason::ContentFilter => "FINISH_REASON_CONTENT_FILTER",
            FinishReason::Timeout => "FINISH_REASON_TIMEOUT",
            FinishReason::ToolCalls => "FINISH_REASON_TOOL_CALLS",
            FinishReason::CacheHit => "FINISH_REASON_CACHE_HIT",
            FinishReason::ClientDisconnect => "FINISH_REASON_CLIENT_DISCONNECT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FINISH_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "FINISH_REASON_STOP" => Some(Self::Stop),
            "FINISH_REASON_LENGTH" => Some(Self::Length),
            "FINISH_REASON_CONTENT_FILTER" => Some(Self::ContentFilter),
            "FINISH_REASON_TIMEOUT" => Some(Self::Timeout),
            "FINISH_REASON_TOOL_CALLS" => Some(Self::ToolCalls),
            "FINISH_REASON_CACHE_HIT" => Some(Self::CacheHit),
            "FINISH_REASON_CLIENT_DISCONNECT" => Some(Self::ClientDisconnect),
            _ => None,
        }
    }
}
/// TokenCountMethod captures how the token counts were determined.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TokenCountMethod {
    Unspecified = 0,
    Tiktoken = 1,
    Estimated = 2,
}
impl TokenCountMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TokenCountMethod::Unspecified => "TOKEN_COUNT_METHOD_UNSPECIFIED",
            TokenCountMethod::Tiktoken => "TOKEN_COUNT_METHOD_TIKTOKEN",
            TokenCountMethod::Estimated => "TOKEN_COUNT_METHOD_ESTIMATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOKEN_COUNT_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
            "TOKEN_COUNT_METHOD_TIKTOKEN" => Some(Self::Tiktoken),
            "TOKEN_COUNT_METHOD_ESTIMATED" => Some(Self::Estimated),
            _ => None,
        }
    }
}
/// Environment Enum captures the deployment environment.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Environment {
    Unspecified = 0,
    Production = 1,
    Staging = 2,
    Dev = 3,
}
impl Environment {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Environment::Unspecified => "ENVIRONMENT_UNSPECIFIED",
            Environment::Production => "ENVIRONMENT_PRODUCTION",
            Environment::Staging => "ENVIRONMENT_STAGING",
            Environment::Dev => "ENVIRONMENT_DEV",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENVIRONMENT_UNSPECIFIED" => Some(Self::Unspecified),
            "ENVIRONMENT_PRODUCTION" => Some(Self::Production),
            "ENVIRONMENT_STAGING" => Some(Self::Staging),
            "ENVIRONMENT_DEV" => Some(Self::Dev),
            _ => None,
        }
    }
}
include!("llm.observability.v1.tonic.rs");
// @@protoc_insertion_point(module)