from typing import Protocol, runtime_checkable


@runtime_checkable
class SessionStorePort(Protocol):
    def add_peer(self, room_id: str, peer_id: str) -> None: ...

    def remove_peer(self, room_id: str, peer_id: str) -> None: ...

    def get_peers(self, room_id: str) -> list[str]: ...

    def room_exists(self, room_id: str) -> bool: ...
